### ISSUE TITLE
Security Investment Report - Add/Update/Delete operations 

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#100]
Name: Sriram Avasarala
Organization: Treasury
Urgency: High
Description of Issue: How do we submit the Security Investment Report Adds , Updates and Deletes. The Operation tag was removed from the latest schema changes in V1.9.6. The sample file doesn't provide information about add, update and delete (inactive) operations.

**Comment by GihaVillazon** [comment]
Hi Sriram, 

We are still working towards the SIR XMLs, there was consideration about simplifying the XML, however the decision was to provide the mentioned tags back. They will be added back for to SIRs. 

Thank You.

**Comment by SriramAvasarala** [comment]
Giha, When are you planning to publish the updated schema for SIR with the Add/update/Delete operations?

**Comment by GihaVillazon** [comment]
Hi Sriram,

The Schema updates were published on Monday 8/14, which includes the tags.

Thank You.

**Comment by SriramAvasarala** [comment]
Hi Giha, Are you referring to this? https://github.com/ombegov/ITDB-schema/commit/2d5b500d75e878032f9d6766756bc2bab249ab71

**Comment by GihaVillazon** [comment]
Yes, is that what you were looking for?

Thank You.

**Comment by SriramAvasarala** [comment]
Yes, delete is an operation similar to add/update or is it part of update with inactive flag?

**Comment by GihaVillazon** [comment]
Delete operation was initiated for an investment for changing the SIR type, but note that users will be able to do this simply by submitting an update, therefore yes it is similar operation. 

Thank You.

**Comment by SriramAvasarala** [comment]
I am referring to delete a capability that was submitted as an Add not SIR. Do I submit the Capability with Operation as Delete (or) Do I submit the Capability with Operation as Update with IsActive flag as deactivated.

**Comment by GihaVillazon** [comment]
We are not using isActive flags for SIR. 
To delete an item within an investment, you set the operation to “delete” and provide either the OMB ID or agency ID related to the record you want to delete, however this feature is still work in progress. 

Thank You.

**Comment by GihaVillazon** [comment]
GM, 
I am closing this ticket, should you need further clarification we can reopen the ticket or create a new one. 

Thank You.
