### ISSUE TITLE
Bureau Code and Agency Code Missing

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#101]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: The nodes for the Bureau Code and Agency Code have all been removed from xsd for the Tower Details section for the Standard Investment Report. These fields are still part of the Guidance for the Data Center SIR. 

Was this by design since the same fields are collected within the AITPS?

**Comment by GihaVillazon** [comment]
Hi Ryan,

That is correct since the information is collected in AITPS, to lessen the reporting burden we removed the nodes from SIR. 

Thank You.
