### ISSUE TITLE
SIR - Adding/Updating/Removing Contracts, Projects, Etc.

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#102]
If I'm reading this correctly, the following tags are used to indicate if we are adding or updating contracts, etc:

1. Contracts - acquistionStrategy
2. Projects - description
3. Metrics - description
4. Metric Actuals - comment
5. Capability - purposeOrOutcome

If I'm correct in this understanding, it's a bit confusing.  For Projects, description is an existing data field not used for this purpose.  For Metrcis, description is an existing data field not used for this purpose.  For Metric Actuals, comment is an existing data field not used for this purpose.  Finally, for Capabilities, purposeOrOutcome is an existing data field not used for this purpose.

Can you help me clear up this confusion?  Are we no longer using these data fields for their original purposes?

How do we remove contracts, projects, etc. from SIRs?

**Comment by courtneycorwin** [comment]
Hi Again,

Ok, so now I see the operation tags again (it looks like there was an update about 7 hours ago).  So, let me edit my question:

1. acquisitionStrategy isn't defined in the guidance (the version I have is from 6/1/2017, it's possible I missed an update), so what is it for?

2. For the other tags I mentioned above (like description) where they already serve another purpose, are we just going back to that original definition?  So, for projects, description would be a brief description of the project and most like not "Add project"?

3.  it looks like add and update are valid values for the operations tag.   Is there a remove option as well?

Thanks!!

**Comment by courtneycorwin** [comment]
I found acquisitionStrategy definition. I'm good there.  I look forward to a response to my other questions.  Thanks!

**Comment by GihaVillazon** [comment]
Hi Courtney,


2.For the other tags I mentioned above (like description) where they already serve another purpose, are we just going back to that original definition? So, for projects, description would be a brief description of the project and most like not "Add project"? 
**Not sure what your question is here, but yes project description definition = Brief description of the project.**
3.it looks like add and update are valid values for the operations tag. Is there a remove option as well?
The tags available:
Update
Add
Delete.

Thank You.

**Comment by courtneycorwin** [comment]
Fantastic, thank you!  Just a quick follow up on the operations tag:

1. What's the minimum required information to run a delete operation at the project, contract, etc. level?  Would just sending the associated agencyID be enough to remove the record?

2. Is there a single accepted order of operation?  i.e. do add operations have to go first, then update operations etc?   Or will the order not matter?

3.  What's the minimum necessary information necessary at the investment level for the delete operation?  For example if an investment changed from a Network Investment to a Data Center Investment (unlikely, I understand) so I want to remove the Network SIR information and replace it with the Data Center SIR information, would a delete operation along with the UII be sufficient?  Or will the delete operation not be valid at that level?

Thanks!!

**Comment by GihaVillazon** [comment]
1. You’ll only need to provide the operation tag and either the OMB ID or agency ID to delete a record. note: delete operation will probably not be ready for the 8/22 release
2. There is no required order of operations for SIR.
3. The delete operation for investment level will also probably not be ready for the 8/22 release, but when it is done, you’ll only need to provide the operation tag and the UII to delete the investment. 

Also note that the use case described for needing to delete an investment was for changing the SIR type, but note that users will be able to do this simply by submitting an update. The system will automatically prune any orphan records that result from changing a SIR from one type to another.

Thank You.

**Comment by courtneycorwin** [comment]
That is good to know - that changing the type won't require us to do anything else but to submit a new SIR.  Thanks for the response!

**Comment by GihaVillazon** [comment]
NP! I will close the ticket, if needed further clarification we can reopen the ticket. 

Thank You.

**Comment by murrayalex** [comment]
Circling back on this, we are still receiving an error that the 'delete' operation is not available. Will this be made available in the release tomorrow night? This is high priority for us.

Error 1840: Element 'operation': [facet 'enumeration'] The value 'delete' is not an element of the set {'add', 'update', 'get'}. on line 1

**Comment by danielwyork** [comment]
@ojedanico @GihaVillazon - Please reopen this ticket until the above question is answered. I don't seem to have permissions to re-open tickets.

**Comment by ojedanico** [comment]
The Infrastructure Management Category for each investment submitted in the IT Portfolio dictates which type of SIR you will need to fill out later. If an Infrastructure Management Category is entered wrong in the IT Portfolio submission, the only way for us to fix it is on the backend since it requires changing an IT Portfolio record after the IT Portfolio submission window has closed.

**Comment by murrayalex** [comment]
Hey Nico,

Not sure if your response was added to the right issue. I am not trying to change the Infrastructure Management Category. This is regarding deleting a previously submitted piece of data from the ITDB for an SIR. For example, removing a contract that was previously submitted incorrectly.

**Comment by ojedanico** [comment]
sorry my comment was geared more to Courtney's post 

Alex, 
What specifically do you what to be able to delete - projects, contracts, and metrics?
and what does it mean to be deleted/can they re-use IDs/?

**Comment by murrayalex** [comment]
For MITBC, Agencies can remove contracts, metrics, projects, activities, risks, etc. Essentially, anything that is not a single data point for the whole investment. We assume that this would be the same for SIRs. If so, then we need the ability (and i thought we had agreed on it above) to delete previously submitted, metrics, metric actuals, contracts, projects, and capabilities.

**Comment by ojedanico** [comment]
Ok we are building out same way as add and update function, for the following sections metrics, metric actuals, contracts, projects, and capabilities and will be in the 9A release for Sept 6th.

**Comment by ojedanico** [comment]
Error message will be created to replace the server error to stop timing out issue in ticket 898 for 9a Hotfix 1 scheduled for 9/8.

**Comment by TsitsiL** [comment]
ITD-898 deployed on 9/8/17. Closing this issue.
