### ISSUE TITLE
ITP Validation error message doesn't display UII 

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#103]
Name: Sriram Avasarala
 Organization: Treasury
 Urgency: Medium
 Description of Issue: The validation error messages doesn't provide UII information for the validation  errors. It will be very hard to fix the errors without having the UII for 300+ ITP's.

Sample error message:

Status Information
XML processed!
• IT Budget submission failed
◦ **IT Portfolio with UII: :**
Error: Total IT Security Spending for BY (0.000001) cannot be greater
than the sum of DME and O&M Agency BY Funding (0).

**Comment by GihaVillazon** [comment]
Hi Sriram,

This error is displayed within the ITPorfolio object that represents the investment, which should assist in determining the UII, similarly  as with all other investment-level errors. 

Thank You.

**Comment by SriramAvasarala** [comment]
I have validated the xml today and the error message display UII information after 8/16 code deployment. Thanks.

**Comment by GihaVillazon** [comment]
Great, I will close this ticket. 

Thank You.
