### ISSUE TITLE
ITP : DataCenterID validation error.

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#104]
Name: Sriram Avasarala
 Organization: Treasury
 Urgency: Medium
 Description of Issue:  We are getting the following validation error when we submit the ITP with the Data center tag as "< DataCenterInventory /> when there is no Data Center ID. As per the schema the Data Center ID is optional.

Error message:
Error: Data Center ID '' must match "DCOI-XX-12345" where "XX" is a
state abbreviation.

**Comment by ojedanico** [comment]
Sriram,

Are you guys putting in a zero or omitting the node? if you are putting a zero it seeing a value and therefore the validation is requiring you to put a DataCenterID.

**Comment by SriramAvasarala** [comment]
Nico,

We are not putting zero's, we are send the tag as "< DataCenterInventory />" , the type is a text type, and it should accept null value. I sent the XML file to support email at 2.23 pm in case if you want to look at the XML file.

**Comment by GihaVillazon** [comment]
Hi Sriram,

You can omit the tag entirely, since there is not data to report. It should not give any error. 

Thank You.

**Comment by SriramAvasarala** [comment]
Thanks Giha. The errors are gone after we omit the tag. You can close this ticket.
