### ISSUE TITLE
Production URL

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#107]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: What is the Production URL for submissions this year? Should Agencies be submitting to itdashboard.gov or myit-2019.itdashboard.gov during the September 5th - September 15th window?

**Comment by GihaVillazon** [comment]
Hi Ryan,

Production URL: https://myit-2019.itdashboard.gov 

**BY19 SUBMISSION DATES:** 

BY19 Agency IT Portfolio:
o   Submission Dates: 9:00AM EST, Tuesday September 5, 2017 – 6:00PM EST, Friday September 11, 2017
 
BY19 Major IT Business Case and Standard Investment Reports:
o   Submission Dates: 6:30PM EST, Tuesday September 11, 2017 – 6:00PM EST, Friday September 15, 2017

Thank You.

**Comment by murrayalex** [comment]
Hey Giha,

It looks like the business case schedule has changed here. Can you clarify what will be available starting on September 5th for the Major IT Business Case? Obviously, an Agency can't submit a business case until after their portfolio, so will they be limited to only validations until after 6pm on Monday, September 11th?

It was our understanding from the call yesterday that no Major IT Business Case operations to the production dashboard would be available until 630pm on September 11.

**Comment by GihaVillazon** [comment]
Hi Ryan,

Yes that is correct. I have made the needed edits on the submission dates. 

Thank You.

**Comment by murrayalex** [comment]
Thanks, Giha. One more clarification. You listed "Friday, September 11" and "Tuesday, September 11". Should those both be "Monday, September 11"?

**Comment by GihaVillazon** [comment]
Thanks Ryan. it's edited :)
