### ISSUE TITLE
CIO Rating API Submission

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#108]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: Does OMB intend to exclude Major Investments from submitting CIO Ratings through the CIO Rating API? If this is the case, will Major Investments still be able to submit CIO Ratings through the Business Case API using Monthly submissions? 

For reference, I am receiving the following error:

Error: Unique Investment Identifier 011-000002616 is for a major investment.  Agencies are required to submit a CIO Evaluation Report for all of their major investments, Type 01, during business case submission.

**Comment by rydougherty** [comment]
Following up here, we would recommend allowing all investments to submit their CIO Ratings through the CIO Rating API in order to maximize flexibility and simplicity. Major Investments could still submit CIO Ratings through the Business Case API while performing Annual submissions. This was also the approach that was articulated throughout the White-boarding Sessions.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

CIO evaluation is expected to be submitted through the business case for all major investments. Since it is optional for other investments it will have a separate API submission for the optional investments only.

Thank You.

**Comment by rydougherty** [comment]
Can you open up the CIO Rating API to accept all types of investments? I understand that CIO Ratings are required for Major Investments. But, CIO Ratings will be submitted through the Business Case API for the Annual, where you can still enforce this requirement. For the remainder of the year, you should be able to submit your CIO Ratings through the CIO Rating API.

This was the implementation that was agreed upon at the White-boarding Sessions.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

We will visit this feature. With the tight time crunch we can add this into a future release. 

Thank You.

**Comment by murrayalex** [comment]
Hey Giha,

Given that we (eCPIC Team) will have to modify our code to send them to separate APIs, we would like to rescind the request to combine them in the future. We recommend that the CIO ratings remain sent to the business case API for majors and the CIO Rating API for all other investments.

**Comment by GihaVillazon** [comment]
ok, will ensure no changes are made to the future releases unless requested. 
I will also close this ticket.

Thank You.
