### ISSUE TITLE
Network Investment Report - Project Output

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#112]
In the guidance, Project Output is defined as "In an IPv6 transition, number of nodes upgraded to IPv6, in a VoIP transition, number of phones upgraded to VoIP."  In your example file, output is "hello world" - a text only value.  Based on the guidance definition, I would expect to only be able to send integers. What's the expected value for this element?

**Comment by GihaVillazon** [comment]
Hi Courtney,

Data Dictionary has the field noted as "Integer" Values. If you have an issue in submission certainly let us know, however integer is the expected value. 

Thank You.

**Comment by GihaVillazon** [comment]
Hi Courtney,

Sample file was also fixed with the 08B. please let us know if you have further issues. 

Thank You.

**Comment by courtneycorwin** [comment]
That's what I thought - I appreciate you verifying for me!

**Comment by GihaVillazon** [comment]
NP! I will close this ticket. 

Thank You.
