### ISSUE TITLE
Acquisition/Contract Strategy - IT Lease - "Not Applicable" is missing

### ISSUE THREAD

**Issue by suchun** [ombegov/ITDB-schema#113]
Name: Sue Hu
Organization: Treasury
Urgency: Medium
Release v1.9.6 - The IT Lease collection has not been updated with FY19 values, the new value "Not Applicable" is not included as the enum only goes up to 5.

**Comment by GihaVillazon** [comment]
Hi Sue, 

Would please retest this concern as it was addressed in 08B.

Thank You.

**Comment by suchun** [comment]
It is fixed in the new release.
