### ISSUE TITLE
Set CIO Rating Operation

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#116]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: When attempting to submit a CIO Rating to the Business Case API, I am receiving the following error: 

Unsupported operation: tns:setCIORating

I will email over my request file.

**Comment by GihaVillazon** [comment]
Hi Ryan,

The annual submission collects the CIO Rating via a “cioRating" element, not “setCIORating". The “setCIORating” element name is used by the monthly operation only.

Please try once again, 

Thank You.

**Comment by rydougherty** [comment]
HI Giha- thanks for the response. Looking at the Monthly Submission Examples files in the xsd the following is listed out for CIO Rating:
`      <setCIORating id="String">
        <cioRatingEval>1</cioRatingEval>
        <cioComment>a</cioComment>
      </setCIORating>`

Furthermore when i attempt to submit the following to the business case API, I receive and error indicating setCIORating should be used:
Request:
`					<tns:updateCIORating id="dee6ef4c-a33a-424a-a37e-7b25ee2082c7">
						<tns:cioRatingEval>3</tns:cioRatingEval>
						<tns:cioComment>Changing Rating</tns:cioComment>
					</tns:updateCIORating>`
Error: Error 1871: Element '{http://www.itdashboard.gov/service}updateCIORating': This element is not expected. Expected is one of ( {http://www.itdashboard.gov/service}updateContract, {http://www.itdashboard.gov/service}addContract, {http://www.itdashboard.gov/service}updateAcquisition, {http://www.itdashboard.gov/service}addAcquisition, {http://www.itdashboard.gov/service}updateSystem, {http://www.itdashboard.gov/service}addSystem, {http://www.itdashboard.gov/service}addPerformanceMetric, {http://www.itdashboard.gov/service}updatePerformanceMetric, **{http://www.itdashboard.gov/service}setCIORating**, {http://www.itdashboard.gov/service}updateOperationalAnalysis ). on line 5

**Comment by GihaVillazon** [comment]
Hi Ryan, 

Would you please send over the file, we will analyze the issue and get back to you. 

Thank You.

**Comment by ojedanico** [comment]
This issue will be addressed with Jira ticket 867 to be deployed with 9a release.

**Comment by GihaVillazon** [comment]
Hi Ryan,

Could you please send over the file associated with this issue, as we would like to look deeper into the root cause of the issue. 

Thank You.
