### ISSUE TITLE
List of bureau codes

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#117]
Can you provide a list of bureau codes for all departments (or at least DHS).  They have indicated to me that there are some new bureau designations for some HQ investments that are new values - 15 and 18 in department DHS 024.

**Comment by GihaVillazon** [comment]
Hi Barry,

Please review the attachment. It does not contain 15 and 18. 
We will have to research further for the bureau codes 15 & 18 

Thank You.


[refBureau.zip](https://github.com/ombegov/ITDB-schema/files/1244052/refBureau.zip)

**Comment by GihaVillazon** [comment]
Hi Barry, 

We are in Midst of updating the Database, to accommodate the request. We will further discuss this during the 1 P.M. Meeting today. 

Thank You.

**Comment by ojedanico** [comment]
Barry,
here is what I pulled from the A11 appendix C which is the official list - let me know if this does not add up

<img width="487" alt="dhs" src="https://user-images.githubusercontent.com/29411438/29639849-3b5d9158-882a-11e7-897c-bfece756519a.PNG">
