### ISSUE TITLE
Data Center ID Validations

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#118]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: There is a validation error that prevents Agencies from submitting Data Center investments without providing a valid Data Center ID. The valid Data Center ID  list is generated from the IDC that the 24 CFO Act Agencies submit. However, NARA and USACE are not CFO Act Agencies, and therefore, do not have Data Center IDs associated with the IDC. How should NARA and USACE proceed with submitting Data Center investments? Can the valid Data Center ID errors be relaxed to just warnings?

**Comment by GihaVillazon** [comment]
Hi Ryan,

That is correct thank you for pointing that out, we have made changes to exclude NARA and USACE from Data Center Id validations. Fix will be deployed with 08B Hotfix.

Thank You.
