### ISSUE TITLE
IT Portfolio Validation errors

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#119]
Name: Sriram Avasarala
Organization: Treasury
Urgency: High
Description of Issue: We are getting following validation errors that are not allowing us to submit ITPs.  

Error: For investments with Standard IT Infrastructure and
Management Category as '02' the Total IT Security Spending for PY (2)
must be equal to the sum of DME and O&M Agency PY Funding and
Contributions (1).
Error: For investments with Standard IT Infrastructure and
Management Category as '02' the Total IT Security Spending for CY (1)
must be equal to the sum of DME and O&M Agency CY Funding and
Contributions (2).
Error: For investments with Standard IT Infrastructure and
Management Category as '02' the Total IT Security Spending for BY
(3) must be equal to the sum of DME and O&M Agency BY
Funding and Contributions (1).

**Comment by GihaVillazon** [comment]
Hi Sriram,

Please share the submission files and response file through the HD mailbox. 

Thank You.

**Comment by GihaVillazon** [comment]
Hi Sriram,

Thank You for the files, however we will also need the response file.

Thank You.

**Comment by SriramAvasarala** [comment]
Giha, I sent the response to support email around 12 pm.

**Comment by SriramAvasarala** [comment]
Giha, Any update on this issue?

**Comment by GihaVillazon** [comment]
Hi Sriram, 

The noted validations are correct error messages if the data is not submitted accurately, however there is a bit of language which needs to be edited. 

Error: For investments with Standard IT Infrastructure and
Management Category as '02' the **Total IT Security and Compliance** for BY must be equal to the sum of DME and O&M Agency BY Funding and Contributions.

Please let us know should you have further questions. 

Thank You.

**Comment by SriramAvasarala** [comment]
Hi Giha,

The Total IT Security and Compliance tower cost **can be less than or equal** to the sum of DME and O&M Agency Funding and Contributions. As per the guidance Total IT Security and Compliance tower cost **doesn't need to be equal** to the  sum of DME and O&M Agency Funding and Contributions (Funding Source).  
I am **not** getting these errors now. It looks like the some kind of code fix was made on your end to exclude these validations. 

Thanks,
Sriram
