### ISSUE TITLE
Successful Submission Showing as an Error

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#120]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The IT Dashboard is returning a "Successful Submission" status underneath an Errors and Warnings node for SIR response files. See the example below:

`        <ErrorsAndWarnings>
            <towerDetails/>
            <status>Submission Successful</status>
        </ErrorsAndWarnings>`

We would expect a Successful Submission response to be indicated in the root, just like the Business Case.

**Comment by ojedanico** [comment]
moving forward 
Errors and Warnings will appear in 2 locations. One is in a node called "ErrorsAndWarnings". That element is included as a child of the parent node, so in the case of towerDetails it will appear in that element. In elements that nest like projects or contracts, it will appear in the respective child node.
	
Errors and Warnings also appear in the "response" element. They appear in summary form relative to each section, along with the submission status for a given tower.
