### ISSUE TITLE
Add and Update Operation SIR Response File 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#123]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: We are looking for a sample response file that mimics what is returned following an Add or Update SIR submission.

In addition, we are looking for information on how the IT Dashboard will treat blank projects, contracts, metrics etc in these response files. Since all nodes are optional within the SIRs, we expect Agencies will, in certain circumstances, omit projects or contracts altogether from submissions. If this is the case will the Projects/Contracts nodes be dropped altogether, or will blank nodes be sent back?

Currently I have submitted a Network Investment with no Cost Details, Contracts, Projects, or Metrics. Contracts, Projects, and Metrics are all fully omitted, while investmentCostDetails sends a node with a single blank child. Can OMB provide some guidance if these instances will be handled consistently across the board?

Current Response File:

`<tower>
    <operation>get</operation>
    <towerDetails>
        <UII>011-000100011</UII>
        <dataCenterID/>
        <federalRealPropertyProfileID/>
        <description>network description change</description>
        <anticipatedEISTransitionDate>2017-08-09</anticipatedEISTransitionDate>
    </towerDetails>
    <investmentCostDetails>
        <investmentCostDetail />
    </investmentCostDetails>
</tower>`

**Comment by ojedanico** [comment]
Here are some of the response files requested 


[SubmissionResponseGuide.txt](https://github.com/ombegov/ITDB-schema/files/1246825/SubmissionResponseGuide.txt)

Note: Just be mindful that this not set in stone until the hotfix gets deployed August 28th.

**Comment by ojedanico** [comment]
[SubmissionResponseExample.txt](https://github.com/ombegov/ITDB-schema/files/1246843/SubmissionResponseExample.txt)

**Comment by rydougherty** [comment]
Hi Nico- Thanks for posting these files, they will be beneficial moving forward with our development prior to next Tuesday. We have three issues are still seeking clarification on for the response files:

1. Can you also provide an example of what a successful submission file would look like?
2. How would a file display multiple towers (investments)? We noticed the parent tags were <Tower1>, would the towers be itemized, ie <Tower1> <Tower2> <Tower3>? Or, can OMB just use <Tower> as the the overarching parent for each investment? We would expect to just use <Tower> given that we are moving away from the itemization.
3. The OMB IDs are listed at the the very bottom of each cluster, see example below. This is not the order in which we send the OMB IDs to the Dashboard in the Request files, so its placement in the Response is odd.

`<contract>
          <operation>add</operation>
          <agencyContractID>EndUser-Contract-123</agencyContractID>
          <status>existing</status>
          <PIID>12345</PIID>
          <acquisitionStrategy>Add contract</acquisitionStrategy>
          <solicitationID>12345</solicitationID>
          <comment/>
          <contractType>Workspace</contractType>
          <isPhysicalDataCenter>no</isPhysicalDataCenter>
          <isIPv4Permitted>no</isIPv4Permitted>
          <taskOrderCompletionDate>2018-02-20</taskOrderCompletionDate>
          **<contractID>4898</contractID>**`

**Comment by ojedanico** [comment]
1. We can create additional response file examples if needed. I think the following options should cover all bases:
•	Single tower submission success response
•	Single tower submission failure response
•	Multiple towers submission success response
•	Multiple towers submission failure response
•	Multiple towers submission mixed success and failure response
•	Single tower get response
•	Multiple towers get response

2. For responses with multiple towers, the <tower> tag is repeated for each tower.

3. In contrast to Business Case, the SIR schema does away with requiring elements to be in a certain order. This was intended to make the schema more flexible and extendable, but I can see how it might also be annoying when the response returns elements in a different order than they were submitted. If the order of elements is deemed by vendors to be a really important feature, I suppose we could implement that, but it would be a pretty big LOE at this point.

**Comment by rydougherty** [comment]
Thanks Nico- the options under point 1 are extensive and would capture all response files we would need. For point 2, I just want to confirm that the <Towers> tag will be used instead of <Tower1>? For point 3, we are currently investigating whether we could handle a random order of child nodes.

**Comment by rydougherty** [comment]
Upon further review, we are also trying to figure out why errors and warnings appear twice: once alongside the "request data" (top half of the response file) and once alone underneath a response node (bottom half of the response file)? This is problematic because there is no way to link a tower under the response node to the "request data" in the top half of the file. Complicating the matter, the submission status only appears under the response node in the bottom half. This means there is no way to tie a successful submission back to a specific investment. 

The most straightforward workaround would be to move the submission status value into the "request data" top half and delete the entire bottom half of the response file. Another possible solution, though substantially clunkier, would be to place a UII node in the bottom half of the response file, underneath the response and tower nodes.

If this would be easier to discuss over the phone, please let me know.

**Comment by ojedanico** [comment]
Based on our conversation on Friday we are in agreement to keep this as is.
