### ISSUE TITLE
Total IT Security Spending Errors

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#124]
Several agencies are getting errors regarding Total IT Security Spending (which is no longer reported). Assuming that these validations transferred to the Total IT Security and Compliance Cost Tower, they're still incorrect.  I've confirmed, for example, that the investments tripping the error have Total IT Security and Compliance Cost Tower amounts that match the funding source amounts.

**Comment by GihaVillazon** [comment]
The issue was fixed with 08B hotfix 1.

Thank You.
