### ISSUE TITLE
Data Center ID SIR Error

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#126]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: We are receiving the following error while submitting an Data Center SIR update:

Error: dataCenterID is required for report type 05.

This validation is not checking if a dataCenterID is already on the Dashboard. Our submission is not updating the dataCenterID, however, a dataCenterID was previously submitted for this investment, so this error should not trigger.

**Comment by GihaVillazon** [comment]
Hi Ryan,

while submitting an update did you leave the dataCenterID off, thinking it was optional because you have already provided it in the add?

IF so that is incorrect. 
While most SIR fields are indeed optional for updates, dataCenterID happens to be defined as a required field for Data Center SIRs. You cannot submit an update that omits it.

Please Confirm.
Thank You.

**Comment by rydougherty** [comment]
Yes, the dataCenterID is not changing so it is left off of the update request file. Can you please explain why this would trigger an error, though? 

The Data Center ID field is required on IT Dashboard. So, during the initial add operation the dataCenterID node must be required to appear in the submission file. However, once the Data Center ID is on the Dashboard, that validation should be dropped (for update files).

Only data changes get submitted to the IT Dashboard in the update operation files. So, if the Data Center ID is not changing, the dataCenterID node will be omitted from update submissions.

**Comment by GihaVillazon** [comment]
Hi Ryan,

We will make the change the Data Center ID for updates will not be needed, this will be deployed with 08B Hotfix.

Thank You.

**Comment by rydougherty** [comment]
Was the Data Center ID dropped altogether for the SIR? We are only able to add a Data Center Investment Report by omitting the Data Center ID node.

**Comment by rydougherty** [comment]
Can OMB please confirm if this was intentional? If we are expected to drop the Data Center IDs from all Data Center SIR submissions, let us know. Right now this error is preventing us from testing critical parts of our application.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

looking into this, the only time you will not need to provide the Data Center Id is while performing updates. Please allow me to circle back on this concern.

Thank You.

**Comment by austin-moffa** [comment]
Hi Ryan,
The removal was intentional. We had an internal discussion and we found that collection it in the SIR submission was redundant/potentially harmful since the data center id is already submitted via the AITPS for that investment in the data center inventory field (which is required and limited to 1 value for a infrastructure type 5/datacenter investment)

**Comment by rydougherty** [comment]
Thanks Austin, we will remove the node on our end for SIR submissions.

**Comment by GihaVillazon** [comment]
Thank you Austin and Ryan. I will be closing this ticket now.

**Comment by rbrown94** [comment]
OMB has made two things very clear.  The Data Center and Cloud SIR should have at most one Data Center ID however the any investment can be associated with multiple Data Center IDs.  I agree it causes problems but the guidance is clear on both parts.  In speaking with OMB they even explained that one of the main benefits of including the Data Center IDs on the AITIPS is so agencies can associate all of the data centers that are part of an investment.  Perhaps wasn't fully thought through but the guidance has been clear and to my knowledge OMB hasn't communicated out a change.
