### ISSUE TITLE
Project Variance Scores

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#128]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: How will the Project Variance Score Algorithms be impacted by the removal of Projected nodes for Agile Activities?

**Comment by GihaVillazon** [comment]
Hi Ryan,

We checked the code logic and do not anticipate that the algorithms used to calculate Project Variance will be affected by the removal of the Projected node for agile activities for FY19. These algorithms primarily use actual and planned cost/schedule values.

Thank You.
