### ISSUE TITLE
IT Budget 1.9.7 XSD Errors?

### ISSUE THREAD

**Issue by kengineer** [ombegov/ITDB-schema#129]
Hi,

I'm am using .Net for our submissions and have successfully generated classes using the [.Net xsd tool](https://docs.microsoft.com/en-us/dotnet/standard/serialization/xml-schema-def-tool-gen) for the IT Budget xsd files via the code command line version 1.8.1. Below is the command executed.

`xsd .\Exchange\ITBudget-Agency-Report-x.xsd .\Extension\Get-ITBudget-EXT-e.xsd .\Extension\Response-ITBudget-EXT-e.xsd .\Extension\Update-ITBudget-EXT-e.xsd .\Subset\niem\appinfo\2.0\appinfo.xsd .\Subset\niem\iso_639-3\2.0\iso_639-3.xsd .\Subset\niem\niem-core\2.0\niem-core.xsd .\Subset\niem\proxy\xsd\2.0\xsd.xsd .\Subset\niem\structures\2.0\structures.xsd .\Subset\ITBudget-facet.xsd .\Exchange\ITBudget-OMB-Response-x.xsd /c
`

When I do the same for version 1.9.7, I get the following error/warnings that prevents the classes from being generated:
>Schema validation warning: 'update-ITBudget-ext:DataCenterID' is an invalid value for the 'ref' attribute. Line 159, position 34.
Schema validation warning: '**resposne**-ITBudget-ext:CostPools' is an invalid value for the 'ref' attribute. Line 327, position 34.
Schema validation warning: 'update-ITBudget-ext:ITTower' is an invalid value for the 'ref' attribute. Line 350, position 34.
Schema validation warning: 'niem-core:TextType' is an invalid value for the 'type' attribute. Line 539, position 38.
Schema validation warning: '**reponse**-ITBudget-ext:ITTowersType' is an invalid value for the 'type' attribute. Line 679, position 34. 

In some cases it looks like the word "response" was misspelled in the xsd, which is causing the problem. I went and fixed the misspellings in Response-ITBudget-EXT-e.xsd and that eliminated two of the warnings. I also changed niem-core:TextType to nc:TextType which fixed another one (whether this is the right thing to do, I'm not sure). So right now I'm left with the following two warnings. Any insight how to fix these would be appreciated.

>Schema validation warning: 'update-ITBudget-ext:DataCenterID' is an invalid value for the 'ref' attribute. Line 159, position 34.
Schema validation warning: 'update-ITBudget-ext:ITTower' is an invalid value for the 'ref' attribute. Line 350, position 34.

I've attached the file I updated for reference.
[Response-ITBudget-EXT-e.zip](https://github.com/ombegov/ITDB-schema/files/1250025/Response-ITBudget-EXT-e.zip)

**Comment by GihaVillazon** [comment]
Hi, 

To avoid the below errors. Please change the "update" to "response". Let us know should you continue to see further issues. 

Schema validation warning: '**update**-ITBudget-ext:DataCenterID' is an invalid value for the 'ref' attribute. Line 159, position 34.
Schema validation warning: '**update**-ITBudget-ext:ITTower' is an invalid value for the 'ref' attribute. Line 350, position 34.

Thank You.

**Comment by kengineer** [comment]
That fixed it - Thanks!

Is this something that will be changed in a later release?

**Comment by GihaVillazon** [comment]
Great, NP.

This does not seem to be our code concern, what would you suggest? 

Thank You.

**Comment by kengineer** [comment]
Fair enough. I thought the alternate spellings of "response" and the other issues identified were something that might affect others. But if the .Net XSD tool is the only tool that has a problem with it, and it would be incorrect to make that change outlined above, then no need to make a change I guess.

**Comment by GihaVillazon** [comment]
Thank you I will be closing this ticket now.
