### ISSUE TITLE
Prior UII For New Investments

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#130]
We are receiving an error on AITPS validation of new investments with Prior Year UIIs stating the following: Error: The provided CurrentUII 010-000002181 cannot change from last year's value of 010-000000326,010-000000331 if the Change in Status Identifier is not a split, consolidation or reorganization.

It was previously communicated that this error would be removed to allow for Agencies to submit based on the scenarios outlined by OMB. This investment has a new UII, and contains pieces of multiple existing investments.

I can send the investment IT Portfolio file is necessary.

**Comment by rydougherty** [comment]
Following up here- this is related to the comment I posted a couple of hours ago in Issue 110.

**Comment by GihaVillazon** [comment]
We have a fix deploying with 08B Hotfix.

Thank You.
