### ISSUE TITLE
 IT Budget API Version

### ISSUE THREAD

**Issue by seanball** [ombegov/ITDB-schema#132]
Name: Sean Ball 
Organization: Nuclear Regulatory Commission 
Urgency: High
Description of Issue: 

Can you confirm which version of the IT Budget API we’re expected to use for the submission in September? The latest version on the github site is 1.9.7. However, when I test a sample XML request against the myuat site, I get XML schema validation errors for version 1.9.x. When I use version 1.8.1, I don’t get these errors (I do get data validation errors, but that is to be expected since I’m not submitting real data).

**Comment by ojedanico** [comment]
For FY19 Testing
IT Budget API	
https://myuat.itdashboard.gov/api/v1/itbudget?apikey=xxxx

Business Case API	
https://myuat.itdashboard.gov/api/v1/businesscase?apikey=xxxx

SIR API	
https://myuat.itdashboard.gov/api/v1/investmentreport?apikey=xxxx

CIO Rating API
https://myuat.itdashboard.gov/api/v1/ciorating?apikey=xxxx

Manual Upload	
https://myuat.itdashboard.gov/drupal/data/submissions/xml-upload

**Comment by seanball** [comment]
I get XML schema validation errors for version 1.9.x. When I use version 1.8.1, I don’t get these errors (I do get data validation errors. We should be using version 1.9.x for the test sites?

**Comment by ojedanico** [comment]
yes v1.9.8

**Comment by SriramAvasarala** [comment]
Nico,

I don't see Standard Investment Report and CIO Rating Evaluations options on https://myuat.itdashboard.gov/drupal/data/submissions/xml-upload and it has only IT Budget and Business Case options. 

This url https://myuat-2019.itdashboard.gov/drupal/data/submissions/xml-upload has all 4 options. 
IT Budget , Business Case, Standard Investment Report and CIO Rating Evaluations. Which one we should use?

Thanks,
Sriram

**Comment by ojedanico** [comment]
You should be using the following url for standard investment reports 
SIR API
https://myuat.itdashboard.gov/api/v1/investmentreport?apikey=xxxx

and 

CIO Rating API
https://myuat.itdashboard.gov/api/v1/ciorating?apikey=xxxx

Submission urls will not be open until Sept 5th.
