### ISSUE TITLE
IT Security and Compliance Cost Tower tag - optional or required

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#133]
Name: Sriram Avasarala
 Organization: Treasury
 Urgency: Medium
 Description of Issue:

I have the following questions about Total IT Security and Compliance Cost Tower in IT Portfolio. Please confirm. If you are planning to change any of these validations in the upcoming build please let us know.
1.Is it required for every investment (Part 1/Part2/Part3) or is it required only for Part 3 Type 02 - IT Security and Compliance investment?
2.If it is not required for Part 1 and Part 2 , should we omit the node (or) should we send the tower node with 0 values.

**Comment by TsitsiL** [comment]
Hi Sriram,
all investments that are not type 04 must include the Total IT Security and Compliance Cost tower. I don't see any tickets that will change this logic.

I will close this ticket and reopen it if you have any follow up questions.

Thanks!
