### ISSUE TITLE
Security Investment No Warnings Server Error

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#139]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: I am receiving a server error when submitting a Security SIR the Dashboard, if there are no errors or warnings. I am able to successfully submit with warnings in the file.

**Comment by ojedanico** [comment]
Is there any error message in the response?

**Comment by ojedanico** [comment]
looking into the messages will get back to you shortly.

**Comment by ojedanico** [comment]
Jira ticket 883 to be deployed with 9a release

**Comment by TsitsiL** [comment]
ITD-883 deployed on 9/6/17. Closing this issue.
