### ISSUE TITLE
Warnings in SIR Files 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#140]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: We are only receiving warnings in the the bottom half of an SIR response file. Warnings should get returned in both halves. I will email over reference files soon.

**Comment by GihaVillazon** [comment]
Hi Ryan,

We are having the fix deployed with 08B hotfix 2.

Thank You.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

Let us know if you are still experiencing this issue.

Thank You.

**Comment by GihaVillazon** [comment]
I will be closing this ticket. 

Thank You.
