### ISSUE TITLE
5 Decimals Returned for SIR Cost Values

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#141]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: In the response files we only see 5 decimals returned for SIR Cost Values, even when 6 decimal values were submitted on our end. I will email over reference files soon.

**Comment by GihaVillazon** [comment]
We have added the fix and will be deployed with 09A.

Thank You.

**Comment by ojedanico** [comment]
Yes, we are aware of this issue and currently updating the code and is for hotfix2

**Comment by rydougherty** [comment]
Hi Nico- we are actually still seeing this issue with the Data Center Cost Details Table. I will email over reference files shortly. That said, given our ability to work around this issue, I would not place this item as higher priority than the items currently queued up for tonight and Friday.

**Comment by ojedanico** [comment]
This issue was resolved with Jira ticket 869 scheduled for 10B release on 10/23.
