### ISSUE TITLE
Security SIR Server Error Received When Cost Nodes Are Blank

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#142]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: I am receiving a server error from the dashboard when I submit an Add request through the Security SIR Annual operation for a capability that is missing a value in one of the cost nodes (PY, CY, BY). I realize values are required for these, but I believe this should return a validation error from the dashboard, not a server error. I am including the node as required in the schema, but it is blank. I will send the request file that is returning the error to the ITDB support mailbox.

**Comment by GihaVillazon** [comment]
Hi Alex, 

we are looking into this, will keep you posted. 

Thank You.

**Comment by GihaVillazon** [comment]
Hi Alex, 

Are you still experiencing the issue?

Thank You.

**Comment by murrayalex** [comment]
No, I am not seeing that error anymore. This can be closed out.

**Comment by GihaVillazon** [comment]
Great! Thank you.
