### ISSUE TITLE
Lag in Assigning OMB IDs through SIR

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#145]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: Following a SIR request which adds projects/contract/metrics etc, it appears the IT Dashboard is returning a response file before all OMB IDs have been properly assigned. I recently submitted an add operation of an End User SIR. The submissions was successful, but 4 Metric Actuals did not receive metricActualIDs in the response. All other new projects, contracts, and metrics received OMB IDs.

This is problematic, because it prevents our tool from back populating these identifiers to the Actual that was submitted.   

The IT Dashboard, should not return a response file until all OMB IDs have been assigned out. I will email over example files soon.

**Comment by GihaVillazon** [comment]
Hi Ryan,

We have opened a ticket to address this issue in the near future release. 
#875

Thank You.

**Comment by rydougherty** [comment]
Hi Giha, can you please give further insight into what you mean by future release? This is a critical must-have for a functioning SIR submission. If there are no OMB IDs returned in the response file, we will be unable to parse the file.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

We are in midst of figuring out the fastest method to have the fix ready. 

Thank You.

**Comment by TsitsiL** [comment]
ITD-875 was deployed on 9/1/17. Closing this issue.
