### ISSUE TITLE
UAT Data Refreshes

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#147]
As we discussed on the phone, can you let me know the last time the data was refreshed in UAT?  I'm sending you over some files where we're getting errors regarding structure IDs already being in use, but the activities they are in use for were deactivated.  I double checked to make sure the response file wasn't returning deactivated activities, etc., and it doesn't appear to be.

This is a low/medium issue.  Mostly the concern is that if there isn't going to be another update, then, really, the next chance we'll have to validate investments won't be until 11th when they can be validated in Production.

Thanks!!

**Comment by GihaVillazon** [comment]
Hi Courtney,

The last data refresh was on 8/21 with 08B deployment. 
Would it help to have a weekly scheduled refresh?

Thank You.

**Comment by courtneycorwin** [comment]
I think some of the activities were deactivated before 8/21, I will follow up on that.  But no, a weekly update is not necessary.  One more refresh before the 5th would be great for accurate testing, but if it doesn't happen, it's fine.  It's not the first time we've had to wait until submission week to do final validation.  I just need to know either way so I can set some expectations.

Thanks!!

**Comment by GihaVillazon** [comment]
With the 09A deployment there will be refresh.

Thank You

**Comment by courtneycorwin** [comment]
Great! Thanks!

**Comment by GihaVillazon** [comment]
No Problem, I will close this ticket now.

**Comment by courtneycorwin** [comment]
I think this got reopened in today's meeting.
