### ISSUE TITLE
Performance Metrics - CY Target

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#148]
It looks like the PY and CY targets for performance metrics are still set to 2016 and 2017 respectively.  Because of this, we are seeing the following validation error ""....Once a CY target has been provided for a metric, it cannot be updated without using a revise operation"

Can you look into this, please.  I'm happy to send you files if needed.

Thanks!
Courtney

**Comment by GihaVillazon** [comment]
Hi Courtney, 

Please send the submission files or provide the time of submission. 

Thank You.

**Comment by courtneycorwin** [comment]
Ran at 9:36/9:37 am today by FAA.

**Comment by GihaVillazon** [comment]
Hi Courtney, 

Sent you an en email, also please send your submission files.

Thank You.

**Comment by courtneycorwin** [comment]
I responded at about 1:30 with the submission files.   Thanks for taking a look for us - basically, all of the cytarget tags should be currently blank, but we're seeing them all as populated.

**Comment by GihaVillazon** [comment]
Hi Courtney, 

Investments which are continuing will require "revise operation" as the metrics were originally captured with the initial submission of business case. When the investment is new the error will not present itself, only for the continuing investments with business case.

Thank You.

**Comment by courtneycorwin** [comment]
The validation is, and always has been, that the rebaseline isn't required until the CYTarget has been submitted for the first time.  In this case, the 2018 CY Target has not been submitted for any of the investments we've tested.  The existing CY Target is moved to PY and the CY Target is blank.

Under your rule, all continuing investments would need to be rebaselined in order to send a value they haven't sent before (2018 CY Target).  I'm fine with this, but none of my users will be and it's a change from past years - so please be very sure before I take this news back.

**Comment by GihaVillazon** [comment]
Hi Courtney, 

After few clarification, you are correct CY value should be blank and will only need revise operation once they are submitted during the submission period. Therefore I have opened a jira ticket to have the fix in place. 
#895.

Thank You, and I appreciate the knowledge transfer form last year.

**Comment by courtneycorwin** [comment]
I appreciate you looking into it!  Enjoy your holiday weekend!

**Comment by TsitsiL** [comment]
JIRA ticket ITD-895 was completed and deployed on 9/6/17. Closing this ticket.
