### ISSUE TITLE
IP Ranges for IT Dashboard

### ISSUE THREAD

**Issue by alex-unger** [ombegov/ITDB-schema#150]
Name: Alex Unger
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue:
In an email on February 7, 2017 Paul Donohue of OMB distributed a list of IP ranges where the IT Dashboard is hosted so that firewall rules can be configured appropriately based on the IT Dashboard moving servers.  Below are the ranges that Paul had sent out.  Can you please verify if these are still correct, or if they’ve been changed, provide the new ranges?

Please update your rules to allow the following ranges:
204.68.207.0/24 (expanded from a /26 to a /24)
198.137.240.0/23 (expanded from two /26s to a /23)
12.183.70.192/26 (unchanged)
2620:010f:b000::/40 (expanded from five /64s to a /40)

**Comment by GihaVillazon** [comment]
Hi Alex, 

We no longer use 204.68.207.0/24 - that can be removed from the list.
Otherwise, still correct.

Thank you.

**Comment by GihaVillazon** [comment]
I will be closing this ticket now. If you have further questions or concerns we can reopen this ticket, or create a new one. 

Thank You.

**Comment by alex-unger** [comment]
Thanks Giha!
