### ISSUE TITLE
Update Costs and Capabilities Server Error

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#151]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High/Critical
Description of Issue: We are receiving a server error while performing an update submission for the Costs and Capabilities Table. It appears this server error is related to the string of Agency ID Server Errors discussed in Issue 111. This is critical as it will prevent Agencies from submitting updates to the only required SIR data.

Request:
```
<?xml version="1.0" encoding="UTF-8"?>
<towers validateOnlyIndicator="true">
  <tower>
    <operation>update</operation>
    <towerDetails>
      <UII>011-000100061</UII>
    </towerDetails>
    <costsAndCapabilities>
      <costAndCapability>
        <operation>update</operation>
        <capabilityID>2737</capabilityID>
        <purposeOrOutcome>This is a test. This is an update</purposeOrOutcome>
        <CY>0.049</CY>
      </costAndCapability>
      <costAndCapability>
        <operation>update</operation>
        <capabilityID>2738</capabilityID>
        <purposeOrOutcome>No Phising here. Update test</purposeOrOutcome>
        <CY>0.05</CY>
      </costAndCapability>
    </costsAndCapabilities>
  </tower>
</towers>
```

Response:
{"ok":false,"error":true,"metadata":null,"httpStatusCode":500,"httpStatusMessage":"Internal Server Error","responseTime":0.6312689781189,"result":null,"errors":[{"code":8,"message":"Undefined index: agencyCapabilityID","severity":0,"file":"\/services\/sEgvHttpP\/server\/19\/htdocs\/api\/Pittsburgh\/Controllers\/ITDB2\/InvestmentReport\/validations\/IRCostAndCapabilityValidator.php","line":134}]}

**Comment by GihaVillazon** [comment]
Hi Ryan,

The issue has been noted and will be fixed in the 9A deployment. A workaround in the mean time is to not omit the agencyCapabilityId, even if the element remains empty. Please confirm you are able to proceed with the mentioned workaround.

Thank You.

**Comment by rydougherty** [comment]
Hi Giha- the workaround is valid through postman. However, it still prevents us from accessing and testing portions of your code and our code through our tool.

We would appreciate if there is anything you can do on your end to have the issue resolved before 9A. This issue was initially slated for resolution in 8b, and is preventing us from testing Security investments.

**Comment by TsitsiL** [comment]
ITD-844 was completed and deployed on 9/6/2017. Closing this issue.
