### ISSUE TITLE
Network SIR Project Output

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#153]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: We are receiving a validation error on the Output field within the Network Projects Table. It is stating that the only valid responses for this field are {1, 2, 3, 4}. I don't see any reference to this in the guidance, and it does not line up with the latest dictionary (that document provides '25' as an example response). Can you provide more information here please?
[20170901_133455179990_608_200.txt](https://github.com/ombegov/ITDB-schema/files/1271055/20170901_133455179990_608_200.txt)

**Comment by GihaVillazon** [comment]
Hi Alex, 

Would you please post the error message you are receiving.

Thank You.

**Comment by murrayalex** [comment]
`<error>Field output with value 5 is not valid. Valid codes are: (1, 2, 3, 4)</error>`

**Comment by GihaVillazon** [comment]
Yes, we noticed this error, and the fix will be deployed with 09A
#890.

Thank You.

**Comment by murrayalex** [comment]
Thanks, Giha. What is the fix exactly? To allow any integer?

**Comment by GihaVillazon** [comment]
With the fix Yes, the field will allow integer values.

Thank You.

**Comment by TsitsiL** [comment]
ITD-890 deployed on 9/6/17. Closing this issue.
