### ISSUE TITLE
SIR Get Response Missing Actual Results

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#154]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The SIR Get File response is not returning Performance Metric Actuals that were successfully submitted to the IT Dashboard. We are receiving a successful confirmation of these Actual Results in the initial response file. However they never appear in the Get File response.  

I will email over three reference files soon.

**Comment by GihaVillazon** [comment]
Hi Ryan,

We will have the fix in place with 09A Release. 
#892.

Thank You.
