### ISSUE TITLE
OMB Control Numbers Not Included In investmentResponse.xsd

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#155]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: The investmentResponse schema does not include the OMB Control Numbers node. We use this file as our template for comparing data internally. We can manually update this now to mitigate issues we are seeing, but can this please be updated in the future? The following node is missing from Investment Details: <element ref="businessCase-update:ombControlNumbers" minOccurs="0"/>

**Comment by GihaVillazon** [comment]
Hi Alex, 

We have noted the issue, and will have the fix in place. 
#899.

Thank You.

**Comment by murrayalex** [comment]
Thanks, Giha.

**Comment by TsitsiL** [comment]
ITD-899 deployed on 9/8/17. Closing this issue.
