### ISSUE TITLE
Contract Dates Returned in Odd Format

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#156]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: The Get File Response is sending back date values in the Day + Time format. We are submitting dates in the mm/dd/yyyy format. We would expect values to be returned in the same format as our submissions.

Request Node Format: `<anticipatedAwardDate>08/19/2017</anticipatedAwardDate>`

Get File Response Format: `<anticipatedAwardDate>2017-08-19 00:00:00</anticipatedAwardDate>`

**Comment by ojedanico** [comment]
Based on the time constraint and the time it would take for us to fix on our end would it be possible for you guy to parse the date?

**Comment by rydougherty** [comment]
Hi Nico, we are happy to postpone this work in order to hit more pressing issues.

**Comment by jeremiah-tcg** [comment]
This issue will be overcome by events due to the changes in the FY20 guidance (re: Contracts Report).
