### ISSUE TITLE
IT Portfolio Data Feed is giving error

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#159]
Name: Sriram Avasarala
Organization: Treasury
Urgency: High
Description of Issue: IT Portfolio Data Feed is giving error. 

We were able to validate and submit the IT Portfolio successfully this morning on UAT site and when we try to download data feed the page displays http 500 internal server error. 

Url: https://myuat-2019.itdashboard.gov/drupal/data/datafeeds?format=csv

https://myuat-2019.itdashboard.gov/api/v1/ITDB2/dataFeeds/portfolio/agencyCode/015?csv=true

**Comment by GihaVillazon** [comment]
Hi Sriram,

Yes we see the 500 Error, We have added the fix with 09A hotfix deployment.

Thank You.

**Comment by SriramAvasarala** [comment]
The ITP data feed is working now, please close this ticket.

**Comment by TsitsiL** [comment]
Thanks Sriram!
