### ISSUE TITLE
BY19 Schema Questions

### ISSUE THREAD

**Issue by TsitsiL** [ombegov/ITDB-schema#16]
Name: Sriram Avasarala
Organization: Treasury
Urgency: High
Description of Issue:
Hi,
 
We have following questions regarding draftBY19 schema. Can you please review them and provide the response?
 
A.      IT Towers: Fields 56 to 85 (part 1 and part 2 investments) These fields are optional and required based on various validations. Our question is whether we need to include them in XML with zeros or not when they are optional.
 
1. Does OMB expect us to submit XML with all IT tower categories? For example : If I have an investment that has only Data Center Cost, how do we submit the data  Option A or Option B
A) Total Data Center Cost PY, Total Data Center CY and Total Data Center BY with values and rest of the IT Towers with zero values.
B) Total Data Center Cost PY, Total Data Center CY and Total Data Center BY with values and no need to submit the rest of the IT Towers with zero values
 
2. How do we submit the updates to IT towers? Does it work similar to Funding Source Line Items? For example : If we submit with Data Center Cost IT Tower in September 2017 and if we want to replace Data Center Cost with Compute Cost IT Tower, how do we submit the data in Jan 2018
        A) Total Data Center Cost PY, Total Data Center CY and Total Data Center BY with zero values and Total Compute Cost PY, CY and BY values
        B) Total Compute Cost PY, CY and BY values and no need to include Data Center Cost with Zero values
 
B.       Valid submission : Can you please validate the following Part , Type and Standard Investment combination and let us if this combination (IT Portfolio) is allowed to be submitted or not? Can we submit the optional business case for this IT Portfolio combination?
 
|Part of the IT Portfolio   | Investment Type                                                   | Standard Investments|
|--------------------------|------------------------------------------------------|-------------------------|
|Part 3                                |  6 - Non-Standard  Infrastructure Investments      |  Network|
|Part 3                                |  6 - Non-Standard Infrastructure Investments       |  Data Center and Cloud|
|Part 3                                |  6 - Non-Standard Infrastructure Investments        |  End User|
 
C.       As per the baseline validations (BY19 CPIC Validations List.xlsx.pdf) released last week, the following combination is invalid and not allowed to submit the Business Case, Investment Report and CIO Rating. If we have a Part 3 security investment with projects and metrics, what options should we choose on IT Portfolio so that the Business Case and CIO Rating report submission are allowed.
 
|Part of the IT Portfolio     | Investment Type                                                    | Standard Investments| Status |
|--------------------------|----------------------------------------------------------------|-----------------|-----|
|Part 3               | 1 - Major |IT Security & Compliance                                                   | Invalid            |
|Part 3               | 5 - Standard Infrastructure Investments |IT Security & Compliance   |  Not Allowed  |
 
 
Thanks,
 
Sriram Avasarala
IT Specialist
Digital Services
Enterprise Business Solutions         
Office of the Chief Information Officer      
U.S. Department of Treasury                      
Customer Support: 202-622-5555
Office: 202-622-6643
Mobile: 202-486-2610
Submit a WebTrack Ticket

**Comment by SriramAvasarala** [comment]
Do you have any update?

**Comment by ojedanico** [comment]
Please review the follow for answers to your questions. If you need further verification please provide comment to this chain. 

Overall answer is, optional Fields do not require data, therefore they can be left blank. 

A1) Following this logic, the answer would be example B that was provided. 
A2) Following this logic, the answer would be example B that was provided. 

Answer for B:
Part 1: IT Investments for Mission Delivery 
Part 2: IT Investments for Administrative Services and Support Systems 
Part 3: IT Investments for IT Infrastructure, IT Security, and IT Management 
**Types of Investment**
1.     Major investment REQUIRES business case  - Part 1 and 2 includes investments types 1-4
2.     Non-major – Business case not possible
3.     IT migration investment, – Business case not possible 
4.     Funding Transfer Investments, – Business case not possible
5.     Standard IT Infrastructure Investments, Part 3 – Business case not possible 
           -  IT Infrastructure,
           -  IT Security, 
           -  IT Management Investments 
                §  Not Applicable 
                §  IT Security and Compliance, 
                §  IT Management, 
                §  Network, 
                §  End User, 
                §  Data Center and Cloud
6.      Non-Standard Infrastructure Investments, Part  - 3  Business case is optional 

Answer for C:
Part 3: IT Investments for IT Infrastructure, IT Security, and IT Management, includes investment type 5 and 6 (see answer B above), 
CIO Evaluation Rating is not required for part 3 but is optional 
Investment type 5 business case is not required 
Investment type 6 business case is optional
