### ISSUE TITLE
SIR Submission Order

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#160]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: We have been receiving errors back for having certain nodes out of order within SIR Update Submissions. For example, placing Cost Details after Metrics triggers the following error:

> Error 1871: Element 'investmentCostDetails': This element is not expected. on line 1

Can you please confirm the following order of submissions for SIR sections:

Investment Details
Cost Details
Contracts
Projects
Metrics

**Comment by ojedanico** [comment]
Yes this is the correct - let me know if you receive the error using this order and we will look into it further.

**Comment by rydougherty** [comment]
Hi Nico- we can still generate the error. But, we will sort the submission files on our end to avoid this error.

**Comment by ojedanico** [comment]
Ok cool thanks!
