### ISSUE TITLE
SIR Submission issue (Security and Complaince report)

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#161]
Name: Sriram Avasarala
 Organization: Treasury
 Urgency: High
 Description of Issue: SIR Submission issue (Security and Compliance report).

We are getting following errors while validating SIR (Security and Compliance Report) using manual upload. 
Submission Failed
CriticalErrors ◦alertThe operation addSecurity is not available at this time.

Submission Failed
CriticalErrors ◦alertThe operation updateSecurity is not available at this time.

**Comment by murrayalex** [comment]
Echoing Sriram, we are seeing this with all of the add operations for the standard reports.

**Comment by GihaVillazon** [comment]
Hi, 

We are looking into this, will keep the community posted. 

Thank You.

**Comment by murrayalex** [comment]
The operation appears to be working again.

**Comment by GihaVillazon** [comment]
Great! thank you.

**Comment by SriramAvasarala** [comment]
Giha, Its working now. Did you fix anything on your end?

**Comment by GihaVillazon** [comment]
Yes, we edited the date to open up the operations window. 

Thank You.
