### ISSUE TITLE
IT Security Error when submitting ITPS

### ISSUE THREAD

**Issue by Schmidttm2** [ombegov/ITDB-schema#162]
Below is the error we are receiving when submitting our ITPS to myit-2019.itdashboard.gov site. I have included the error and the part of the input file for the specific investment that meets the IT Security & Compliance reporting.

I have also included my ITPS XML, input and response files.

Response file:

Error: At least one investment must exist with Standard IT Infrastructure and Management Category = '02' and the sum of Total IT Security and Compliance Cost for CY and BY greater than 0.

Input /request file data

<UniqueInvestmentID>
<CurrentUII>014-000000048</CurrentUII>
<PriorUII>014-000000048</PriorUII>
<InvestmentLineStructure>00</InvestmentLineStructure>
<SharedServicesCategory>00</SharedServicesCategory>
</UniqueInvestmentID>
<InvestmentCharacterization>
<InvestmentTitle>Security/Cyber Security Services</InvestmentTitle>
<InvestmentDescription>
Provides operational security support to State Department IT assets and infrastructure. This includes encryption, secure voice and data communications, user privacy and security training.
</InvestmentDescription>
<BureauCode>00</BureauCode>
<PartofITPortfolio>03</PartofITPortfolio>
<InfrastructureManagementCategory>02</InfrastructureManagementCategory>
<MissionArea>09</MissionArea>
<TypeofInvestment>05</TypeofInvestment>
<NationalSecuritySystemsIdentifier>01</NationalSecuritySystemsIdentifier>
<FEAPrimaryBRMService>121</FEAPrimaryBRMService>
</InvestmentCharacterization>
<InvestmentStatusChange>
<StatusIdentifier>11</StatusIdentifier>

**Comment by TsitsiL** [comment]
Closing this issue as it was already reported via Help Desk where it being addressed.
