### ISSUE TITLE
Business Case submission issue

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#163]
Name: Sriram Avasarala
Organization: Treasury
Urgency: High
Description of Issue: Business Case submission issue. 

We are getting following validation errors for acquisition Strategy, Existing Contracts fields while validating Business Case using manual upload. As per the schema these fields are optional and also the xml was validated successfully yesterday and we are getting errors today.  
 
Investment 015-0000000XX: operations failed
◦updateInvestment: 
alertThe investment must have the following elements. Please, resubmit with updates that include Acquisition Strategy, Existing Contracts.

Investment 015-0000000XX: operations failed◦updateInvestment: 
◾alertThe investment must have the following element. Please, resubmit with updates that include Acquisition Strategy.
◾warningContract with agency identifier '124549': Please check back tomorrow to see USA Spending API result.

**Comment by SriramAvasarala** [comment]
I sent the xml and error output to the dashboardsupport email at 11.34 am.

**Comment by barrypannell** [comment]
Ditto for our DHS testing.  The file tested fine in previous days but today it is getting the errors above.

**Comment by barrypannell** [comment]
It is not in all investments submitted.  There was another error on the 2 cases we saw this error.  There was an error with a goal/objective for the investment and an error with an eliminated investment for the other.

**Comment by ojedanico** [comment]
I looked at the FY19 guidance and confirmed that Major IT Business Case section D (Acquisition/Contract strategy) is required:

•	For major Investments designated as IT Security and Compliance Standard Investments (code “02” in Column 7 of the IT Investment Portfolio Summary), complete Major IT Business Case Section D and F only. 
•	For major Investments not designated as an IT Security and Compliance Standard Investment (codes “01” or “03” in Column 7 of the IT Investment Portfolio Summary), complete both the Major IT Business Case Sections A through D and Major IT Business Case Details sections A through C. 
•	For Investments designated as Administrative Services and Support Systems Investments (code “02” in Column 6 of the IT Investment Portfolio Summary) complete both the Major IT Business Case Sections A-E and Major IT Business Case Details sections A-C (see MAJOR IT BUSINESS CASE table on page 3).

These fields are required for a first-time submission each budget year.  With 09A release we made sure those validations are in place.

**Comment by TsitsiL** [comment]
Closing this ticket as per my findings that were posted by Nico in the last comment.  These sections are required for the the first annual submission. The investments with errors in the input file sent by Sriram were missing these required sections. Please us know if you have any other questions, thanks!

**Comment by SriramAvasarala** [comment]
Tsitsi, please keep this ticket open. OMB agreed to investigate further and provide the response.

**Comment by ojedanico** [comment]
I just reopened it so we can discuss further

**Comment by SriramAvasarala** [comment]
Nico, I discussed this issue with our CPIC team and they confirmed that we have major investments that they don't have any contracts (both Awarded and Planned Acquisitions). These validations were not there in FY18 submissions and with these new validations we cannot submit the business cases without acquisitions. Please let us know how do we handle this scenario.

**Comment by SriramAvasarala** [comment]
Nico,  The IT Security and Compliance Standard Investment Reports don't have to fill Business Case Sections D and F . These instructions seems like FY18 instructions and we have a SIR for security and compliance. 
------
• For major Investments designated as IT Security and Compliance Standard Investments (code “02” in Column 7 of the IT Investment Portfolio Summary), complete Major IT Business Case Section D and F only.
• For major Investments not designated as an IT Security and Compliance Standard Investment (codes “01” or “03” in Column 7 of the IT Investment Portfolio Summary), complete both the Major IT Business Case Sections A through D and Major IT Business Case Details sections A through C.
• For Investments designated as Administrative Services and Support Systems Investments (code “02” in Column 6 of the IT Investment Portfolio Summary) complete both the Major IT Business Case Sections A-E and Major IT Business Case Details sections A-C (see MAJOR IT BUSINESS CASE table on page 3).
------------

**Comment by barrypannell** [comment]
Based on the previous year submission guidance DHS would submit the annual submission XML that included the updateinvestment section and within it the overview and lifecycle costs so that the required fields defined below were included.     
 
For the first September Business Case submission of each continuing major investment, the tags from the updateInvestment operation listed below will be required. Once provided, these tags will remain optional (per the schema) for subsequent updateInvestment submissions.
capitalAssetSummary
-investmentDetails
-investmentStartEndDates
- investmentStartYear
- investmentEndYear
investmentDetails
-investmentDescription
-objectivesOrGoals
-returnOnInvestmentDescription
-investmentRequirements
-programCodeFPI
-investmentSharedService
-investmentPivEnabled
-pmDetials


Following that submission, a monthly submission file would be submitted that included any project, contract, operational performance and risk information updates including any new fields.  

Technically, if the investment updated to ITD on Aug 31, there may not be any changes to projects, contracts, risks, performance measures (other than the new target).

**Comment by ThomasMilligan** [comment]
This validation needs to be removed and discussed with the community before implementation.

1.	Our Testing has shown the Validation willonly allow submission when a major investment has at least one update to an existing acquisition AND at least one update to a pending acquisition.
     a.	 The Validation is assuming that all major investments have at least one existing acquisition and one pending acquisition 
     b. As implemented, investments without acquisitions and those without one of the two classes will be forced to upload dummy acquisition data to pass Validation.
     c.	 An investment not reporting all acquisition data is a data quality issue and not a validation issue.

2.	While the Guidance has been published, this revised Validation is new for the BY19 submission and has not been communicated to Agencies. As the Submission deadline is pending, now is not the time to make changes to the business process.

**Comment by courtneycorwin** [comment]
I've just had a similar issue reported to me.  In this case, the error is "The investment must have the following element. Please, resubmit with updates that include Acquisition Strategy." and it's the only error returned on validation.

I can get you some more information inf you need it, but in at least one case, the error is returned for a continuing investment that didn't have Acquisition entries last year either.

For what it's worth, the investments in question passed validation prior to the hotfix update.

**Comment by ojedanico** [comment]
Thanks, we are looking into now. And will provide an update shortly.

**Comment by ojedanico** [comment]
From what I am gathering from everyone is the Acquisition Strategy is what is causing the issue?

**Comment by ThomasMilligan** [comment]
Yes.

**Comment by courtneycorwin** [comment]
For me as well, thanks!

**Comment by barrypannell** [comment]
The error message also includes a reference to CIO Rating.  Which also was 'not required' previously on continuing investments initial update.  And of source is moving to a separate update.

**Comment by barrypannell** [comment]
If you review the UAT and the submission trial # 868880 you will see an annual submission/ investment update for 11 continuing investments.  10 of the 11 update successfully.  Only 1 rejects with the error discussed and another error condition.   None of the updates include any contract updates or CIO rating.  That was the inconsistency I was surprised about.

**Comment by barrypannell** [comment]
My recommendation/request on this item is to relax validation so that on the initial submission of a continuing investment the sections that are required are the overview and lifecycle costs sections.  Other sections on continuing investments like planned or awarded contracts, CIO Ratings would not be required.

**Comment by SriramAvasarala** [comment]
I agree with DHS recommendation. Please let us know if you have any update on this issue.

**Comment by ThomasMilligan** [comment]
I also support the DHS recommendation.

**Comment by GihaVillazon** [comment]
As Requested by the vendors we are proceeding to relax these validation and will be deployed with 09A Hotfix 1. 
#917
Thank You.

**Comment by SriramAvasarala** [comment]
Thanks Giha.

**Comment by barrypannell** [comment]
Thanks.

**Comment by courtneycorwin** [comment]
Thanks!!

**Comment by SriramAvasarala** [comment]
This issue is resolved, you can close this ticket. Thanks.

**Comment by bill-gehrke-hhs** [comment]
This issue does not appear to be resolved with respect to systems inventory.  As of this morning, I continue to receive the following message for Part 2 investments that either omit "businessCase-update:systemsInventory" or provide that field but leave it blank:

The investment must have the following element. Please, resubmit with updates that include Systems Inventory.

**Comment by TsitsiL** [comment]
Hi Bill, this if from FY19 guidance about providing Systems Inventory:

For Investments designated as Part 2 - Administrative Services and Support Systems in column 6 (by
entering code “02”) of the IT Investment Portfolio Summary, provide a list of systems included in this
Investment.

This validation was introduced and implemented last year and is continuing this year.

**Comment by bill-gehrke-hhs** [comment]
This validation was not in place last year, as we had two Part 2 investments for FY2018 submit with no systems which were submitted successfully.  I just reviewed the XML files we submitted in October and April, and also pulled the data from the IT dashboard using "getInvestment" to confirm that no systems were submitted for those investments and the dashboard has no systems attached to them.

The guidance cited above is the same as from last year, so we did not expect any change in the requirements, and it may be possible that a "list of systems" could be a list of zero if, perhaps, the investment has no operationsl systems or provides only services.

I am also atempting to determine whether the investments for FY2019 with no systems should have them, but in any case, we were expecting to continue to have the ability we had in FY2018 to submit no systems.

**Comment by barrypannell** [comment]
I agree with Bill.  Last year the system/application data was not sent with the annual submission update investment initial file which only included the overview, lifecycle costs and OA data.  The system data was included in a second update file with projects, metrics and risks.  I saw this yesterday afternoon.  Last week when I submitted this error was not stopping the test submission.  I had not thought in my emails about Part 2 investments.   

And I have a related issue - highlighted by this validation - last year DHS added an investment in Part 2 that did not have a system given that it was just starting out.  That investment was accepted as part 2 last year without systems.  The investment still has not put a solution system into the investment.  So at this time I do not have a system to add to the investment.  This validation is stopping the update.

**Comment by courtneycorwin** [comment]
I am also seeing this validation returned for an investment that didn't have systems last year and doesn't have any systems this year - I think, as with Barry's case, they're working on it but don't have it set up yet.  Is it possible to downgrade this to a warning?

**Comment by ojedanico** [comment]
This issue will be resolved with Jira ticket 944 to change this to a warning in release 9a hotfix 4 deployed 9/13

**Comment by barrypannell** [comment]
DHS submitted an investment annual update this morning for the investment at issue and it processed successfully.   Thanks for your attention.
