### ISSUE TITLE
SIR "Is Metric Retired" Response Value 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#164]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The "Is Metric Retired" field is returning values in a "y" or "n" format for the Get File Response. Data is not sent over in that format. This also differs from the format used within the MITBC.

Request: `<isMetricRetired>No</isMetricRetired>`

Get File Response: `<isMetricRetired>n</isMetricRetired> `

**Comment by ojedanico** [comment]
This issue will be resolved with Jira Ticket 915 scheduled for 9a hotfix 1 for 9/8 deployment.

**Comment by TsitsiL** [comment]
ITD-915 deployed on 9/8/17. Closing this issue.
