### ISSUE TITLE
Get File Response does not Return Performance Measurement Category Mapping

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#165]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: In the SIR API, the `<performanceMeasurementCategoryMapping>` node does not return data in the Get Response File.

Request Node:
` <performanceMeasurementCategoryMapping>1</performanceMeasurementCategoryMapping>`

Get File Response: `<performanceMeasurementCategoryMapping/>`

**Comment by GihaVillazon** [comment]
Hi Ryan, 

We will have this fixed with 09A hotfix 1 deployment.
#914

Thank You.
