### ISSUE TITLE
Measurement Condition Capitalization 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#166]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: In the SIR API, the Measurement Condition Field is returning a different capitalization than what is submitted to the IT Dashboard. Notice below how the "T" in target is lowercase in the request, but capitalized in the Get File. The MITBC matches the format we send the the request file.

Request: `<measurementCondition>Over target</measurementCondition>`

Get File Response: `<measurementCondition>Over Target</measurementCondition>`

**Comment by ojedanico** [comment]
This issue will be resolved with Jira Ticket 916 scheduled for 9a hotfix 1 for 9/8 deployment.

**Comment by murrayalex** [comment]
This item can be closed, Nico. Thanks.
