### ISSUE TITLE
Type 04 Investment Security Spending Error

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#167]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: For Type 04 investments, we are receiving the following error, even if the IT Security and Compliance IT Tower values submitted are 0: 
Error: Total PY IT Security Spending must be 0 when investment type is funding contribution.

We are receiving these for CY and BY as well. Please see the attached file that shows our request file and the dashboard response. The Type 04 investment is "Benefits 21st Century Paperless Delivery of Veterans Benefits".

[Type 04 Security Spending Error.txt](https://github.com/ombegov/ITDB-schema/files/1288435/Type.04.Security.Spending.Error.txt)

**Comment by GihaVillazon** [comment]
Hi Alex, 

We were unable to reproduce the error on our end, could please send over your submission file and I will have a developer look into it. 

Thank You.

**Comment by murrayalex** [comment]
I attached it to the original issue. I will send the XML to the ITDB support mailbox.

**Comment by GihaVillazon** [comment]
Yes, I have received the file, we are looking into the root cause of the error.
#917.

Thank You.

**Comment by GihaVillazon** [comment]
Hi Alex, 

The issue is being caused because it seems like you are sending 0.000000 instead of just 0. PHP knows 0, 0.0, and string '0' are empty/false, however string '0.0' etc. are considered true. Therefore Please resubmit with only "0". Certainly let us know if the issue is not resolved. 

Thank You.

**Comment by murrayalex** [comment]
Hey Giha,

Thanks for the response. I'm curious why this error isn't appearing for Internal Labor. We are sending them both the same way, but we aren't returning an error for those nodes. Any particular reason you chose to implement them differently?

**Comment by GihaVillazon** [comment]
Hi Alex, 

The two were not implemented differently on purpose.  When the fix is deployed, this will no longer be an issue.

Thank You.

**Comment by danielwyork** [comment]
What is the fix being deploy for this?

**Comment by GihaVillazon** [comment]
The validation was comparing the provided value of 0.000000 as a string to 0 as a number, and the sting "0.000000" is not the same as the number 0.  The code fix casts the provided value as a float in the comparison logic, so that 0.000000 does equal 0. 

Thank You.

**Comment by TsitsiL** [comment]
ITD-923 deployed on 9/11/17. Closing this issue.
