### ISSUE TITLE
Incorrect Requirement for Financial Performance Metric

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#171]
In testing upload of the annual submission, I received the following error:

If an investment has performance metrics (009-xxxxxxxxx), at least 1 metric should have performanceMetricCategory as "3".

This is not correct, per the CPIC guidance (pg. 58), which requires five metrics including one metric from category 1, three from category 2, and that "The fifth metric, or more as Agencies may report more than five metrics, can come from any category."

This is a high priority issue as it is blocking annual submission for investments that are no longer reporting a financial performance (category 3) metric.

**Comment by TsitsiL** [comment]
Hi Bill,

Your assessment is absolutely correct and we are looking into a fix for this. I will update you when I know when that will be. Thanks!

**Comment by TsitsiL** [comment]
We are working to remove this validation entirely in a hotfix. I will alert you when the hotfix is deployed.
Thanks!

**Comment by dstevenson-tcg** [comment]
Created ITD-928 for this.

*David Stevenson,* Developer
*TCG, Inc. - Positively Distinct* - CMMI-DEV Level 3 - CMMI-SVC Level 2 -
ISO 9001:2015
202-986-5533 Ext. 8448 | david.stevenson@tcg.com | www.tcg.com
<https://www.facebook.com/TCG-32241785903>
<https://twitter.com/TCGnews> [image:
Linkedin] <https://www.linkedin.com/in/davidestevenson>

**Comment by TsitsiL** [comment]
Good morning Bill,

the hotfix was deployed this morning to remove this validation. This should be resolved so I am going ahead and closing this ticket. Please let me know if you have any issues.

Thanks!
