### ISSUE TITLE
SIR Submissions 

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#174]
Submitter: Barry Pannell
Org: DHS/MBC 
Question:  I wanted confirmation that all infrastructure SIRs will initially be 'adds'.  I am certain we discussed this for the security and compliance standard investments.  We also talked about the status change for standard infrastructure investments for the IT Portfolio as 'reorganization'.   I wanted additional confirmation that the initial submission for all data center/cloud/compute, network and end user standard infrastructure investments should be 'add'.   There should be no 'UII' conflict in submitting a fresh SIR for an old infrastructure investment that is continuing.  (The old project, metric, contract slate is 'cleared').

**Comment by GihaVillazon** [comment]
Hi Barry, 

Yes that is correct initial submission for all data center/cloud/compute, network and end user standard infrastructure investments should be 'add'.  Also correct on the UII for the SIRs 

Thank You.
