### ISSUE TITLE
Security SIR Capability Costs Comparison Warning Incorrect Thru Update

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#175]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: When making updates to capability costs within a Security SIR, the validation comparing capability costs to the Security Tower total is incorrectly comparing values. If sending an update to a single cost node (PY for example) and dropping the other two, the validation reads as though the current values for CY and BY are being removed. I have a security investment on the ITDB that currently matches tower and capability costs. After submitting updates to a PY capability, I received the following error: 

`The sum of all IT security compliance capabilities for CY ( 0.000800 ) should exactly match Total Security and Compliance Cost CY ( 0.001000 ) from the investment in the IT Portfolio.`

I received the same for BY. I did not make any changes to the CY or BY amounts. I will send over the Get and the Request file that triggered this warning.

**Comment by GihaVillazon** [comment]
Hi Alex, 

We will add this issue in the upcoming sprint to be analyzed further, however the mismatch of calculation is a warning not an error therefore it will not restrict any submissions. 

Thank You.
