### ISSUE TITLE
Data Feed IT Spending Totals

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#176]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The Data Feed Total IT Spending values do no include Contribution totals. The correct Contribution and Agency Funding spending values accurately display in their respective columns. However, the total only displays Agency Funding values. I will email over an example file that one of our Agencies generated earlier today.

**Comment by GihaVillazon** [comment]
Hi Ryan,

This is an impact due to the data feeds which are sceduled to be ready on September 28th.

Thank You.
