### ISSUE TITLE
Issue with values in column "ValiateOnly Submission" 

### ISSUE THREAD

**Issue by suchun** [ombegov/ITDB-schema#179]
For Security Investment Reports submissions, the values in column "ValiateOnly Submission" do not reflect the true value in the XML file, even the validateOnlyIndicator="true" in the xml, the column on the "Review Submissions" would display "N" instead of "Y".

**Comment by TsitsiL** [comment]
User sent 2 submission IDs to Helpdesk to investigate this issue. I have partially masked ID info below.

I checked submission with ID XXX730 and validateOnlyIndicator is false. Meaning it is a true submission (not just a validate). The Review Submissions page has this correctly indicated as “N,” it is NOT a validateOnly

For submission with ID XXX723, validateOnlyIndicator is true, meaning it is NOT a true submission (just a validate). The Review Submissions page has this incorrectly indicated as “N,” it should be “Y”. 

Requesting that Giha create a JIRA ticket for this to investigate incorrect setting demonstarted for 2nd submission above.

**Comment by GihaVillazon** [comment]
The Fix will be in place with the Hotfix 4 deployment. 

Thank You.

**Comment by TsitsiL** [comment]
Hotfix 4 was deployed on Wednesday night (9/13). I will go ahead and close this issue. Please let us know if you have any questions.
Thanks!
