### ISSUE TITLE
Part 2 Investment Incorrectly Required to provide Objective/Goal

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#181]
In performing the annual submission for a Part 2 major investment, I received the following error:

> If an investment has performance metrics (009-xxxxxxxxx), at least 1 metric should have a valid Performance Metric Objective or Goal value and belong to the performanceMetricCategory "2".

However, the FY19 guidance (pg. 58) limits this requirement to Part 1 investments:  

> For Investments listed in Part 1 of the Agency IT Investment Portfolio Summary, at least one of these metrics must contribute to a Strategic Objective or Agency Priority Goal.

As this prevents submission of a Part 2 investment, this is a high priority issue for us.

**Comment by ojedanico** [comment]
Bill,

We are currently fixing this validation error with Jira ticket 948 and will push in a hotfix. As soon as I know when we can push it out I will let you know.

**Comment by TsitsiL** [comment]
Hi Bill,
Hotfix 5 included a task ITD-950 to disable incorrect metric validations, including this one that you reported that was a blocker for you. This fix was deployed this morning. You should be good to go. 

I will go ahead and close this issue. Please let us know if you have any questions.

Thanks!
