### ISSUE TITLE
Security Get Response

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#184]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Critical
Description of Issue: One of our Agencies is experiencing a set of odd data returned for the Security Get File. It appears that a set of training data or test data is loaded for their SIRs. This Agency has yet to submit any SIRs, but the IT Dashboard returns data unrecognizable to them in Response files. It is critical to remove all odd data in their Get File Response.

**Comment by GihaVillazon** [comment]
Hi Ryan,

We are looking into this concern.
Thank You.

**Comment by rydougherty** [comment]
Following up to see if this was resolved?

**Comment by GihaVillazon** [comment]
Hi Ryan, 

We have noted the issue and it will be resolved tonight. The agencies should not encounter similar situation and will be able to proceed with their submissions without any faulty response. 

Thank You.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

The issue has been resolved.

Thank You.

**Comment by GihaVillazon** [comment]
Good Morning, 

I will be closing this ticket now, should you have further concerns we can reopen this ticket or create a new ticket as needed. 

Thank You.
