### ISSUE TITLE
DoD Question - Level at which TBM Data is submitted via xml

### ISSUE THREAD

**Issue by danielwyork** [ombegov/ITDB-schema#19]
Question from John Casteel from  DoD:

Want to make sure the level Cost Pool and IT Tower data will be submitted in the XML schema.  Will it be at the Investment level or Funding Source?

**Comment by GihaVillazon** [comment]
Hello, 

They are at investment level, and each investment will have a funding source. 
I have also attached the working FY19 Schema for your convenience:
https://github.com/ombegov/ITDB-schema/tree/master/draftBY19
