### ISSUE TITLE
Investment Rebaseline Counts

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#190]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: Last week, we discussed altering the way OMB tracks baseline changes during this submission period due to the data issue that was identified last week. Was a decision made on this?

**Comment by ojedanico** [comment]
Yes, the email states that the agency can either do an add function a rebaseline function. If you are concerned about how the baseline look we can alter for the agency on a case by case basis.

**Comment by murrayalex** [comment]
My concern is the actual count of rebaselines. This is a metric that OMB reports back to CIOs on the quarterly portfoliostat, and it something that Agencies take very seriously. If they performed a rebaseline over the summer, then an Agency may have to perform another now to "re-submit" the same update they made over the summer. For example, if a project changed its description or SDLC methodology during the summer (a baselined field), then they will be prompted for another rebaseline now to make the change again.

In this situation, will the OMB reconciliation process recognize these and remove the unnecessary rebaseline?

**Comment by austin-moffa** [comment]
Hi Alex,
Yes. That is the plan for the reconciliation implementation. We will be reaching out (in a similar way to deletes) in regards to the rebaselines which occurred in order to make sure they are properly backdated to their original submission time and will not be double-counted or misreported.

**Comment by murrayalex** [comment]
Thanks, Austin. I think that makes sense. We will let our Agencies know so they can be prepared for that discussion.
