### ISSUE TITLE
Removing Data from the IT Dashboard

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#191]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: What is the timetable for deleting data that was previously removed over the summer? Several of our Agencies have requested to have data removed by the ITDB group, and this data can impact and even prevent submissions in certain scenarios.

**Comment by rydougherty** [comment]
As a clarification, you have reached out to several of our Agencies about removing their data. We know of one at this point that has requested to have data removed. The timing of when you remove this data impacts the validations that our Agencies see and could ultimately impact their strategy for submitting today, so we’re trying to understand if these removes would take place today or after the submission window closes. Our recommendation is waiting until after the submission window closes in order to eliminate confusion. Thanks.

**Comment by ojedanico** [comment]
So far we have heard from (eCPIC agencies) is SSA and ED. If we do not delete the records they will not able to submit. We have already begun delete both agencies records. 

Once I have confirmation the records are deleted I will let you know should be confirmed by noon if not earlier.
