### ISSUE TITLE
getInvestment getContracts incomplete response

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#194]
Submitter: Barry Pannell
 Org: DHS/MBC
Priority: High 
Issue: Using the getInvetsment and the getContracts functions, we do not seem to be getting all contracts for investments.   
Investment 024-000005246 - 
Today - on the BY18 ITD data feed there are 7 contracts.  
On 9/14 we submitted an investment update XML file with 7 contracts updated along with the rest of the investment info.  Successful.    Response file shows the 7 contracts.
Yesterday and Today - using the getInvestment and getContracts service we receive only 3 of 7 contracts on the response file.  

This is seen on other investments as well.

This is also seen on risks.

We are using the getInformation functions to validate deleted and continuing information.

**Comment by GihaVillazon** [comment]
Hi Barry, 

I will have the team look into this issue. 

Thank You.

**Comment by GihaVillazon** [comment]
Hi Barry, 

I sent a file to your email, please review and respond. 

Thank You.

**Comment by barrypannell** [comment]
The 4 contracts listed in the email attachment were the 4 that I raised the issue on.  They were the first 4 that I reported.  

There are 14 more contracts that we expected to see on ITD for the DHS investments.  8 Acquisitions have been identified as not in the getinfo.  And 14 risks are identified as not in the getinfo.   
We have not reviewed the projects, activities, metrics or results yet because we were focusing on the sections that were affected by the deactivations.  
I thought this was an issue that was in the getinformation function since the updates were successful  last week.

**Comment by GihaVillazon** [comment]
Hi Barry, 

I sent an email to you with an attachment, please review and let us know should you have any further questions or concerns. 

Thank You.

**Comment by barrypannell** [comment]
I received the email.  I am starting the verification.  
Can you explain what happened to this data or what is happening that I don't see it via the getinformation function?  If I am aware of the condition that has caused the issue I can be on the lookout for the situation as I look to confirm?

**Comment by barrypannell** [comment]
The lists of data that you identified as data to recover in ITD includes data for investments that were 'downgraded' to non-major investments and investments that were 'reorganized' to non-standard infrastructure.  Did you want to include those contracts, risks, metrics, etc.. in the report?  are these data types that would be restored?

**Comment by GihaVillazon** [comment]
Hi Barry, 

I will close this ticket since you are testing the reconciliation records. If you see further issues we can reopen this ticket or create a new one. 

Thank You.
