### ISSUE TITLE
Projected Values in Agile Activities Table

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#197]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: I am unable to submit Agile Projected Completion Dates to the UAT Dashboard. I am receiving the error below: 

` <sr:message level="error">Error 1871: Element '{http://www.itdashboard.gov/service}projectedCompletionDate': This element is not expected. Expected is one of ( {http://www.itdashboard.gov/service}agencyActivityId, {http://www.itdashboard.gov/service}releaseName, {http://www.itdashboard.gov/service}releaseNumber, {http://www.itdashboard.gov/service}releaseDescription, {http://www.itdashboard.gov/service}NPI, {http://www.itdashboard.gov/service}NPE, {http://www.itdashboard.gov/service}NCE, {http://www.itdashboard.gov/service}NCI, {http://www.itdashboard.gov/service}DTC, {http://www.itdashboard.gov/service}DPC ). on line 1</sr:message>`

I will email over the request file soon.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

The error you received is due to attempt of placing projectedCompletionDate straight after activityID, so you are missing all of the other expected elements from agencyActivityID to plannedCompletionDate. 

Please retry with the below order: 

                    <businessCase-update:activityId>123</businessCase-update:activityId>
                    <businessCase-update:agencyActivityId>a</businessCase-update:agencyActivityId>
                    <businessCase-update:releaseName>a</businessCase-update:releaseName>
                    <businessCase-update:releaseNumber>a</businessCase-update:releaseNumber>
                    <businessCase-update:releaseDescription>String</businessCase-update:releaseDescription>
                    <businessCase-update:NPI>3</businessCase-update:NPI>
                    <businessCase-update:NPE>3</businessCase-update:NPE>
                    <businessCase-update:NCE>3</businessCase-update:NCE>
                    <businessCase-update:NCI>4</businessCase-update:NCI>
                    <businessCase-update:DTC>9</businessCase-update:DTC>
                    <businessCase-update:DPC>5</businessCase-update:DPC>
                    <businessCase-update:plannedStartDate>1970-01-01</businessCase-update:plannedStartDate>
                    <businessCase-update:actualStartDate>1970-01-01</businessCase-update:actualStartDate>
                    <businessCase-update:plannedCompletionDate>1970-01-01</businessCase-update:plannedCompletionDate>
                    <businessCase-update:projectedCompletionDate>1970-01-01</businessCase-update:projectedCompletionDate>
                    <businessCase-update:actualCompletionDate>1970-01-01</businessCase-update:actualCompletionDate>
                    <businessCase-update:plannedTotalCost>10000</businessCase-update:plannedTotalCost>
                    <businessCase-update:projectedTotalCost>10000</businessCase-update:projectedTotalCost>
                    <businessCase-update:actualTotalCost>10000</businessCase-update:actualTotalCost>
                    <businessCase-update:isActive>active</businessCase-update:isActive>
                  </businessCase-update:reviseUpdateAgileProjectActivity>


Thank You.

**Comment by rydougherty** [comment]
Hi Giha, thanks for the response. This is a monthly update submission so I should be able to omit the nodes that are not getting updated. Please see the updateInvestment Schema below:

```
  <element name="updateAgileProjectActivity">
    <complexType>
      <sequence>
        <element ref="businessCase-update:activityId" minOccurs="0"/>
        <element ref="businessCase-update:agencyActivityId" minOccurs="0"/>
        <element ref="businessCase-update:releaseName" minOccurs="0"/>
        <element ref="businessCase-update:releaseNumber" minOccurs="0"/>
        <element ref="businessCase-update:releaseDescription" minOccurs="0"/>
        <element ref="businessCase-update:NPI" minOccurs="0"/>
        <element ref="businessCase-update:NPE" minOccurs="0"/>
        <element ref="businessCase-update:NCE" minOccurs="0"/>
        <element ref="businessCase-update:NCI" minOccurs="0"/>
        <element ref="businessCase-update:DTC" minOccurs="0"/>
        <element ref="businessCase-update:DPC" minOccurs="0"/>
        <element ref="businessCase-update:plannedStartDate" minOccurs="0"/>
        <element ref="businessCase-update:actualStartDate" minOccurs="0"/>
        <element ref="businessCase-update:plannedCompletionDate" minOccurs="0"/>
        <element ref="businessCase-update:projectedCompletionDate" minOccurs="0"/>
        <element ref="businessCase-update:actualCompletionDate" minOccurs="0"/>
        <element ref="businessCase-update:plannedTotalCost" minOccurs="0"/>
        <element ref="businessCase-update:projectedTotalCost" minOccurs="0"/>
        <element ref="businessCase-update:actualTotalCost" minOccurs="0"/>
      </sequence>
    </complexType>
  </element> 
```

**Comment by GihaVillazon** [comment]
Hi Ryan, 

It seems you put "xsi:nil = true" in actualCompletionDate and actualTotalCost which is not allowed.
Please correct that before submitting again, it should work as one of the lead developers took the time to review your XML. 

Thank You.

**Comment by rydougherty** [comment]
Hi Giha, the error is triggering because the UAT Dashboard is not expecting us to send the Projected nodes through the Update Monthly Submission Operation. This issue does not revolve around the null Actual Completion Date and Actual Total Cost nodes. Can you double check to make sure that UAT Dashboard has the latest schema and is equiped to handle Projected values? 

I did try removing the null Actual Completion Date and Total Cost nodes and the same error still triggered. As an aside, we are expecting an error to trigger for null Actual nodes for testing purposes. But instead, we get errors for the Projected nodes instead.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

Thank you for your patience,
We were able to recreate the issue perhaps there was a deployment issue with the multiple hotfixes deployed, however with the recent deployment we did not see the error generate, could you please retest and verify. 

Thank You.

**Comment by rydougherty** [comment]
Thanks Giha, I just tested and everything appears to be resolved.

**Comment by GihaVillazon** [comment]
Great I will close this ticket now. 

Thank You.
