### ISSUE TITLE
"Server directory is not accessible" CIO Rating API Response

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#198]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: I am receiving a "Server directory is not accessible" response for the CIO Rating API on the UAT Dashboard while running the get file. I have posted the request file below:

`<?xml version="1.0" encoding="UTF-8"?><operations xmlns="http://www.itdashboard.gov/service" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.itdashboard.gov/service ../Exchange/serviceRequest.xsd" validateOnlyIndicator="false"><cioRatingInformation uniqueInvestmentIdentifier="011-000002502"><getInformation><getCIORating id="f3e48515-2a24-4a5c-9cc4-151ae634a25e" /></getInformation></cioRatingInformation></operations>`

**Comment by rydougherty** [comment]
Following up here, we are seeing the same issue for the Investment Report API as well. Did OMB intentionally take these APIs offline for the UAT Dashboard?

**Comment by ojedanico** [comment]
This should be fixed now please let me know if you are still seeing this error.

**Comment by rydougherty** [comment]
Hi Nico- still getting the error for both APIs on the UAT Dashboard:

```
Request:
<?xml version="1.0" encoding="UTF-8"?><operations xmlns="http://www.itdashboard.gov/service" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.itdashboard.gov/service ../Exchange/serviceRequest.xsd" validateOnlyIndicator="false"><cioRatingInformation uniqueInvestmentIdentifier="011-000100142"><getInformation><getCIORating id="4d3f026d-1c4d-4df5-b4a4-f29a5814c50f" /></getInformation></cioRatingInformation></operations>
*******************************************************************
Response:
Server directory is not accessible
```

**Comment by ojedanico** [comment]
ok looks like its fixed on our end please let us know if you are still seeing the error.
