### ISSUE TITLE
IT Dashboard Status

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#199]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: One of our Agencies successfully ran validations against the IT Dashboard this morning. Is the production Dashboard accepting submissions again? Or, was it just turned on for testing purposes?

**Comment by ojedanico** [comment]
No its open, Kelly sent out communication Tuesday morning.
