### ISSUE TITLE
SIR Delete Operation

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#200]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: Does OMB have a timetable for enabling the delete operation within SIR submissions? If not, should Agencies still plan on reaching out to have OMB manually delete SIR data?

**Comment by ojedanico** [comment]
This feature will be added during the 11A release scheduled for Nov 6 deployment through Jira ticket 1057.
