### ISSUE TITLE
Incorrect Objective or Goal Error

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#202]
When performing a monthly manual XML submission with two (or more) investments, I occasionally receive the following error:

Performance Metric Objective Or Goal (123) does not match a value provided at the investment level.

This occurs even though the goal (123) is at the investment level.

It appears that this occurs when there are two investments sent, investment A, and investment B.  Investment A is first in the file and includes tns:updateInvestmentDetails and investment B includes tns:updatePerformanceMetric.  What appears to be happening in this case is that the system pulls the investment objective and goal list from investment A and uses that to compare to the metrics in investment B.  Unless investment A happens to have a matching set of objectives and goals, the above error is generates.

Of note to support this, if I use the same XML file and remove the tns:updateInvestmentDetails from investment A, I no longer receive the incorrect error in investment B.  Additionally, if I reverse the order of the file to submit investment B first, followed by investment A, I also no longer receive an improper error.

As I can generally work around the issue by re-ordering the investments or splitting into more files, this is a lower priority for now, though it is a frustrating item to address.  It is also an issue reported last year, so I do not believe it is directly related to new changes.  I will be following up by providing three XML files to generate the error and to demonstrate the two tests mentioned above that avoid the error.

**Comment by TsitsiL** [comment]
Hi Bill,

while I was going through help desk tickets I had created for other agencies I came across one that seems identical to yours. So I will group yours and that issue together in ITD-684 (I know you can't access our JIRA tickets but I wanted to make sure I reference it here so we don't lose track). I will also attach the XML files you sent for this issue to the same ticket.

Thanks!

**Comment by TsitsiL** [comment]
Bill,

I also found a workaround in that issue that might work for you:
_User was asked to retry submission one investment at a time. User responded that this works, so we have a workaround so their monthly submission will not be delayed._

Please try the workaround and let us know if it works. The ticket is still resolve the root issue so the workaround is temporary.

Thanks!

**Comment by bill-gehrke-hhs** [comment]
That workaround does work, but with 98 investments to report is not practical.  Re-ordering the investments within the file is the somewhat more practical workaround for us.
