### ISSUE TITLE
CIO Rating Error explanation 

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#203]
Name: Barry Pannell 
Org: DHS(MBC Consulting)
Urgency: Moderate
Description: 
Could you please explain the reason behind the associated error:

•alertCIO Evaluation submission failed◦CIO Rating with UII: 024-000005624 : 
alertError: Unique Investment Identifier 024-000005624 is for a major investment. Agencies are required to submit a CIO Evaluation Report for all of their major investments, Type 01, during business case submission.

I received the error when doing a validate  submission.  Got it in both prod and test environments.

**Comment by ojedanico** [comment]
Hey Barry,

the logic is all major investments require a CIO Evaluation, Is the investment UII: 024-000005624 a major investment?

**Comment by barrypannell** [comment]
Hi –
All 39 DHS majors had CIO rating updates submitted over the summer.  19/39 were updated on Aug 31.  8 were last updated at the end of June and the remaining were updated in early May.
In September they were not ready with any updates to the rating or comments.
So I had expected that the ratings carry over from the last update.
Do we need to resubmit all ratings now?

024-000005624 is a major but in my test file I did not include it.

Barry


Barry Pannell
INVEST Support – OCIO EBMO
MBC Consulting
866-233-9904

**Comment by barrypannell** [comment]
Additional info.  
I used the CIO Rating XML/XSD schema format above.  
When I reverted back to using the CIO Rating update via the business case monthly update file format, I was successful.  
I looked into the ITD CIO Rating data by using the data feed of CIO Ratings and I see all the ratings updates from the summer.
