### ISSUE TITLE
Costs and Capabilities Delete Operation 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#207]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The SIR API does not allow us to delete Cost and Capabilities using the OMB ID (`capabilityId`). I am receiving an error when sending a delete operation accompanied by the `capabilityID`. The error goes away when I add an `agencyCapabilityID` to the file. However, many Agencies do not submit Agency IDs and rely on the IT Dashboard generated OMB IDs.

Request File:
```
<?xml version="1.0" encoding="UTF-8"?>
<towers validateOnlyIndicator="true">
  <tower>
    <operation>update</operation>
    <towerDetails>
      <UII>019-000001884</UII>
    </towerDetails>
    <costsAndCapabilities>
      <costAndCapability>
        <capabilityID>3782</capabilityID>
        <operation>delete</operation>
      </costAndCapability>
    </costsAndCapabilities>
  </tower>
</towers>
```

Response:

> An identifier must be provider for the operation: delete.

**Comment by ojedanico** [comment]
We currently created a  Jira ticket 1297 to address this issue. Currently the fix is to replace the capabilityID with the OMB ID.
Jeremiah is currently looking into the 1A sprint to see if we can address this issue during 1A. I will update as soon as I have one with times of the sprint and deployment.

**Comment by ojedanico** [comment]
Ticket 1297 has made it into the 1A sprint scheduled to deploy Jan 3rd.
