### ISSUE TITLE
New Capability Codes

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#21]
Name: Alex Murray
Organization: eCPIC
Urgency: Medium
Description of Issue: The current schema does not outline the enumerations for the new capabilities within the Costs and Capabilities table. In order to update our template for this table, we need the codes that will be associated with each new capability. Is there a timeline for publishing these codes?

**Comment by GihaVillazon** [comment]
Good Morning, 

We will have the requested data posted towards the end of July. 

Thank you,
Giha

**Comment by ojedanico** [comment]
Please use this table for the Agency Capability Codes. 

Thank you 
[Agency Capability Codes.xlsx](https://github.com/ombegov/ITDB-schema/files/1097834/Agency.Capability.Codes.xlsx)

Nico
