### ISSUE TITLE
12/18 Deployment

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#210]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: Did OMB deploy the Schema changes last night? This morning, I am still able to successfully send Investment Start Date and End Date nodes in the Annual Submission Capital Asset Summary.

**Comment by TsitsiL** [comment]
Good morning Ryan,

Release 12B with the schema changes was not deployed last night, we had a delay and it will be deployed this evening. This was communicated by Justin yesterday during the vendor call. Our deployments are usually completed after 7PM, so you can expect the changes when you submit tomorrow morning.

Thanks!
