### ISSUE TITLE
Rebaseline Response Does not match XSD or Examples

### ISSUE THREAD

**Issue by kengineer** [ombegov/ITDB-schema#213]
We submitted a rebaseline request to the myuat-2019 test endpoint and it submitted successfully but the response back was not what we were expecting. According to the XSD and the examples provided with the API, the response should have the following hierarchy...

- sr:operationResults
    - sr:investment
        - sr:success
            - sr:reviseInvestmentResult
                - businessCase-response:capitalAssetPlan
                    - businessCase-response:capitalAssetSummary
                    - businessCase-response:performanceMeasureReport
                        - businessCase-response:performanceMetrics
                            - businessCase-response:performanceMetric
                            - businessCase-response:performanceMetric

However, the response we received back had the following hierarchy (see attached for actual response)

- sr:operationResults
    - sr:investment
        - sr:success
            - sr:reviseInvestmentResult
                - sr:performanceMetric
                - sr:performanceMetric

Is this an error in the XSD/Samples and we should assume the response will always be in the form we received or an error in the API that will be fixed.

Please let me know if you need more information.

[Response_2017-12-27_11-05-07-AM.zip](https://github.com/ombegov/ITDB-schema/files/1591344/Response_2017-12-27_11-05-07-AM.zip)

**Comment by ojedanico** [comment]
There is no error 

This actual response you provided is for a monthly submission.  The example response displayed is for an annual submission.

The response you received is the expected response for a monthly submission.

We could update the example file to show the expected reviseInvestment section that corresponds to the monthly submission vs the annual submission.  Would this be beneficial?
