### ISSUE TITLE
ATIPS Database Comparison 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#214]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: Will OMB use last year's Passback submission database or this fall's Annual submission database to compare against upcoming AITPS submissions? In other words, when Agencies are setting their Change in Status Identifiers should those values compare against what was submitted in the fall or what was submitted in last winter's Passback window? Traditionally, if an Agency eliminates an investment in the fall it would still include that eliminated investment in the Passback AITPS (Change in Status = eliminated). In order to do so, OMB must be comparing data against last year's Passback database.

**Comment by ojedanico** [comment]
No change to this functionality. The system ignores stage 1 (fall) submissions for the current budget year and compares stage 2 (passback) submissions for the current budget year to the latest submissions in the previous budget year (stage 2 BY18).

**Comment by rydougherty** [comment]
Thanks Nico, that approach works well for us.
