### ISSUE TITLE
Cost and capability

### ISSUE THREAD

**Issue by suchun** [ombegov/ITDB-schema#215]
How does cost and capability work?  If we have a cost and capability item, for passback submissions, if we made changes to it, do we add it to the new ITP, or we send it with "update" tag to the dashboard?  If we deleted a capability, do we send it with a "delete" tag?

**Comment by ojedanico** [comment]
I am not 100% sure what you are asking so I hope this helps...

Cost and capabilities items are maintained through SIR submissions, not IT Budget submissions.  Only IT Budget Submissions for Stage 2 ignore what was entered for Stage 1.  Business Case, SIR, and CIO Evaluation submissions are permanent changes.  Anything added, changed, or deleted in Stage 1 remains added, changed, or deleted.  So if they added a cost and capability item for this budget year, they do not need to add it again.  If they have changes to that cost and capability item now, they would submit those changes as an "update".  If they already deleted a cost and capability item, it will still be deleted; they cannot do anything with this item.  If they need to delete a cost and capability item, then they would submit it with a "delete" operation.

**Comment by suchun** [comment]
Thank you for your prompt reply, that’s exactly what I asked for.

**Comment by suchun** [comment]
IT was a mistake related ITP to Cost and Capability, it should be Security Report.  Thanks again!
