### ISSUE TITLE
CY Funding for Eliminated investments

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#218]
In testing our IT Budget Submission on UAT, I receive the following error:

◦IT Portfolio with UII: 009-xxxxxxxxx: 
alertError: BY and CY amounts must be zero for eliminated investments

While I see that this validation is listed in the current set of validations (and, looking at the history, may never have been formally removed from the documented list of validations,) this validation was not in place for September.  In fact, it was removed after lengthy discussions, including an in-person meeting, in which we were given specific scenarios for eliminating investments while reporting CY funding (see github issue #75) as an example.

Please advise as to whether the elimination scenarios provided before the September submission still apply or whether CY funding will no longer be allowed for investments being eliminated.

**Comment by rydougherty** [comment]
This appears to be a continuation of closed issue #58

**Comment by ojedanico** [comment]
Bill, 

You are correct - it seems that we missed moving this validation from our records and have updated the validation document to reflect what is current in our code. In addition, I had our development team double check the code to make sure this validation has been removed. 

Please feel free to notify us if you are experience something different.

**Comment by bill-gehrke-hhs** [comment]
I just re-tested our submission in the UAT environment and again received this error for the investment being eliminated which has CY funding.

**Comment by ojedanico** [comment]
Hey Bill 
Thanks for the heads up - we have added to UAT to match production. please let us know if you are still seeing an issue.

**Comment by bill-gehrke-hhs** [comment]
Thanks.  This has been resolved for us in UAT.
