### ISSUE TITLE
Previous year 'eliminated by funding' investment has received funding

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#219]
Submitter: Barry Pannell
 Org: DHS/MBC
Issue: Getting error 'PriorUII must correspond to an active investment from the prior budget year submission'.    
For BY18 submission, investment 024-000004053 had no funding for FY17 and FY18 at final submission day.  In order to report the investment with 0 funding in those years, the status was set as 'eliminated by funding'.   
Now the investment has funding for FY18 and FY19, and the department wants to submit with same UII.  
Error is being raised that prior UII had to be 'active' in prior budget year.  I do not believe that validation was tightly enforced previously as 'eliminated by funding' investments were able to be 'reactivated' in the following year with same UII.  

Recommendation: Clarify this error is what is desired by ITD validation.  Is correct submission procedure to submit with new UII as status = new.

**Comment by ojedanico** [comment]
Yes, these is the desire outcome per OMB, therefore you will need to submit with a new UII as status = new.  please  let me know if you have any questions.
