### ISSUE TITLE
AITPS Validations

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#22]
Name: Ryan Dougherty
Organization: eCPIC PMO (BAH)
Urgency: Medium
Description of Issue: When performing AITPS Validations (validateOnlyIndicator=”true”) if there are no errors returned in the response file, then, regardless of whether warnings should get returned, no warnings will be returned in the response file. If there are errors returned or if you are submitting (validateOnlyIndicator=”false”), warnings will get correctly returned where applicable. In other words, if I am validating the AITPS and I address all the issues that are triggering errors, I will no longer be able to see what warnings are getting triggered until after I have submitted. 
Associated Links: None

**Comment by GihaVillazon** [comment]
Good Morning, 

We have received your request, and are looking into a solution. We will communicate the steps/solution within this chain, as the response progresses. 

Thank You,
Giha

**Comment by TsitsiL** [comment]
Good afternoon,
we created ticket ITD-562 for this issue, which will be presented to the product owner for prioritization. We will provide updates on this issue as we get them.

Thanks!

**Comment by ojedanico** [comment]
The solution is being worked during this sprint targeted to be completed by Wednesday 19th. If the date slips we will update the post.

**Comment by ojedanico** [comment]
A solution has been identified and implemented however it still needs to go through QA and Security reviews. Therefore, the solution issue will be available for testing in the July 31st release.
