### ISSUE TITLE
IT Dashboard Down

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#221]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: For your awareness, it appears that the myit-2019.itdashboard.gov sites was briefly down this morning. Several our Agencies reported connection errors, and we confirmed in our error logs that your application was unavailable. This downtime appears to be resolved, and our Agencies are currently connecting fine with the IT Dashboard site. Just wanted to make sure your team was aware of this.

**Comment by ojedanico** [comment]
Issue resolved on Jan 23rd.
