### ISSUE TITLE
Submitting a Blank List of PRA Control Numbers

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#224]
It appears the schema is not allowing the submission of a blank list of control numbers.  This may be necessary where a record was submitted and it no longer applies and/or was submitted in error and the investment should have no PRA control numbers associated with it.  I first attempted to do this with an annual submission and then with a monthly.  For the monthly, I attempted using all of the following (recognizing the first two and second two should be the same) to force a blank set of control numbers:

```
<tns:ombControlNumbers><tns:ombControlNumber></tns:ombControlNumber></tns:ombControlNumbers>
<tns:ombControlNumbers><tns:ombControlNumber/></tns:ombControlNumbers>
<tns:ombControlNumbers></tns:ombControlNumbers>
<tns:ombControlNumbers/>
```
All pass the XSD but all returned the error:

> ◦updateInvestmentDetails: 
> alertOMB Control Number is optional but if submitted must be entered in the following format: XXXX-XXXX.

I would expect that submitting one of the above should be understood to indicate that the list of control numbers is being overriden with a blank list.  Alternatively, a tag (similar to the "nil" attributes used in some areas) could be added to make it more explicit.

In either case, please advise as to the best way both to address the issue for the current investment (recognizing this may be a manual request to remove the data) and the plan for supporting this functionality long-term.

**Comment by ojedanico** [comment]
We have created Jira ticket 1400 to resolve this issue. Once the ticket has been assigned to a sprint I will provide an update with the release date and the solution to fix the issue.

**Comment by ojedanico** [comment]
Ticket 1400 has be added to sprint 2B to be deployed on the 26 Feb 2018.

**Comment by TsitsiL** [comment]
The fix for this was deployed on 3/12. Closing this ticket.
