### ISSUE TITLE
Maximum Value for Agile Epics

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#226]
There seems to be some discrepancy regarding the maximum value for NPE and NCE.  According to (what I think is) the most recent data dictionary:

NPE - decimal(3,1) - 112.3
NCE - decimal(3,1) - 112.3

However, according to the most recent production schema:
simpleType name="agileEpics"
  restriction base="decimal"
  pattern value="[0-9]{0,2}(\.[0-9]{0,1})?"/

The data dictionary indicates a maximum value of 999.9 and the schema indicates a maximum value of 99.9. Can you please let me know which is correct and then update where appropriate? Thanks!

**Comment by ojedanico** [comment]
This is not a development issue.  The data dictionary example needs to be updated.  Both the database column definition (decimal(3,1)) and the schema type definition (decimal [0-9]{0,2}(\.[0-9]{0,1})) both indicate that the maximum value is 99.9.  The example of 112.3 is invalid.  The maximum allowed is 99.9.  The data dictionary will be updated and provided to the vendors.

**Comment by courtneycorwin** [comment]
Hi Nico,

Updating the data dictionary resolves this ticket for me as well as the users that routed the question through me. Thanks!!
