### ISSUE TITLE
Non-Major (Downgraded Major) Investment CIO rating update Failed

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#232]
Submitter: Barry Pannell
 Org: DHS/MBC
 Issue: Attempted to submit a CIO rating update for a non-major investment (that was just downgraded major to non-major in January) and the submission failed.  Investment 024-000005395.  The investment rejected indicating 'a CIO rating with the initial business case was required' when submitting using the CIO Rating Assessment XML file upload option.   

Recommendation: This 'downgraded' investment CIO Rating update should be treated like other non-major investment or infrastructure rating updates.

**Comment by ojedanico** [comment]
Jira Ticket 1414 was created for sprint 2b release scheduled for deployment on 2/26.
