### ISSUE TITLE
Question about public available ITD investments and fields 

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#234]
Submitter: Barry Pannell
 Org: DHS/MBC
Issues/questions:  
For the 2019 ITD dashboard available to the public - 
1) The current 2019 ITD available to the public is not showing the standard and non-standard infrastructure investments.  Will those display on Feb 12?  
2) The current ITD is only showing FY17 funding.  Is FY18 funding not displayed to the public yet because there is not a full year FY18 appropriation yet and the funding is still through a CR?  Will FY18 show when there is a full year appropriation - between today and March 23 or whenever a full year appropriation passes?  
3) When will the FY19 funding plan show to the public?  Is that when the President's Budget is submitted to Congress or later?

**Comment by ojedanico** [comment]
1.	They will be displayed to the public tonight in the Individual Investments table, IT Portfolio data feed, and IT Portfolio Funding Sources data feed; however, some of the data feeds (e.g. CIO Evaluation history) will need to be updated to show them. (i.e. future release)
2.	FY18 is showing as of Feb 12. 
3.     FY19 is showing as of Feb 12.
