### ISSUE TITLE
Error Attempting to Update Investment Details

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#237]
When submitting an XML update including the updateInvestmentDetails section, I receive the following error:

> Error
> 
> Undefined variable: validControlNumber

This issue appears to have been introduced in the Monday-Tuesday timeframe as it did not appear when the XML files were tested Monday morning but did appear when they were submitted on Tuesday afternoon.  The error is now reproducable by submitting that section and is avoided by removing the updateInvestmentsDetails section.

All of the investments have no OMB Paperwork Reduction Act control numbers and none are attempting to add/modify that data.  (Based on the error, I am assuming this is what is at issue.)  As this is not a required field, there appears no reason for the error.

An additional concern is the form and behavior of the error  It appears that the files - which contained about 10 investments each - were processed to the investment with the error, meaning some, but not all, of the investments' data was submitted to the dashboard.  However, the response file is blank.  I would expect an error like this to prevent all processing of the file.  And, if it does not, I would expect a response file that indicates (un)successful completion of the investments before the one encountering this error.

I will email XML for the investments with issues.

**Comment by TsitsiL** [comment]
Good morning Bill,

I verified with the team that there was a change in logic around the element ombControlNumber to address another reported issue. So for now, the logic is expecting this element to be included and will throw this error. There are workaround options detailed below that will bypass this error so your submission can go through.

Workaround options:
1.	Include all of the OMB Control Numbers for this investment. You do this if you want to keep any existing ones in the database; or
2.	If you don’t have any existing OMB controls numbers for this investment in the database or you want them removed/eliminated, you can just include the parent element without any value <ombControlNumbers>  and without any <ombControlNumber> child elements.

Please try either option and let us know if you have any issues.

As I mentioned, the workaround is for now so you can submit while we work on the OMB Control Number logic.

**Comment by bill-gehrke-hhs** [comment]
I can confirm that this addresses the issue for the affected investments and should allow for a successful submission.  The additional concern I noted is still outstanding in that since these files have already been submitted and it appears that some data was accepted by OMB, I am looking for validation on that.  The specific submissions were provided via email and we can persue that concern there.

**Comment by TsitsiL** [comment]
Closing this ticket for the 1st issue. The 2nd issue will be addressed separately via help desk since it has agency-specific information.
