### ISSUE TITLE
Draft Schema Questions

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#24]
Name: Ryan Dougherty
Organization: eCPIC PMO (BAH)
Urgency: Medium
Description of Issue: Paperwork Reduction Act OMB Control Number is not included in the Draft Schema. Will this eventually get added to the Investment Details Section? If so, can the Data Type and Text Length also be provided?
Associated Links: None

**Comment by GihaVillazon** [comment]
Hi Ryan, 

Major IT Business case has an added question to collect the "Paperwork Reduction Act OMB Control #". The details will be collected within the Investment Detail Section, however we will be publishing updated FY19 Schema, with all the details. 

Thank You.

**Comment by rydougherty** [comment]
Thanks for the response. I noticed that OMB Control Numbers was added as a field in the Add Investment and Update Investment Draft Schemas. Similar to Data Center ID and Public Urls, it appears that the IT Dashboard is expecting the data to be submitted in a table format, as in one <ombControlNumber> node for each Control Number nested underneath the <ombControlNumbers> node. In other words, if an investment is associated with three OMB Control Numbers, would you expect three <ombControlNumber> nodes? Can you please confirm if this is the case? 

Also <ombControlNumbers> is missing from the Investment Response Schema.

**Comment by GihaVillazon** [comment]
Yes, The way its structured is to list the Control Numbers one after the other.
We have published the working FY19 Schema please refer to below link for further clarification. https://github.com/ombegov/ITDB-schema/tree/master/draftBY19
