### ISSUE TITLE
Draft FY19 AITPS submission process 

### ISSUE THREAD

**Issue by danielwyork** [ombegov/ITDB-schema#25]
**Name:** Daniel W. York
**Organization:** GSA, eCPIC PMO
**Urgency:** Medium 
**Description of Issue:** The 95% FY 19 IT Budget Guidance says "Details and instructions for submitting the verification of eGov/LoB contributions and the Draft Agency IT Investment Portfolio Summary will be forthcoming." Can OMB OFCIO expand on how it will be expecting to collect the Draft FY19 AITPS submission from Agencies? In the past OMB has asked for this data in a number of ways from posting them to an OMB MAX page, to emailing them to their OFCIO Desk Officer, to submitting them via API to the ITDB. The answer to this question may impact the prioritization of work items for CPIC Vendors, especially if OMB OFCIO is planning to ask for Agency Draft FY19 AITPS submission via API.

**Comment by danielwyork** [comment]
@mattbailey0 and @justgrimes - Has this been figured out yet?

**Comment by ojedanico** [comment]
Dear CPIC Vendor Community, 

The process for this year’s draft IT Portfolio will require agencies to send an excel file via email to their respective Agency’s Desk Officer and cc OFCIO@omb.eop.gov. The response is due August 21st. 

Note: This date is subject to change based on the release of A-11 Guidance. 

This pre-submission information is important to help OMB understand agencies’ progress in the transition to standard investment reporting. In addition, this pre-submission will help facilitate any questions or concerns you may have in filling out this year’s budget. 

The excel spreadsheet must include the following fields for the submission:
Previous UII
Current UII
Shared Services Category
Shared Services Identifier
Bureau Code
Part of Agency IT Portfolio Summary
Type of Investment
Standard IT Infrastructure and Management Category 
Change in Investment Status Identifier
Agency Description of Change in Investment Status
Investment Title
Investment Description
FEA BRM Services – Primary Service Area

The CPIC CoP has be instructed via email - If they have any question regarding your agency’s IT Portfolio or this transition to standard investment reporting please reach out to your Desk Officer. 

If you or your clients have any questions about this submission process please feel free to reach out to Nico Ojeda at Nicolas.J.Ojeda@omb.eop.gov.

**Comment by danielwyork** [comment]
Do we know when this information will be published to the wider CPIC Community? Once the information is distributed formally to the CPIC Community, this ticket can be closed.

**Comment by ojedanico** [comment]
Gordon sent out the email to CoP today.
