### ISSUE TITLE
Performance Metric Comment Baseline Logic

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#250]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium 
Description of Issue: I wanted to confirm if Performance Metric Actual Result Comments are baselined after an Agency has provided Actual Result data? In the past, this field has been baselined once a comment was submitted to the IT Dashboard. In the baselined fields section of version 24 of the Submission Instructions document, OMB merged and attached the comment “New actual results can be added at any time. Actual results become baselined once provided” to the performanceMetricActualResult, performanceMetricDateofActual, and performanceMetricComment fields. However, in version 25, it is unclear if the “New actual results can be added at any time. Actual results become baselined once provided” comment still applies to the performanceMetricComment field due to a page break (see pages 13-14). Can you please help clear up whether an Agency is able to change their Performance Metric Actual Result Comment without an accompanying rebaseline?

**Comment by TsitsiL** [comment]
Response provided via IT Dashboad Support email:

Good afternoon Ryan,

The note: “New actual results can be added at any time. Actual results become baselined once provided” applies to all of these fields:
performanceMetricActualResult 
performanceMetricDateofActual
performanceMetricComment

So answer your question, yes, this Performance Metric Actual Result Comments becomes baselined once a comment has been provided.

Thanks!
