### ISSUE TITLE
Costs and Capabilities Nodes

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#26]
Name: Ryan Dougherty
Organization: eCPIC PMO (BAH)
Urgency: Medium
Description of Issue: Costs and Capabilities Table is still in the Schema for the Major IT Business Case, albeit as an optional set of nodes. Will the Costs and Capabilities nodes be removed from the Major IT Business Case?
Associated Links: None

**Comment by GihaVillazon** [comment]
Costs and Capabilities nodes will not be removed from the Major IT Business Case.
We have the working schema published below is the link for your convenience.
https://github.com/ombegov/ITDB-schema/tree/master/draftBY19
