### ISSUE TITLE
Government FTE Nodes

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#27]
Name: Ryan Dougherty
Organization: eCPIC PMO (BAH)
Urgency: Medium
Description of Issue: Government FTE nodes are still in the Life Cycle Costs table with no indication of switch to the Internal Labor language. Will the nodes continue to reference Government FTEs or will Internal Labor nodes be introduced to the Life Cycle Costs Table and the Internal Labor Cost Pools?
Associated Links: None

**Comment by GihaVillazon** [comment]
For this year Government FTEs and Internal Labor are both accounted and The FTE - lifecycle table differentiates between DME and O&M. Internal Labor makes no reference to DME and O&M. In FY20 it will only be Internal Labor.

Thank You.
