### ISSUE TITLE
Contracts Report Success Response and UAT Environment

### ISSUE THREAD

**Issue by kengineer** [ombegov/ITDB-schema#271]
I see there is a sample response for contracts reports, but the response is for only a failed submission. Is there a sample response for a successful submission?

Also, I was testing to see if https://myuat-2020.itdashboard.gov/api/v1/contractsreport would allow me to perform any operations yet in attempt to see what type of responses are returned, and I noticed I get a "UII could not be found message" for **get** and **add** operations for UII's that are valid, at least on the Business Case side. I understand this functionality may still be in development, and if that is the case, that's fine. Otherwise, if it should work, is there something that needs to be done to make UII's active for contract reports in the UAT environment?

Thanks,
Ken

**Comment by jeremiah-tcg** [comment]
Hi Ken, 

Thank you for posting this. We created a sample response for successful submission for the Contracts Report, but missed pushing it to the repository. We'll be sure to include it in our next push. 

Regarding your second concern, were you submitting the Contracts Report before or after submitting an FY20 IT Budget? Users must start with an IT Budget upload or they will have no FY20 investments to work with in UAT.

If the response occurred after you had already submitted an IT Budget for FY20, can you provide the UIIs that were returned as invalid? Tests of Contracts Report submission on our end have been successful thus far.

Regards, 

Jeremiah

**Comment by kengineer** [comment]
Thanks for the reply. We have not submitted the IT Budget for FY20 yet so we'll try that and let you know if we run into any issues. 

Thanks again.
Ken

**Comment by kengineer** [comment]
FYI, I believe everything is working as expected after we submitted and IT Budget.
