### ISSUE TITLE
Draft Agency IT Investment Portfolio Summary

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#273]
Page 12 of the guidance indicates that "At a minimum, the Draft Agency IT Investment Portfolio Summary should include the Previous Unique Investment Identifier (UII), Current UII, Investment Category, Shared Services Identifier, Part of Agency IT Portfolio Summary, Type of Investment, Investment Title, Investment Description, and FEA BRM Services – Primary service area."

The concern I have relates to the "Investment Category," which is not a field in the IT Investment Portfolio Summary.  Based on the order listed (which seems to list them in the order they appear in the full exhibit,) it would appear this might be intended as "Shared Services Category" (and would also make sense as the Shared Services Identifier is required but is not as meaningful without the Shared Services Category.)  However, there are also the "Mission Support Investment Category" and "Standard IT Infrastructure and Management Category" fields which are investment categories that are not otherwise listed in the set of required fields for the draft.  Could you please clarify what is expected for the "Investment Category" field?

**Comment by elliotyoon202** [comment]
Good Morning, 

We have confirmed that Investment Category refers to "Shared Services Category" in the template posted to the MAX site: https://community.max.gov/x/N6LIWw
