### ISSUE TITLE
Get File Server Error for SIRs

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#276]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The Get File Response for SIRs is returning a server error on our end. The same request files were working fine on Tuesday:

Request:
`<?xml version="1.0" encoding="UTF-8"?><towers validateOnlyIndicator="false"><tower><operation>get</operation><towerDetails><UII>011-000003024</UII></towerDetails></tower></towers>`

New Response:
`{"ok":false,"error":true,"metadata":null,"httpStatusCode":500,"httpStatusMessage":"Internal Server Error","responseTime":0.063064098358154,"result":"The server encountered an unexpected error. Please try again."}`

Old Response: 
`<?xml version="1.0"?>
<InvestmentReportResponse>
  <towers>
    <tower>
      <operation>get</operation>
      <towerDetails>
        <UII>011-000003024</UII>
      </towerDetails>
      <CriticalErrors>
        <errors>
          <error>The UII (011-000003024) could not be found, is not active, or does not have type="05"  (Currently:  01) and PartOfExhibit="03"  (Currently:  01), and an InfrastructureManagementCategory in (02, 04, 05, 06). (Currently:  01)</error>
        </errors>
      </CriticalErrors>
      <status>Get Failed</status>
    </tower>
  </towers>
  <response>
    <tower>
      <towerDetails>
        <UII>011-000003024</UII>
      </towerDetails>
      <CriticalErrors>
        <errors>
          <error>The UII (011-000003024) could not be found, is not active, or does not have type="05"  (Currently:  01) and PartOfExhibit="03"  (Currently:  01), and an InfrastructureManagementCategory in (02, 04, 05, 06). (Currently:  01)</error>
        </errors>
      </CriticalErrors>
      <status>Get Failed</status>
    </tower>
  </response>
</InvestmentReportResponse>
`

**Comment by courtneycorwin** [comment]
We received this error as well.

**Comment by elliotyoon202** [comment]
We believe that this issue has been solved with our deployment last night. Would you/your team be able to check if this issue was solved?

**Comment by rydougherty** [comment]
Thanks Elliot, we have verified the issue is resolved.
