### ISSUE TITLE
AITPS Warnings

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#277]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: This has been a bit of a lingering issue, however, we are still noticing that AITPS warnings only display if the response file also returns validation errors. In other words, if I am an Agency and do not receive any validation errors on the AITPS file I am submitting, than I have no way of viewing the warnings that the IT Dashboard should be communicating to me. 

See closed issue #22

**Comment by rydougherty** [comment]
Hi Elliot, it appears to be happening with all AITPS warnings. If I notice an exception, I will let you know.

**Comment by elliotyoon202** [comment]
For internal tracking purposes, this is Jira ticket ITD-1890

**Comment by jeremiah-tcg** [comment]
The resolution for ticket ITD-1890 was deployed on 11/5. Please confirm if we can close this issue.
