### ISSUE TITLE
MITBC Get File Server Error

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#278]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The Get File Response for MITBC is returning a server error on your end. It appears that the IT Dashboard cannot locate the Commercial Solutions Adoption field.

Request:
`<?xml version="1.0" encoding="UTF-8"?><tns:operations validateOnlyIndicator="false" xmlns:businessCase-update="urn:us:gov:businessCase-update" xmlns:businessCase-add="urn:us:gov:businessCase-add" xmlns:tns="http://www.itdashboard.gov/service" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><tns:investmentInformation uniqueInvestmentIdentifier="011-000002616"><tns:getInformation><tns:getInvestment id="27c65cd6-9d6b-42ac-b019-aadefc688551" /></tns:getInformation></tns:investmentInformation></tns:operations>`

Response:
`{"ok":false,"error":true,"metadata":null,"httpStatusCode":500,"httpStatusMessage":"Internal Server Error","responseTime":0.10431599617004,"result":null,"errors":[{"code":2,"message":"PDOStatement::execute(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'commercialSolutionsAdoption' in 'field list'","severity":0,"file":"\/services\/sEgvHttpP\/server\/20\/htdocs\/api\/Pittsburgh\/Controllers\/ITDB2\/BusinessCase\/entities\/InvestmentProject.php","line":395}]}`

**Comment by elliotyoon202** [comment]
We believe that this issue has been solved with our deployment last night. Would you/your team be able to check if this issue was solved?

**Comment by rydougherty** [comment]
Thanks Elliot, we have verified the issue is resolved.
