### ISSUE TITLE
IT Budget validation errors

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#279]
Name: Sriram Avasarala
Organization: Treasury
Urgency: Medium
Description of Issue: As per FY2020 guidance, cost pool names changed from "Costs" to "Amounts." and IT Tower names changed from "Costs" to "Amounts" but the CostPoolCategorySimpleType and ITTowerCategorySimpleType values are not updated in the ITBudget-facet.xsd file. Can you publish the updated ITBudget-facet.xsd file to GitHub. 

https://github.com/ombegov/ITDB-schema/blob/master/src/ITBudget/Subset/ITBudget-facet.xsd
https://github.com/ombegov/ITDB-schema/releases/tag/v2.0.5

We are getting the following validation errors.  

Error 1840: Element '{urn:us:gov:update-ITBudget-ext}CostPoolCategory': [facet 'enumeration'] The value 'Total External Labor Cost' is not an element of the set {'Total Internal Labor Amount', 'Total External Labor Amount', 'Total Outside Services Amount', 'Total Hardware Amount', 'Total Software Amount', 'Total Facilities and Power Amount', 'Total Telecom Amount', 'Total Other Amount', 'Total Internal Services Amount'}. in input on line 65

Error 1840: Element '{urn:us:gov:update-ITBudget-ext}ITTowerCategory': [facet 'enumeration'] The value 'Total Compute Cost' is not an element of the set {'Total Data Center Amount', 'Total Compute Amount', 'Total Storage Amount', 'Total Network Amount', 'Total Output Amount', 'Total End User Amount', 'Total Application Amount', 'Total Delivery Amount', 'Total IT Security and Compliance Amount', 'Total IT Management Amount', 'Total Platform Amount'}. in input on line 79

**Comment by elliotyoon202** [comment]
ITBudget-facet.xsd file has been pushed to the repo
