### ISSUE TITLE
Data Center ID Submission

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#28]
Name: Ryan Dougherty
Organization: eCPIC PMO (BAH)
Urgency: Medium
Description of Issue: If an Investment has multiple Data Center IDs associated with it, should the Investment submit multiple <DataCenterID> nodes under a single investment, or should all Data Center IDs be included within the same node?
Associated Links: None

**Comment by GihaVillazon** [comment]
Hello, 

Each investment can have one datacenterID, I have attached the link directly to the XML Sample for your convenience. 
https://github.com/ombegov/ITDB-schema/blob/master/draftBY19/InvestmentReport/examples/datacenter.xml

Thank You.

**Comment by rydougherty** [comment]
Thanks for the response.  I was looking at the Data Center ID field within the AITPS and that behavior contradicts the example schema posted above, which is from the Data Center Standard Investment Report (which also contains the Data Center ID field). Will the two Data Center ID fields be treated differently? Or, will there be a convergence, where both fields are submitted in table format (multiple <DataCenterID> nodes underneath a <DataCenterInventory> node?

**Comment by GihaVillazon** [comment]
Hi Ryan, 

Please refer to below link for Data Center ID field within the AITPS 
https://github.com/austin-moffa/ITDB-schema/blob/master/draftBY19/ITBudget/Examples/update-ITBudget-request.xml

Hope this helps. 

Thank you,

**Comment by rydougherty** [comment]
Thanks for the response. Can you please confirm that you are asking us to submit the same field, Data Center ID, two different ways, one way for the AITPS and one way for the Data Center Investment Report?

**Comment by GihaVillazon** [comment]
Yes, that is correct. AITPS will collect only the Data Center IDs, and the Investment Report will collect related elements to the data center investment. 

Thank You
