### ISSUE TITLE
IT Dashboard Prevents Delivery SIR Submission

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#285]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: We are receiving the following error back when attempting an add operation for a Delivery Investment: `          <error>000483-SIR: The UII (011-000880003) could not be found, is not active, or does not have type="05"  (Currently:  05) and PartOfExhibit="03"  (Currently:  03), and an InfrastructureManagementCategory in (02, 04, 05, 06, 07, 08). (Currently:  09)</error>`

A Delivery SIR will have InfrastructureManagementCategory = 09, so this validation should be adjusted to allow 09.

**Comment by austin-moffa** [comment]
This is being fixed as part of 08A sprint. Our ticket numbers are 1882/1884.

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
Both tickets were deployed on 8/12. Can you confirm this issue is resolved?
