### ISSUE TITLE
Operational Analysis Operation Node SIR

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#288]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: How should we handle the operation node for the SIR operational analysis section? The first time we submit an investment, we can submit `<operation>add</operation>` , however, in subsequent submissions should we submit add or update when operational analysis data changes? Considering there is no identifier attached to individual OAs, my assumption would be to always submit `<operation>update</operation>` for all submissions except the very first.

**Comment by courtneycorwin** [comment]
This was the question I brought up over the phone during our last meeting. I believe the action item was that they were going to remove the add/update for that node.  I have it in my notes to follow up on the next call. 

I should have put it on github to track after the meeting.  Sorry about that!

**Comment by jeremiah-tcg** [comment]
Created ticket ITD-1899 for this issue. This will be released with our 2018.08B deployment.

**Comment by Felicha** [comment]
OMB currently does not require Operational Analysis for Standard Investments.  Will the ITDB schema mandate OA fields for SIRs?  Concerned that mandating OA fields for SIRs will cause validation failures because OA information may not be available (or applicable) for Standard Investments.

**Comment by jeremiah-tcg** [comment]
Operational Analysis is added as an optional section for Delivery and Network SIRs. OA fields are not set as mandatory.

**Comment by jeremiah-tcg** [comment]
Courtney/Ryan - 2018.08B was deployed to UAT. Please let us know if this is resolved.
