### ISSUE TITLE
Internal Server Error Submitting Major Business Case

### ISSUE THREAD

**Issue by kengineer** [ombegov/ITDB-schema#289]
We were attempting to test the submission of the major business case against the https://myuat-2020.itdashboard.gov/api/v1/businesscase environment and received an "Internal Server Error" message when we submitted the following request.

```xml
<operations xmlns:businessCase-add="urn:us:gov:businessCase-add" xmlns:businessCase-update="urn:us:gov:businessCase-update" validateOnlyIndicator="true" xmlns="http://www.itdashboard.gov/service">
    <investmentInformation uniqueInvestmentIdentifier="429-000002500">
        <annualSubmission>
            <updateInvestment id="16">
                <businessCase-update:capitalAssetPlan>
                   <businessCase-update:capitalAssetSummary>
                        <businessCase-update:agency>429</businessCase-update:agency>                        `
                    </businessCase-update:capitalAssetSummary>
                </businessCase-update:capitalAssetPlan>
            </updateInvestment>
        </annualSubmission>
    </investmentInformation>
</operations>
```

This is actually a pared down request from what we originally tried to submit. We tried to isolate any specific piece of the submission that was causing the problem, but couldn't find anything specific.

The actual error returned was:

```javascript
{"ok":false,"error":true,"metadata":null,"httpStatusCode":500,"httpStatusMessage":"Internal Server Error","responseTime":0.08378005027771,"result":"The server encountered an unexpected error. Please try again."}
```

**Comment by jeremiah-tcg** [comment]
Can you try the submission again and let us know if you encounter the same error? We haven't been able to replicate this on our end as of yet.

**Comment by jeremiah-tcg** [comment]
We created ITD-1898 for this issue and will be deploying a Hotfix for it this week. Tag is 2018.08A.Hotfix.1

**Comment by jeremiah-tcg** [comment]
The fix has been deployed. Can you confirm this is no longer an issue?

**Comment by kengineer** [comment]
I tried with my abbreviated request above and I no longer get an internal server error. When I get a chance to try a full submission, I'll let you know how it goes, but so far, looking promising.

**Comment by elliotyoon202** [comment]
Hello,
Please let us know if this issue can be closed or if you're still experiencing this issue.

-Elliot

**Comment by kengineer** [comment]
You can close this issue
