### ISSUE TITLE
Number of Required Performance Metrics for Standard IT Investment Reports

### ISSUE THREAD

**Issue by danielwyork** [ombegov/ITDB-schema#29]
**Name:** Daniel York
**Organization:** GSA, eCPIC PMO
**Urgency:** Medium 
**Description of Issue:** The 95% FY19 IT Budget Guidance states that Network and End User Standard Investment Reports must provide a minimum of five performance metrics. In a Q&Z session with agencies, members of OMB OFCIO have said that it was OMB's intent not to set a required number of performance metrics for the Network and End User Standard Investment Reports. Will the v.1.9 xsd release candidate (set to be released on July 5th) include any requirements for the Network and End User Standard Investment Reports to have any number of performance metrics aligned to of of the Performance Measurement Categories?

**Comment by ojedanico** [comment]
As discussed in the whiteboard session June 29th the minimum on performance metrics had been lifted and updated in the current draft of the guidance.
