### ISSUE TITLE
Contracts Report Operations Node

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#291]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: Is OMB planning on removing the `<operation>` node from the Contracts Report? Given there are no PIID identifiers, each submission operation would always act as an update.

Similar to #288

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
Yes, we are planning to remove the operation node for the Contracts Report. This is tracked in ticket ITD-1899 and will be released with our 2018.08B deployment.

**Comment by rydougherty** [comment]
Thanks Jeremiah- the issue appears to be resolved
