### ISSUE TITLE
IT Dashboard Erroneously Triggering Structure ID Error for SIRs

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#294]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High, critical blocker
Description of Issue: I am unable to submit Project Activities to the Investment Report End Point. The validation error below is triggered even when the Structure ID node is included in my request file.

> 000581-SIR: structureID is a required field and cannot be blank or omitted when isAgile="N".

ITDB Response:

`      <projects>
        <project>
          <operation>add</operation>
          <uniqueProjectID>B</uniqueProjectID>
          <projectName>Wireless Project</projectName>
          <objective>Accelerated success</objective>
          <projectStartDate>2011-04-14</projectStartDate>
          <projectCompletionDate>2019-10-11</projectCompletionDate>
          <lifeCycleCost>3.9</lifeCycleCost>
          <SDLCMethodology>2</SDLCMethodology>
          <releaseEverySixMo>N/A</releaseEverySixMo>
          <releaseEverySixMoComment>test</releaseEverySixMoComment>
          <productionDeploymentDate>2018-07-11</productionDeploymentDate>
          <fundedBy>IT WCF</fundedBy>
          <commercialSolutionsCosts>3</commercialSolutionsCosts>
          <commercialSolutionsAdoption>1</commercialSolutionsAdoption>
          <commercialSolutionsReasoning>2</commercialSolutionsReasoning>
          <activities>
            <activity>
              <operation>add</operation>
              <isAgile>N</isAgile>
              <activityName>Test</activityName>
              <activityDescription>Test Activity</activityDescription>
              <structureID>B.10</structureID>
              <startDatePlanned>2018-08-07</startDatePlanned>
              <startDateProjected>2018-08-07</startDateProjected>
              <startDateActual>2018-08-01</startDateActual>
              <completionDatePlanned>2018-08-15</completionDatePlanned>
              <completionDateProjected>2018-08-21</completionDateProjected>
              <completionDateActual>2018-08-13</completionDateActual>
              <totalCostPlanned>0.013</totalCostPlanned>
              <totalCostProjected>0.017</totalCostProjected>
              <totalCostActual>0.013</totalCostActual>
              <ErrorsAndWarnings>
                <errors>
                  <error>000581-SIR: structureID is a required field and cannot be blank or omitted when isAgile="N".</error>
                </errors>`

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
This should be resolved with our next deployment (2018.08B).
