### ISSUE TITLE
Updated Schema for Week of 6/26

### ISSUE THREAD

**Issue by alex-unger** [ombegov/ITDB-schema#30]
Name: Alex Unger
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: Is OMB still planning to post an updated schema this week?  On last weeks ITDB Developers call, it was said that there'd be an updated schema posted each Monday evening.

**Comment by GihaVillazon** [comment]
We apology for missing this week’s weekly push. We ran into some issues in our attempt to automate our process for posting to GitHub. We believe we have fixed the issue moving forward. Please see the new push posted today. Please bear with us as we improve our processes to better serve the community. 

Thank You,
