### ISSUE TITLE
Error Received When Updated ASO/APGs

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#305]
Priority: HIGH

When updating the ASO/APG NID using an existing agencyID, I'm getting the following error:

000493-BCD: The investment objectiveOrGoal (5221) is currently associated with an open performance metric (7597) and cannot be deactivated/changed.  

I think we've discussed several times why this is an issue, so I won't re-explain that here.  It's preventing us from completing our testing - can you let me know when it will be resolved?

Thanks!
Courtney

**Comment by elliotyoon202** [comment]
Hello Courtney, 

Can you please send us the test file that you are using to MBX.OMB.ITDASHBOARD@omb.eop.gov so that we can better investigate this issue?

-Elliot

**Comment by courtneycorwin** [comment]
Hi Elliot,

I will send the test file, but I just want to reiterate that we've discussed our concern with this issue.  
Currently, in order to add a new ASO/APG to a Performance Metric, we have to add the ASO/APG, and submit the investment.  Then we have to add the ASO/APG to the Metric (because we can't add ASO/APGs that aren't already in the list), submit it. And then we can deactivate the ASO/APG.  So, three submissions in total.

Since the codes have changed, we are just updating the codes we're using (reusing the same agencyID as previously discussed).  So, in this case, 5221 is no longer a valid ASO/APG ID and we're updating it with the proper 11 character code.  We should not have to deactivate it or disassociate it from Performance Metrics in order to do so.   If that's the case, each MITBC will require 3 submissions.

**Comment by courtneycorwin** [comment]
And, as I reread this, even if we did 3 submission still would not work since the 5221 ASO/APG ID is no longer valid so the submission would be rejected if we tried to include it.  I believe the solution was to wipe out all of the existing ASO/APG records so they would all go up as adds and we can reuse our agencyIDs.

Regardless, we still need to work on the overall process of updating ASO/APGs going forward so we can avoid the scenario in the post above.

**Comment by courtneycorwin** [comment]
Hello All,

Can I please have a date as to when the ASO/APG records are going to be removed from the dashboard? Some agencies have employed a workaround where they are just adding new records instead of updating the existing records with the new 11-character codes, but I'm not a fan of this since it means if the original ASO/APG records aren't removed, it will result in both sets of ASO/APGs existing in the business case.

**Comment by elliotyoon202** [comment]
Hi Courtney,

The UAT database investmentObjectiveOrGoal table has been truncated, so users have to add new objectiveOrGoal values to the database as there is nothing to update. Users will not be able to reuse agencyObjectiveOrGoalID as those values are in the audit table for the purged records. Users are able to update the performance metrics, reusing the agencyPerformanceMetricId with the new performanceMetricObjectiveOrGoal.

**Comment by courtneycorwin** [comment]
HI Elliot,

What was agreed to was that we would be able to reuse our existing IDs (in our case, agencyIDs).  During one of our meetings, your team agreed that the record would be purged and, that while all submissions would go up as "Add", we could reuse our existing IDs.

**Comment by barrypannell** [comment]
I have the same issue.  Courtney's understanding is my recollection of the discussion as well.

**Comment by elliotyoon202** [comment]
Courtney and Barry,

I've talked with out team and have found way so that the validation would not find a match and that existing IDs can be reused.

I'll circle back with when this change will be deployed.

**Comment by elliotyoon202** [comment]
Good Morning - 

To follow up, we are planning on deploying a fix for this today.

-Elliot

**Comment by courtneycorwin** [comment]
Thank you for the update!

**Comment by elliotyoon202** [comment]
The fix should now be on UAT - Please see if this has fixed the issue.

**Comment by courtneycorwin** [comment]
Confirmed.  Thank you!

**Comment by courtneycorwin** [comment]
Hi All,

We are getting this error again.  We have a 5 digit goal ID that is being updated to the appropriate 11-character value.  However the error received is that we can't update the goal ID because it's associated with a performance metric.

This had been fixed last week, so maybe something undid it?  Please let me know if you want to see the submission files.

**Comment by courtneycorwin** [comment]
Hi Jeremiah,

I've sent over the files for your review.  Upon additional investigation, the error isn't quite what I thought it was given the error message returned by OMB.  I've sent you three files:

Hi All,

Here are the files I think are pertinent to Issue #305 – the error issue a bit different than I originally thought, but this is an extremely high issue for us.  The attached files are as follows:

1.	Input_to_OMB – this is the file sent to OMB.  The file was sent as updateInvestment and the ASO/APG in question was also sent as an update because of its presence in the Output_from_OMB file.

2.	Output_from_OMB – this is OMB’s response to getInvestment – you’ll see there is one active ObjectiveorGoal with an 11-character ID valid for BY20.  At some point, the business case for the investment must have actually been submitted to the UAT site vs. validated.

3.	Errors_from_OMB – these are the errors returned based on the input file.  The error message returned here is “000493-BCD: The investment objectiveOrGoal (45542) is currently associated with an open performance metric (24004) and cannot be deactivated/changed”.  However, as you’ll see in the input file, there is no objectiveOrGoal with an ID of 45542 (a valid BY19 goal that is not valid for BY20).  That Goal ID is still associated with a Performance Metric because we submit the details separately.  So, the error message is, essentially, referencing an objectiveOrGoal that no longer exists.  

Thanks for helping to resolve this!
Courtney

**Comment by courtneycorwin** [comment]
The instructions from OMB worked for us on this. You can go ahead and close the ticket.  Thanks!!
