### ISSUE TITLE
Submission Confirmation Questions

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#306]
Just a couple of questions regarding this:

1. How will this affect the PBGC/Labor submission?  If PBGC submits a confirmation, how will that affect Labor's submission (and vice versa)?

2. Are the validations this will be checking active in UAT?

3. If agencies submit a confirmation in UAT, will they need to contact you to "undo" the confirmation to continue general testing?  For example, several agencies test their ITPS and MITBC in pieces and will probably want to test the confirmation in a similar fashion.

**Comment by elliotyoon202** [comment]
Hi Courtney, 

Please see our answers to your questions below.
1. We recommend that PBGC and DOL coordinate across their agencies before they complete the submission confirmation process.
2.      The validations checked during UAT are:
•	All Majors must have business cases
•	Contracts Reports must be submitted for Part 3s and Majors 
•	Standard Investments for End User, Security, Network, and Data Center/Cloud must have Investment Reports Attached
3.     There is currently no lock in place, so submitting a confirmation during UAT will not lock things for testing, so OMB will not have to “undo” the confirmation.

-Elliot

**Comment by courtneycorwin** [comment]
Hi Elliot,

Thanks for the answers. #2 and #3 work just fine for me (I appreciate you're not locking anything down in UAT).

I don't think #1 is feasible.  The two agencies have not had to coordinate their submissions in the 10 years I've been working with them.  I will let PBGC know (and Kelly and/or Wil should reach out to both PBGC and Labor) but, I think you will get a lot of push back.

**Comment by elliotyoon202** [comment]
Hi Courtney,

Thanks for the feedback on #1 - we will escalate this to folks here at OMB to see what we might be able to work out.

**Comment by courtneycorwin** [comment]
Great.  In the meantime, I've sent PBGC a heads up on your recommendation and I've recommended they contact their desk officer if coordinating isn't a possibility.  Who knows, maybe it won't be so bad.

**Comment by courtneycorwin** [comment]
Hello All,

It seems a meeting at 10:30am on Tuesday is being set up to finalize the plan for this. My understanding is that for this annual submission PBGC and DOL will coordinate their submissions.  However, it's been requested that this be a temporary solution and that a more permanent one that will allow PBGC to continue to submit independent of DOL be implemented in time for passback.

**Comment by jeremiah-tcg** [comment]
HI All, 

A meeting between PBGC, DOL, and OMB occurred today at 9AM. Per the discussion, PBGC and DOL agreed to coordinate during the predecisional annual submission period to complete the submission confirmation process. At this time, the same level of coordination between both agencies is expected during the passback submission period.

Regards, 
Jeremiah
