### ISSUE TITLE
Review Submissions Not Distinguishing Errors and Warnings

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#307]
When submitting an IT Budget file (and I believe but have not fully tested it applies to other types,) the "Review Submissions" page, "Summary" link does not indicate which issues are errors and which are warnings.  (Even providing the "ResponseInformationLevel" value could be sufficient.)  A recent submission has the link labeled "Unsuccessful 2 errors 22 warnings", however, when I click on it, I just see a list of 24 items, with no designation of which is which.

This is now a higher priority issue for us due to the following response we are receiving when submitting XML via myuat.itdashboard.gov:

•alertIT Budget submission failed◦Overall IT Budget Portfolio: 
alert000226-ITP: The submission is too large to process in a timely fashion, please check back in a few minutes

It appears the site is being more aggressive about timing out, which would be fine, except for the above issue.  In past years, our IT Budget submissions essentially never timed out, and the immediate response did distinguish between warnings and errors.  So, while I believe this is not a new issue, it was previously (at least for us) a minor issue because we could re-submit if needed to generate the errors and warnings.  As such, an alternative solution would be to restore the timeout settings.

**Comment by elliotyoon202** [comment]
Hi Bill,

To address your concerns:
- We look into adding in distinguising the errors and warnings. (Internal tracking: ITD-1932)
- We will investigate the issue that you are having with timing out. It could potentially be because it is in UAT, but we will confirm (Internal tracking: ITD-1933)

**Comment by bill-gehrke-hhs** [comment]
Thanks for the response.  To add a little more detail on the timeout issue since you logged a ticket for it - UAT could certainly be a part of the issue, as I have seen that in the past.  However, the timeout response is definitely occurring far more quickly than in the past (on UAT or production.)  Additionally, I noted that when I submitted nearly the identical file (with the 2 errors corrected,) I did not receive a timeout message but a success message (and, as a note, per issue #277, the warnings were not displayed.)  While it certainly may take longer to generate the errors/warnings, it seems like the timeout message is coming at very nearly the same amount of time as the success message with the only difference being whether there were errors or not.

**Comment by elliotyoon202** [comment]
Thanks Bill - I've add the additional details to the ticket

**Comment by jeremiah-tcg** [comment]
Hi Bill, 
The timeout issue should be resolved at this time, given our 2018.09A push on Friday. Please let us know if that one is still an issue.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment]
Hi Bill, 
We deployed a fix to distinguish the errors and warnings on 10/3. Please let us know if we can close this ticket.

Regards, 
Jeremiah

**Comment by elliotyoon202** [comment]
Hi Bill,
Please let us know if this issue can be closed or if you're still experiencing this issue.

-Elliot

**Comment by cegan2133** [comment]
Hi Bill, we are closing this issue, as it was resolved by the previous vendor. Please let us know if you have any follow-up questions or issues related to this item.
