### ISSUE TITLE
Agency System ID Required

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#308]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High, blocker
Description of Issue: The IT Dashboard returns a server error when I do not submit the Agency System ID node during an Add System Operation. This server error prevents us from utilizing OMB assigned System IDs.

Request:
`<systems validateOnlyIndicator="true">
    <system>
        <operation>add</operation>
        <details>
            <UII>011-000002616</UII>
            
            <systemName>250 Name</systemName>
            <averageUsersPerMonth>120</averageUsersPerMonth>
            <initialOperatingYear>1999</initialOperatingYear>
        </details>
        <products>
            <product>
                <operation>add</operation>
                
                <productName>250 Char Product Name</productName>
                <vendorName>250 Char Vendor Name</vendorName>
                <versionNumber>1.1.0</versionNumber>
                <lastMajorTechRefresh>12-2012</lastMajorTechRefresh>
                <anticipatedTechRefresh>01-2013</anticipatedTechRefresh>
                <endOfContractedSupport>11-2019</endOfContractedSupport>
                <productExpectEndOfLife>N/A</productExpectEndOfLife>
                <productFunctions>
                    <productFunction>FFM.010</productFunction>
                    <productFunction>FFM.020</productFunction>
                    <productFunction>FFM.030</productFunction>
                </productFunctions>
            </product>
        </products>
    </system>
</systems>`

Response:
`{
    "ok": false,
    "error": true,
    "metadata": null,
    "httpStatusCode": 500,
    "httpStatusMessage": "Internal Server Error",
    "responseTime": 0.047607898712158,
    "result": null,
    "errors": [
        {
            "code": 8,
            "message": "Undefined index: agencySystemsInventoryID",
            "severity": 0,
            "file": "/services/sEgvHttpP/server/20/htdocs/api/Pittsburgh/Controllers/ITDB2/SystemsInventory/validations/SystemsInventoryDetailsValidator.php",
            "line": 27
        }
    ]
}`

**Comment by elliotyoon202** [comment]
Hi Ryan, we've started looking into this.

ITD-1931 (Internal Tracking)

**Comment by rydougherty** [comment]
Hi- do you have an ETA for when this item will be deployed to the UAT Dashboard?

**Comment by elliotyoon202** [comment]
Hi Ryan,

We're currently testing this and our best estimate right now for deployment is Friday (8/31), if not sooner.

-Elliot

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
We deployed 2018.09A to UAT which included a fix for this. Please us know if the issue is now resolved.
Regards, 
Jeremiah

**Comment by rydougherty** [comment]
Hi Jeremiah, the server error appears to be resolved but we are encountering a validation error upon submission that is preventing us from adding new systems/products. Essentially when we go to submit, the products I am attempting to add are returned with blank nodes, and I receive the following error:

> ERROR: timePeriodID: 19 does not exist for insert

When I set the validateOnlyIndicator to true, everything works fine.

Request File:

`<?xml version="1.0" encoding="UTF-8"?><systems validateOnlyIndicator="false"><system><operation>add</operation><details><UII>011-000002616</UII><systemName>System 3</systemName><averageUsersPerMonth>55</averageUsersPerMonth><initialOperatingYear>2000</initialOperatingYear></details><products><product><operation>add</operation><productName>Office v2</productName><vendorName>Zone v2</vendorName><versionNumber>2.0</versionNumber><lastMajorTechRefresh>07-2018</lastMajorTechRefresh><anticipatedTechRefresh>06-2018</anticipatedTechRefresh><endOfContractedSupport>05-2018</endOfContractedSupport><productExpectEndOfLife>04-2018</productExpectEndOfLife></product></products></system></systems>`

Response:

`<?xml version="1.0"?>
<SystemsInventoryListResponse>
  <systems>
    <system>
      <operation>add</operation>
      <details>
        <UII>011-000002616</UII>
        <systemName>System 3</systemName>
        <averageUsersPerMonth>55</averageUsersPerMonth>
        <initialOperatingYear>2000</initialOperatingYear>
        <systemsInventoryID/>
      </details>
      <products>
        <product>
          <operation>add</operation>
          <productName/>
          <vendorName/>
          <versionNumber/>
          <lastMajorTechRefresh/>
          <anticipatedTechRefresh/>
          <endOfContractedSupport/>
          <productExpectEndOfLife/>
          <productID/>
        </product>
      </products>
      <status>Submission Failed</status>
    </system>
  </systems>
  <response>
    <system>
      <details>
        <UII>011-000002616</UII>
      </details>
      <products>
        <product/>
      </products>
      <CriticalErrors>
        <errors>
          <error>ERROR: timePeriodID: 19 does not exist for insert</error>
        </errors>
      </CriticalErrors>
      <status>Submission Failed</status>
    </system>
  </response>
</SystemsInventoryListResponse>`

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
We believe this may be due to the data rebaseline which took place on 9/1. We think you'll have to submit the IT Portfolio first before you can test the Portfolio Details sections. Please let us know if you encounter the same error after the IT Portfolio is submitted for this UII.
Regards, 
Jeremiah

**Comment by rydougherty** [comment]
Hi Jeremiah- looks like that did the trick. We are good to go with this item now.
