### ISSUE TITLE
IT Security & Compliance Towers Validations

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#310]
There are several validations related to IT Security & Compliance Towers saying that type 4 investments cannot submit a value greater than zero for PY, CY, or BY amounts.  FAA has just received guidance that these validations are no longer valid and will be removed from the UAT environment.

Can you please confirm that the validations are no longer valid and let me know what date  you expect the validations to be removed?  Thanks!

**Comment by courtneycorwin** [comment]
Hi Jeremiah,

I am being pushed for a date on this - it's preventing agencies from submitting a valid ITPS which, as you know, has a domino effect.

Thanks!

**Comment by jeremiah-tcg** [comment]
Hi Courtney, 

We just implemented this manually on UAT a few minutes ago. Please let me know if we can close this issue.

Regards, 
Jeremiah

**Comment by courtneycorwin** [comment]
Verified - thanks for the fix!

Courtney
