### ISSUE TITLE
SIL Product Functions Format

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#315]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High, Blocker
Description of Issue: The IT Dashboard is returning Product Functions in an odd format. When I send multiple Product Fundinctions the values are returned in the following format for the Get Response and the Submissions Response: `<productFunctions>FFM.010|FFM.020|FFM.030</productFunctions>`. The XSD indicates that Product Functions will be displayed in the following format in response files: 

` <productFunctions>
                        <productFunction>
                            <productFunction>FFM.010</productFunction>
                            <productFunction>FFM.020</productFunction>
                            <productFunction>FFM.030</productFunction>
                        </productFunction>
                    </productFunctions>` 

This format doesn't look quite right either. I believe the extra `<productFunction>` node should be dropped.

**Comment by elliotyoon202** [comment]
ITD-1657 (Internal Tracking)

**Comment by rydougherty** [comment]
Hi- do you have an ETA for when this item will be deployed to UAT?

**Comment by elliotyoon202** [comment]
Hi Ryan,

We're currently testing this and our best estimate right now for deployment is Friday (8/31), if not sooner.

-Elliot

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
We deployed 2018.09A to UAT which included a fix for this. Please us know if the issue is now resolved.
Regards, 
Jeremiah

**Comment by rydougherty** [comment]
Thanks Jeremiah, this is working for us now.
