### ISSUE TITLE
productionDeploymentDate SIR vs MITBC

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#317]
Hi All,

Just to follow up on the question I brought up in today's meeting:

On the SIR (#870-SIR), the productionDeploymentDate is looking for an MM-YYYY format with an N/A option.

In the MITBC, there's no specific validation related to it, but historically, it's been YYYY-MM-DD with no N/A option.

I'd like to confirm that data allowed in this tag will remain consistent with the MITBC rules.  Thanks!

**Comment by jeremiah-tcg** [comment]
Hi Courtney, 

We've decided to remove the 000870-SIR validation to ensure the data allowed is consistent with MITBC rules. We will update the BY20 Application Validations document to show the validation as removed shortly.
Regards, 
Jeremiah

**Comment by courtneycorwin** [comment]
Perfect!  Thank you!

**Comment by jeremiah-tcg** [comment]
So all are aware, this validation no longer exists in the code. We are making several updates to the validation spreadsheet one of which will reflect the removal of the 000870-SIR validation.

**Comment by courtneycorwin** [comment]
Provided that in the case of both the SIR and the business case that this is required to be a full date with no N/A option, then I'm good with closing this ticket.  Thanks!

**Comment by jeremiah-tcg** [comment]
Hi Courtney, 
We checked this. Here's what was found:
Verified – The following formats are allowed: MM-DD-YYYY, MM/DD/YYYY, YYYY-MM-DD
Verified – The following are not allowed: MM-YYYY, "N/A"
Regards, 
Jeremiah
