### ISSUE TITLE
End User and Data Center Cost Codes

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#319]
Could the cost codes for the End User and Data Center & Cloud Standard Investment Reports be added to the Data Dictionary Enumerations Excel file?  Worksheets exist for Network, Application, and Delivery, but not these.  (And it might be just as simple to have one worksheet for all of the cost codes rather than 5.)

As far as I can tell, there is no change in these codes since last year, so this is a minor issue, but it would be helpful to have all of these codes documented there rather than just some to avoid any possible ambiguity.

**Comment by elliotyoon202** [comment]
Hi Bill,

Can you clarify what you mean by cost codes? We should be able to add anything to the data dictionary that you'd find useful.

-Elliot

**Comment by bill-gehrke-hhs** [comment]
The Enumerationx Excel file has worksheets named "Network Investment Types", "Application Investment Types", and "Delivery Investment Types".  There should be equivalent worksheets for End User and for Data Center & Cloud.  And while they are referred to in the Excel at "Types", they are more specifically cost type codes since they relate to the investment cost detail.

**Comment by jeremiah-tcg** [comment]
Hi Bill, 
I just created a pull request #323 for this. You should see it updated momentarily. If satisfied, please let us know if we can close this issue.
Regards, 
Jeremiah

**Comment by bill-gehrke-hhs** [comment]
Thanks - the updated Excel file includes the requested codes.
