### ISSUE TITLE
Working Whiteboard session topics

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#32]
At the session today I would like to spend some time on talking through 'transition' issues from the previous investments submitted to the new submissions.  
Can old infrastructure investments be categorized as standard infrastructure?   Are standard infrastructure investments expected to get new UIIs?  What is the status change from an existing investment broken into standard infrastructure investments?  What happens to their 'old' projects and performance measures?  

On projects, 'old' closed projects that are closed, will they need to update their SDLC to the new values?   Will old values be grandfathered/retained?  What if I need to submit a correction later for a project for an actual cost or actual date?  Will the SDLC validation flag? 

These are the type of questions that can come up after basic new/update investment testing.

**Comment by GihaVillazon** [comment]
Please let us know if there are any outstanding questions/concerns which were not discussed in the whiteboard session. 

Thank You.

**Comment by GihaVillazon-REISys** [comment]
For any investment that is the same, retains UII. 

For one to one relationships (existing investment = standard investment), use same UII.

When fully transitioning an existing investment to create new investments, use new UIIs.

If a large part of an existing investment transitions to a standard investment, UII can be maintained, anything reflected in a new investment then assign a new UII.
