### ISSUE TITLE
SIR Funded By Required

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#320]
Is there a reason the funded by field is required for SIR projects?  To provide flexibility, my understanding is that the SIR fields would be optional.  All other "project detail" fields except project name (which makes sense as to be required) are optional.  This includes start and end date, total cost, and the similar dropdown for SDLC Methodology.  It is also worth noting that N/A is not the same as not responding/null since it indicates an affirmative statement that the project is not funded by a TMF or WCF.

I would expect that 000653-SIR would be set as a warning and that all of the errors related to commercial solutions (which included 000650-SIR, 651-SIR, 652-SIR and possibly others) would be warnings to be consistent with the warnings for things like missing start and end dates in the SIR.

**Comment by jeremiah-tcg** [comment]
Hi Bill, 
We were previously informed this particular field would be required by OMB. We have escalated this to our POCs at OMB to clarify their intent.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment]
Hi Bill, 
Received an answer on this after following up today. OMB recognizes this would be a tedious exercise during the initial submission, but stressed a need to confirm that every project either is or is not funded by TMF or IT Mod WCF, including SIRs. As a result, the field will remain required for investments that are required to submit the project sections.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment]
Per our discussion at the 9/13 CPIC Vendor meeting, closing this issue.
