### ISSUE TITLE
Mission Area Reference Table

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#33]
Name: Ryan Dougherty
Organization: eCPIC PMO (BAH)
Urgency: Medium
Description of Issue: The Mission Delivery and Management Support Area Field in the Guidance states:

"Mission Delivery and Management Support Area [2-digit code] (variable element)
These two digits indicate the mission delivery and management support areas. Agencies should assign a unique code for each mission delivery and management support area reported. Agencies shall provide a reference table for mission areas to the ITDB to include:
o Agency Code [3-digits]
o Mission Delivery and Management Support Area [2-digit code]
o Description [500 characters]"

The guidance doesn't indicate how this will be provided to OMB this year. Will Agencies email it to their desk officers like they did last year? The reference table requirements make it appear as though it will be submitted electronically, but it does not appear in the draft schema.
Associated Links: None

**Comment by GihaVillazon** [comment]
Yes, Please continue with the same process.
