### ISSUE TITLE
Covered Entities Data Erased Following Submissions

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#330]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium, no technical blockers but Agency data issue
Description of Issue: We are noticing that the IT Dashboard is either erasing, or incorrectly returning, Covered Entities Data for a given SOC following an unrelated submission. If I update a SOC node and leave the Covered Entities node untouched (dropped from my request file), then the ensuing Get Response from the IT Dashboard only returns a single Covered Entity for that SOC. 

I will email the request and response files that demo this issue to the Help Desk soon.

**Comment by elliotyoon202** [comment]
ITD-2005 (Internal Tracking)

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
We deployed a fix for this in our 2018.09B.Hotfix.1 deployment last night. Please let us know if this issue is now resolved for you.
Regards, 
Jeremiah

**Comment by elliotyoon202** [comment]
Hi Ryan,
Please let us know if this issue can be closed or if you're still experiencing this issue.

-Elliot

**Comment by rydougherty** [comment]
Hi Elliot, yes you can close this issue
