### ISSUE TITLE
IT Dashboard Blocking Valid Budget Code

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#331]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High, Agency Reported Issue
Description: One of our Agencies has reported that the IT Dashboard is returning the following validation error: 

> `<response-ITBudget-ext:ResponseInformation>
                <response-ITBudget-ext:ResponseInformationLevel>1</response-ITBudget-ext:ResponseInformationLevel>
                <response-ITBudget-ext:ResponseLogDescription>000075-ITP: Funding Code provided "029-40-0151" is not active </response-ITBudget-ext:ResponseLogDescription>
            </response-ITBudget-ext:ResponseInformation>`

029-40-0151 is  valid code per the most recent copy of the data dictionary.

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
The Master Account Table, which is the IT Dashboard's data source, now shows this code as being inactive. We updated our reference table with this information last night, but the update to the Data Dictionary has not been made yet. Will have the pull request that includes the document update routed through GitHub this evening. 
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
We updated the Data Dictionary document on GitHub on 9/10. Please let me know if we can close this ticket.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment]
Per our discussion at the 9/13 CPIC Vendor meeting, closing this issue.
