### ISSUE TITLE
Old ASO/APG Codes Appearing in Production Get Responses

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#333]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Critical, Blocking Agency Submissions
Description of Issue: We have multiple Agencies reporting that the old Goal Codes are still aligned with Performance Metrics on the IT Dashboard. I have posted the error that Agencies are receiving below. I know the old Goal Codes were cleared out of the UAT Database, but were these codes also cleared from Production?

> `<sr:messagelevel="error" xpath="/tns:operations[1]/tns:investmentInformation[1]/tns:annualSubmission[1]/tns:updateInvestment[1]">000493-BCD: The investment objectiveOrGoal (1017) is currently associated with an open performance metric (26398) and cannot be deactivated/changed</sr:message>`

**Comment by lhornung** [comment]
All the ASO/APG IDs we have for each agency will show in the ref-ASO/APG data feed. Agencies should let us know if they have an ID that does not exist in our system. Another reason for invalid code errors is to use an ASO/APG ID for a metric when the ASO/APG ID is not added and submitted for the business case yet in the updatedInvestment file.

**Comment by jeremiah-tcg** [comment]
The Data Change to drop the old goal codes from the performance metrics was deployed yesterday. Please let us know if we can close this ticket.

**Comment by elliotyoon202** [comment]
Hi Ryan,
Please let us know if this issue can be closed or if you're still experiencing this issue.

-Elliot

**Comment by rydougherty** [comment]
Hi Elliot, yes we were able to workaround this issue
