### ISSUE TITLE
ASO/APG Data Dictionary

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#334]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Critical, Blocking Agency Submissions
Description of Issue: Is the enumerations document up to date with the latest valid ASO/APG codes? We have several Agencies submitting codes that are listed on the enumerations document, but they are still receiving invalid code errors.

**Comment by lhornung** [comment]
All the ASO/APG IDs we have for each agency will show in the ref-ASO/APG data feed. Agencies should let us know if they have an ID that does not exist in our system. Another reason for invalid code errors is to use an ASO/APG ID for a metric when the  ASO/APG ID is not added and submitted for the business case yet in the updatedInvestment file.

**Comment by jeremiah-tcg** [comment]
This is ITD-2007. Since State and USAID share ASO/APG ID's, we will need to add records for USAID in our reference table. We plan to deploy a fix for this issue today.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment]
Hi Ryan, 
We just deployed the fix for this. Please let us know if we can close this ticket.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment]
Closing this ticket as it appears to be resolved in our db
