### ISSUE TITLE
Network Investment Requirements

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#335]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: What are the requirements for submitting Performance Metrics data for Network SIRs. Is at least one metric required only when that Network SIR has O&M funding? Or does the rule go in a different direction?

**Comment by lhornung** [comment]
Network and delivery SIRs should have at least one metric.

**Comment by jeremiah-tcg** [comment]
Closing issue per our discussion at yesterday's meeting.
