### ISSUE TITLE
SIR Project Validation with more than 9 activities 

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#336]
Name: Barry Pannell 
•Organization: DHS (MBC)
•Urgency: High 
•Description of Issue: 
Attempting to add a project (unique project id 1) to a new(add) Network infrastructure investment.
Project has 13 activities.  
Structure ID number goes 1.1 - 1.13.
All activities are at the same top level.  
No parentage defined in this project. 

Getting an error message saying activity 1.10 is in list twice.  
Also getting a warning saying that activity 1.1 is a parent activity (it is not - all activities at the top level) 

alert Submission Failed for UII 024-000005270

activities◦alert000886-SIR: structureID 1.10 occurs multiple times.

activities◦warning000892-SIR: Activity with structureID '1.1' is a parent activity which means the following submitted fields are overwritten by values derived from the children activities: (startDatePlanned, startDateProjected, startDateActual, completionDatePlanned, completionDateProjected, completionDateActual, totalCostPlanned, totalCostProjected, totalCostActual).

Appears structure ID may be getting padded to 2 characters making activity 1.1 convert to 1.10 thereby making it a duplicate. 
Another place it appears that 1.1 may be treated as a parent to 1.10-1.13 - which it is not.  

This is seen on another investment on 2 separate projects with same scenario.  

Will experiment with adjusting the structure ID.

**Comment by barrypannell** [comment]
My test to modify the structure IDs 1.1-1.9 to 1.01-1.09 was successful for one of the investments.  I expect it will work on the others.  This hopefully helps

**Comment by barrypannell** [comment]
Elliot –
I reviewed the 2 investments/3 projects impacted and discussed with Kim Kern.  We revised the activities for the 3 projects to use 2 digits for the structure ID (second level under project ID) for activities at this time.  That resolved the problem for now.
Thus the urgency is off now for us though I would suspect that it may come up soon for another DHS investment or another department/agency may encounter.
Barry

Barry Pannell
INVEST Support – OCIO EBMO
MBC Consulting
866-233-9904

**Comment by jeremiah-tcg** [comment]
The fix for this was deployed in the hotfix that went out today. Please let us know if this issue can be closed.

**Comment by elliotyoon202** [comment]
Hi Barry,
Please let us know if this issue can be closed or if you're still experiencing this issue.

-Elliot

**Comment by barrypannell** [comment]
We tested this issue out earlier in December.  It is resolved based on our test.  Meant to report at last vendor call.

**Comment by cegan2133** [comment]
Hi Barry, we are closing this issue, as it was resolved by the previous vendor. Please let us know if you have any follow-up questions or issues related to this item.
