### ISSUE TITLE
Get Investment Internal Server Error

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#339]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: Do you have time frame for the resolution of the internal server following a Get Investment Request?

Request:
`<?xml version="1.0" encoding="UTF-8"?><tns:operations validateOnlyIndicator="false" xmlns:businessCase-update="urn:us:gov:businessCase-update" xmlns:businessCase-add="urn:us:gov:businessCase-add" xmlns:tns="http://www.itdashboard.gov/service" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><tns:investmentInformation uniqueInvestmentIdentifier="184-000000005"><tns:getInformation><tns:getInvestment id="b8225c8b-aa3d-4f6e-89ac-0a93434a525f" /></tns:getInformation></tns:investmentInformation></tns:operations>`

Response:
`"ok":false,"error":true,"metadata":null,"httpStatusCode":500,"httpStatusMessage":"Internal Server Error","responseTime":0.064803838729858,"result":null,"errors":[{"code":8,"message":"Undefined variable: monthlySubmission","severity":0,"file":"\/services\/sEgvHttpP\/server\/20\/htdocs\/api\/Pittsburgh\/Controllers\/ITDB2\/BusinessCase.php","line":382}]}`

**Comment by kpohland** [comment]
This is ITD-2066. 

-Kim

**Comment by elliotyoon202** [comment]
Hey Ryan,

We are aware of this issue and we're aiming to deploy sometime next week.

-Elliot
(ITD-2066)

**Comment by elliotyoon202** [comment]
Hi Courtney and Ryan,

The fix is planned on being deployed tonight.

-Elliot

**Comment by jeremiah-tcg** [comment]
The fix for this was deployed on 10/3. Please let us know if we can close this ticket.

**Comment by courtneycorwin** [comment]
Hi All,

I've tested this and it works for my agencies.   I would wait until Ryan has a chance to validate it before closing this ticket, but you can close whatever related ticket you have for me with the help desk.  

Thanks!
Courtney

**Comment by elliotyoon202** [comment]
Hi Ryan,
Please let us know if the issue was fixed with our deployment on 10/3 and if we can close this ticket.

Thanks,
Elliot
