### ISSUE TITLE
IT Budget CIO Authority Amount Validation Request

### ISSUE THREAD

**Issue by kengineer** [ombegov/ITDB-schema#341]
For next years IT Budget Submission, can you add some validation for the CIO Authority Amount field under Budget Account Summary that will let the submitter know if they value being submitted is off? For the other Budget Account Summary fields (e.g. Total Agency Funding, Total Agency Funding BY Budget Authority Amount, etc...) there is validation that lets the submitter know if the values submitted do line up with what was submitted in the IT Portfolio. It would be helpful to have similar validations for the CIO Authority Amount.

**Comment by elliotyoon202** [comment]
Hello. Thank you for your suggestion. We will forward on this suggestion to the appropriate team and will consider adding this functionality in the future.
