### ISSUE TITLE
Target Date for XSD Candidate (v1.9.0) shared to vendors

### ISSUE THREAD

**Issue by alex-unger** [ombegov/ITDB-schema#38]
Name: Alex Unger
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue:  I wanted to check in to see the timeframe in which the XSD Candidate (v1.9.0) will be committed to Github?

**Comment by GihaVillazon** [comment]
Hi Alex,

Past Monday there were no updates to the schemas, however COB Monday 10th of July we will have an updated version published in GitHub. 

Thank you.

**Comment by alex-unger** [comment]
Are the schemas currently in use by the myuat-2019 the ones currently available on Github?

**Comment by danielwyork** [comment]
@GihaVillazon, I think @alex-unger was talking about the XSD Candidate that was scheduled to be posted July 5th, not the weekly update. @ojedanico / @MitchellTCG can you please validate when vendors can access the XSD Candidate (v1.9.0) will be made available to vendors, or how we can access it now?

**Comment by GihaVillazon** [comment]
Yes they are. 
Thank you Daniel, We will have the XSD Candidate published on July 10th, which will be the closest version to the final schema. 

Thank You.

**Comment by danielwyork** [comment]
The Important Dates section of https://github.com/ombegov/ITDB-schema/blob/master/README.md#important-dates says the XSD Candidate was to be released on July 5th. @justgrimes please confirm the schedule slip.

**Comment by ojedanico** [comment]
We are working on the organization of the file structure to make this more user friendly. 

Thanks for your patience.

**Comment by alex-unger** [comment]
Thanks for posting the v1.90 schema!
