### ISSUE TITLE
Expiration of UAT Tokens

### ISSUE THREAD

**Issue by alex-unger** [ombegov/ITDB-schema#39]
Name: Alex Unger
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: Currently the MyUAT-2019.itdashboard.gov tokens have a 12 hour expiration.  Could the ITDB group extend the expiration of these UAT tokens to at least a week?

**Comment by ojedanico** [comment]
This is a question for MAX let me we look into it and see if they are willing to adjust the time to accommodate your request.

**Comment by GihaVillazon** [comment]
Hi All, 

We came across certain security issues related to extending the tokens, however we are still looking into it, will keep the community posted as we progress towards an answer. 

Thank You.

**Comment by GihaVillazon-REISys** [comment]
Hi All, 

The "Full Submission" tokens usually last **12 hours**, however for your convenience we have accommodated UAT tokens to expire after 7 days. The extension of tokens will be deployed July 31st. 

Thank You.
