### ISSUE TITLE
Internal Server Error on AITPS Submission

### ISSUE THREAD

**Issue by alex-unger** [ombegov/ITDB-schema#40]
Name: Alex Unger
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: When submitting an AITPS Request, the server error below is returned.  Note:  The XML validates successfully.  An email will be sent to the ITDB group with the XML request.

{
  "ok": false,
  "error": true,
  "metadata": null,
  "httpStatusCode": 500,
  "httpStatusMessage": "Internal Server Error",
  "responseTime": 0.60042214393616,
  "result": null,
  "errors": [
    {
      "code": 0,
      "message": "Fatal Error: Error inserting into itPortfolioTBMAudit table, Error inserting into itPortfolioAudit table"
    }
  ]
}

**Comment by GihaVillazon** [comment]
We are looking into this, will keep you posted. 

Thank You.

**Comment by GihaVillazon** [comment]
We have created a ticket to further investigate the issue.
https://egovjira.max.gov/jira/browse/ITD-631

Thank you.

**Comment by danielwyork** [comment]
@GihaVillazon - FYI only the TCG developers appear to have access to the JIRA link you provided. The rest of us get the below screen when we try to access it. 
![jira access denied](https://user-images.githubusercontent.com/18399925/27968542-683ea606-6315-11e7-82a3-711784f7f99c.PNG)

**Comment by GihaVillazon** [comment]
That is correct, only the internal team will have access sorry about the confusion. We just wanted to update the community that we are looking into it further. 

Thank You.

**Comment by alex-unger** [comment]
Hello ITDB group - I wanted to check in to see if there's any update on this issue?

**Comment by alex-unger** [comment]
Following up on this, we were finally able to obtain a token from one of our supported agencies, and it appears this error has been resolved.  Thanks!

**Comment by GihaVillazon-REISys** [comment]
Great!
