### ISSUE TITLE
Working Whiteboard 2nd Session Topics

### ISSUE THREAD

**Issue by GihaVillazon** [ombegov/ITDB-schema#42]
We hope you all have found much value out of the previous session, and we are continuing to provide the support needed to get the environments ready for FY19. 

Any questions or concerns to be discussed during the 2nd whiteboard session please post here.

Thank You.

**Comment by danielwyork** [comment]
We would like an update on https://github.com/ombegov/ITDB-schema/issues/40. It is BLOCKER that is preventing us from testing the AITPS submissions.
