### ISSUE TITLE
July 10 Weekly SRC files update

### ISSUE THREAD

**Issue by danielwyork** [ombegov/ITDB-schema#45]
Name: Daniel York
Organization: GSA eCPIC PMO
Urgency: High
Description of Issue: When should vendors expect to see the weekly update XSD Candidate (v1.9.0) (https://github.com/ombegov/ITDB-schema/tree/master/src)? It does not appear the weekly Monday evening update has been posted.

**Comment by ojedanico** [comment]
please file for directions on how to get to weekly update

**Comment by ojedanico** [comment]
Adding the path with screen shots to readme file so you can find the weekly updates. Hope to have it up shortly. In the mean time you can find the weekly updates under the Code tab by clicking on Release - just above the create new file button.

**Comment by danielwyork** [comment]
https://github.com/ombegov/ITDB-schema/releases

**Comment by ojedanico** [comment]
Thanks Dan!
