### ISSUE TITLE
CIO Rating Submissions

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#48]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: Was there a final decision regarding whether or not the CIO Rating will be submitted separately from other files? For example, will the CIO Rating still be submitted as part of the the Business Case in the Annual?

**Comment by GihaVillazon-REISys** [comment]
Good Afternoon, 

CIO Rating will follow the same submission process for Major Investments. When the investment does not allow/require a business case the CIO Rating node will be available for submission independently. However Type 1 Submission will not have the ability to submit the CIO rating independently, They MUST follow the existing process.

Thank You.
