### ISSUE TITLE
Warning Message - for CIO Evaluation 

### ISSUE THREAD

**Issue by GihaVillazon-REISys** [ombegov/ITDB-schema#49]
Good Afternoon,

As discussed, on the importance of having a warning message for the CIO Evaluation piece of the submissions. 
Please provide ideas on what the "Warning" Message should appear as.

We have also opened up a jira ticket as soon as the error message is finalized we will work towards implementing it. 

Thank You.

**Comment by GihaVillazon-REISys** [comment]
Below are the message we have implemented. 

**Warning Message**
Agencies are required to submit a CIO Evaluation Report only for their major investments. It is Optional for all other investments

**Error message** 
Agencies are required to submit a CIO Evaluation Report for all of their major investments, Type 01, during business case submission.

Thank You.

**Comment by SriramAvasarala** [comment]
Can we submit the CIO Rating as part of the Business Case Submission (similar to prior year) for all  major investments, Type 01? (or) do we need to submit the CIO Evaluation Reports separately? 
Example: 
<businessCase-update:cioRating> 
      <businessCase-update:cioRatingEval>1</businessCase-update:cioRatingEval> 
      <businessCase-update:cioComment>TEST</businessCase-update:cioComment> 
</businessCase-update:cioRating>

**Comment by GihaVillazon-REISys** [comment]
Yes, CIO Rating will be part of Major investments (similar to prior year). 

Thank You.
