### ISSUE TITLE
Submission Tentative Dates 

### ISSUE THREAD

**Issue by GihaVillazon-REISys** [ombegov/ITDB-schema#50]
As discussed and committed during the meeting, we are providing the tentative dates below:

- Final Draft Guidance  and A-11 July 31st (tentative)
- Pre-submission Aug 21 (tentative) 
- Budget Submission Sept 11 (tentative)

Thank You.

**Comment by murrayalex** [comment]
Thank you for posting this. Will the Final Draft Guidance on July 31 include the requirements for the Draft AITPS Submission on August 21? Or will those be coming out separately?

**Comment by GihaVillazon-REISys** [comment]
Dear CPIC Community, 

The process for this year’s draft IT Portfolio will require agencies to send an excel file via email to their respective Agency’s Desk Officer and cc OFCIO@omb.eop.gov. The response is due August 21st. Note: This date is subject to change based on the release of A-11 Guidance. This pre-submission information is important to help OMB understand agencies’ progress in the transition to standard investment reporting. In addition, this pre-submission will help facilitate any questions or concerns you may have in filling out this year’s budget. 

The excel spreadsheet must include the following fields for the submission:
Previous UII
Current UII
Shared Services Category
Shared Services Identifier
Bureau Code
Part of Agency IT Portfolio Summary
Type of Investment
Standard IT Infrastructure and Management Category 
Change in Investment Status Identifier
Agency Description of Change in Investment Status
Investment Title
Investment Description
FEA BRM Services – Primary Service Area

If you have any question regarding your agency’s IT Portfolio or this transition to standard investment reporting please reach out to your Desk Officer.
