### ISSUE TITLE
Baseline Change for Standard Investment Reports

### ISSUE THREAD

**Issue by danielwyork** [ombegov/ITDB-schema#53]
Name: Daniel York
Organization: GSA eCPIC PMO
Urgency: High
Description of Issue: Will Standard Investments reports require rebaseline change requests to change certain fields, like the the End User Standard Investment Reports Project table or project table.

**Comment by ojedanico** [comment]
The final answer on this is that there will be **No Baseline Changes** for Standard Investment Reports.
