### ISSUE TITLE
Eliminated Investments Funding Breakdown 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#55]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: Should eliminated investments with PY and CY funding break out their total PY and CY costs into IT Towers and Cost Pools aside from Security and Internal Labor?

**Comment by ojedanico** [comment]
There is no hard requirement, but Kelly has been encouraging them to break out as much as possible.

**Comment by danielwyork** [comment]
@ojedanico - at Passback the IT Cost Pool and IT Tower cost data will be required of investments on the Agency IT Portfolio. Will the IT Dashboard have a requirement for agency investments marked as 'eliminated' to also provide their IT Cost Pool and IT Tower cost data?

**Comment by ojedanico** [comment]
FY 2019 Requirements for IT Cost Pools: Throughout the FY 2019 cycle, Internal Labor is the only cost pool that will be required.  Internal Labor relates to Government FTE costs, which has been reported for years and removed to report as Internal Labor.  External Labor, Outside Services and Internal Services should be prioritized as they relate to M-17-22 efforts.  Optional and mandatory requirements will remain unchanged during FY 2020 cycle, but this may be adjusted based upon efforts to make this implementation easier. 
FY 2019 Requirements for IT Towers: IT Security and Compliance IT Tower costs are mandatory for all applicable Investments for the September 2017 submission.  For the January 2018 submission, all applicable IT Tower costs (except for Application and Delivery) will be mandatory.
OMB strongly encourages agencies to begin while these fields are optional and work with OMB desk officers on implementation challenges.

While there is no requirement for agency investments marked as 'eliminated' to provide their IT Cost Pool and IT Tower cost data is strongly encourages agencies do so.
