### ISSUE TITLE
IT Budget and Business Case Synchronized Data 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#56]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: After successfully submitting an IT Budget to the myuat-2019 Dashboard, I am unable validate or submit any investments through the Annual Operation. I was able to submit a sample IT Budget and verify a successful save through the GetITBudgetReport operation. However, when attempting to perform a annual update for one of the investments in my portfolio, I receive the following error: 

<sr:message level="error" xpath="/tns:operations[1]/tns:investmentInformation[1]/tns:annualSubmission[1]/tns:updateInvestment[1]">IT Budget does not have a record for unique investment identifier 011-000002502</sr:message>

**Comment by ojedanico** [comment]
This error should have been addressed with last release - please let us know if you are still receiving the same error.

**Comment by rydougherty** [comment]
Hi Nico- I am still seeing this issue in myuat-2019. I will email over files shortly.

**Comment by ojedanico** [comment]
This issue has been resolved. After doing a successful IT Budget upload, we now see values as expected in the database that were NULL before.  We also attempted an updateInvestment, and did not get the error that the investment doesn't exists in the IT Portfolio.
