### ISSUE TITLE
Tags Missing in MITBC

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#59]
In testing and reviewing the MITBC, it seems that the planningBudgetaryResource and dmeBudgetaryResources tags are no longer allowed.  Will this be fixed?

**Comment by TsitsiL** [comment]
Hi Courtney,
please send the XML request and response with errors you are getting that are preventing these tags. You can send them to itdashboardsupport@omb.eop.gov and please reference this GitHub issue.
Thanks!

**Comment by TsitsiL** [comment]
Hi Courtney,
Based on the latest guidance, planningBudgetaryResource and dmeBudgetaryResources tags will be allowed. We have a ticket ITD-759 to implement this that is currently scheduled for release in the 08A sprint - which is scheduled for August 14.

**Comment by courtneycorwin** [comment]
Hi TsiTsi,

I just had a customer test the MITBC today and received this error:

3.	Error 1871: Element '{urn:us:gov:businessCase-update}planningBudgetaryResourcesPY-1': This element is not expected. Expected is one of ( {urn:us:gov:businessCase-update}dmeGovernmentFTECostsPY-1, {urn:us:gov:businessCase-update}dmeGovernmentFTECostsPY, {urn:us:gov:businessCase-update}dmeGovernmentFTECostsCY, {urn:us:gov:businessCase-update}dmeGovernmentFTECostsBY, {urn:us:gov:businessCase-update}dmeGovernmentFTECostsBY_1, {urn:us:gov:businessCase-update}dmeGovernmentFTECostsBY_2, {urn:us:gov:businessCase-update}dmeGovernmentFTECostsBY_3, {urn:us:gov:businessCase-update}dmeGovernmentFTECostsBY_4_Beyond, {urn:us:gov:businessCase-update}maintenanceBudgetaryResourcesPY-1, {urn:us:gov:businessCase-update}maintenanceBudgetaryResourcesPY ). on line 40

I believe this issue means the fix was not deployed on the 14th. Can you follow up on this for me, please?  Thanks!

**Comment by courtneycorwin** [comment]
Given the date, this is a HIGH priority to get fixed.  Thank you!
