### ISSUE TITLE
Cost Detail Category Enumerations

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#64]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: In the updated Example files for the Investment Reports posted yesterday it insinuates that the Category field within the Cost Details tables will submit a code value to the IT Dashboard, instead of the the category name. Is this by design? If so, is OMB planning on releasing an updated enumerations document listing the Category to Code conversions?

**Comment by ojedanico** [comment]
Please see the data dictionary Guidance Data Dictionary tab here you will find enumerations for each section. High-lighted in soft red are all the enumerations
Example for End User Category 
1. Workspace 
2. Mobile Devices 
3. End User Software 
4. Network Printers 
5. Conferencing & AV 
6. IT Helpdesk 
7. Deskside Support "

**Comment by rydougherty** [comment]
Thanks Nico, I see the values for Network and End User. It looks like enumerations are still missing for Data Center & Cloud.

**Comment by ojedanico** [comment]
Sorry Ryan, 

Good catch - I could have swore I updated that field - they are built the same it's just 1-X in the order they show up in the guidance.

![image](https://user-images.githubusercontent.com/29411438/28875533-dbcd94a8-7763-11e7-8eed-4a67f1bae430.png)

**Comment by rydougherty** [comment]
Thanks Nico, that should close out this issue.
