### ISSUE TITLE
Capability Codes 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#65]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: The 95% XSD for the Investment Report shows Security investments will submit values for both the NISTFrameworkCategory and the capability, for each item in the Cost and Capabilities table. Last year, only the capability codes where submitted for each item within the Cost and Capabilities table. Each capability code acts as a unique identifier on its own. Is OMB planning on requiring the NISTFrameworkCategory submissions?

**Comment by ojedanico** [comment]
No, the NISTFrameworkCategory should be derived from the Cost and Capabilities code since its a one to one relationship. Please see Data Dictionary FY19 Agency Capability Codes tab for codes
