### ISSUE TITLE
Investment Reports - Projects, Contracts, and Performance Metrics

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#66]
It's my understanding that on the Investment Reports, investments can have one to may Projects, Contracts, and Performance Metrics (where applicable...not all investment reports call for these).  This is similar to how the Major IT Business Case Details accepts submission.  However, there doesn't seem to be a way for us to do that with these reports.  

If we're only expected to send/update one record of each type per report - please let me know.   Otherwise, we need a method to identify which records we are adding and which we are updating (in the Details report, we use agencyIds (or OMBIds depending on the vendor) and statuses.

Please let me know which direction you will be going in so we can prepare properly.  Thanks!

**Comment by ojedanico** [comment]
We are currently building this out to follow the same process as the business case. You will either do an add or update - if update use OMB ID in response or the Agency ID.

**Comment by rydougherty** [comment]
When will these adds and updates for projects, contracts, metrics be available in the schema?

**Comment by ojedanico** [comment]
Monday's (Aug 14th) weekly release v1.9.6
