### ISSUE TITLE
Investment Report - Performance Metrics

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#67]
My understanding is that the Performance Metrics included in some of the investments reports can have one to many Performance Metric Actuals (similar to the rule in the Major IT Business Case Details report).  However, based on the schema you've posted, Metric Actuals are separate from Performance Metrics.

**Comment by GihaVillazon-REISys** [comment]
Yes that is correct, we will have the fixes according to the guidance on August 14th.

Thank You.

**Comment by murrayalex** [comment]
Thanks, Giha. To provide us additional lead time on making this update, can you confirm that you will implement this update to metric actuals in the investment reports the same way they are implemented within the Business Case? If so, we can use that structure as a guide.

**Comment by GihaVillazon-REISys** [comment]
I would not recommend that, we will have an updated schema on the 14th, which will provide better insight on the implementation for Investment Reports. 

Thank You.

**Comment by courtneycorwin** [comment]
Great, thanks!
