### ISSUE TITLE
Investment Reports - Validate Only

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#69]
There isn't a tag to indicate that the submission is validateOnly for the reports like we have for all of the other submission reports.  Will we have this option?

**Comment by GihaVillazon-REISys** [comment]
We will be implementing this in the next Sprint. 

Thank You.

**Comment by TsitsiL** [comment]
Closing this issue - the response to the user's question has been provided. If user has follow-up question, issue can be reopened.
