### ISSUE TITLE
TBM Data for Type 04 Investments

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#70]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: The latest guidance version specified that Type 04 investments will not need to submit IT Tower and Cost Pool data. Will this change be implemented by making those nodes optional for Type 04?  Or will these nodes not be accepted for Type 04?

**Comment by ojedanico** [comment]
Yes, we are updating the schema to make those nodes optional for Type 04. This will be reflected in the August 9th release.

**Comment by murrayalex** [comment]
Thanks!
