### ISSUE TITLE
Investment Report OMB IDs: investmentReportID

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#71]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: Underneath the towerDetails node there is space for an investmentReportID node. What is the purpose of this node? Each investment will only submit one Details section, there will never be a need to submit multiple towerDetails nodes per investment.

There is no OMB ID for the investmentDetails, the Business case equivalent of towerDetails.

**Comment by GihaVillazon** [comment]
Hi Ryan,

With the updated schema, the investmentReportID node will be removed. 
OMB ID for the investmentDetails will not be required for submissions. 

Thank You.
