### ISSUE TITLE
Investment Report OMB IDs: costID

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#72]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: It appears that each Category within the Cost Details table will have an OMB ID associated with it. Is there a reason each Category needs an OMB ID? Presumably no one would submit Transition Services nodes (from the Network Cost Details table) more than once.

The Cost Pools and IT Towers have a similar set up, and they don't have any OMB IDs.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

This was a design decision to provide flexibility to update the Cost Details table for FY19.
We will reconsider if this option is required for FY20.

Thank You.

**Comment by rydougherty** [comment]
Hi Giha, Thanks for the response. Will I be able to update Cost Details values without the costID node?

**Comment by GihaVillazon** [comment]
The OMBID can also be used for updates. 

Thanks
Giha

**Comment by rydougherty** [comment]
The costID and OMB ID are the same thing. Can we update through the category since that acts as a unique identifier as well?

**Comment by GihaVillazon** [comment]
Yes, decision was made to update through category. 

Thank You.

**Comment by GihaVillazon** [comment]
Closing this ticket, should you need further clarification the ticket can always be reopened. 

Thank You.
