### ISSUE TITLE
Investment Report OMB IDs: projectID

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#73]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: Within both the Network and End User Projects Tables, there is a Project ID field. It is therefore unclear whether or not the projectID field in the xsd represents the Project ID field in the guidance or the OMB ID for that row item.

The business case solves a similar dilemma by having both a projectID field (OMB ID) and a uniqueProjectID field (field listed in Guidance).

**Comment by GihaVillazon-REISys** [comment]
We are in the midst of making updates to the Schema and the updates will be available for you on the 14th of August. It will enclose the fields for projectID vs the OMB ID.

Thank You.
