### ISSUE TITLE
Investment Report OMB IDs: metricID

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#74]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: Within both the Network and End User Performance Metrics Tables, there is a Metric ID field. It is therefore unclear whether or not the metricID field in the xsd represents the Metric ID field in the guidance or the OMB ID for that row item.

**Comment by GihaVillazon-REISys** [comment]
The field represents the metricID.

Thank You.

**Comment by rydougherty** [comment]
Thanks Giha, can you confirm the metricID field will function as the OMB ID, just as it does in the business case?

**Comment by GihaVillazon** [comment]
Yes, one of the IDs could be leveraged to perform any updates. 

Thank You.
