### ISSUE TITLE
Eliminated Investments

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#75]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: The scenarios that were laid out at the vendor white boarding sessions include several situations where investments should be marked as eliminated. Can you provide additional guidance on how those investments should be reported in subsequent fiscal years? For example, the scenarios show that an eliminated investment could have funding in PY and CY and $0 in BY. Would Agencies need to report that investment again in BY20 (with $0 in CY and BY) and again in BY21 (with $0 in all years)? Would they remain marked as "Eliminated" in those future budget year submissions?

Further clarification would be appreciated.

**Comment by ojedanico** [comment]
I will need to consult with Kelly to understand the business rules for future budget year submission on "Eliminated" investments.

**Comment by ojedanico** [comment]
Yes, see scenario below 

![image](https://user-images.githubusercontent.com/29411438/28985360-313c448e-7930-11e7-8d51-3e40805d1a36.png)

**Comment by murrayalex** [comment]
Thanks for the udpate, Nico!
