### ISSUE TITLE
Current validations under Quick Link files

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#76]
Name: Sriram Avasarala
Organization: Department of Treasury
Urgency: Medium
Description of Issue: The validations link under Quick links still pointed to old validations. Can you update the link and post the new validation rules?

**Comment by GihaVillazon** [comment]
Please follow the link below to FY19 Validations. 
Data Dictionary and Validation are located in the below link:
https://github.com/ombegov/ITDB-schema/tree/master/draftBY19
Thank You.

**Comment by GihaVillazon** [comment]
Good Morning,

Validations V1.9.4.xlsx is the most recent updated Spreadsheet. Posted in GitHub on August 7th. 

Thank You.
