### ISSUE TITLE
Security Spending Errors

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#77]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: For Security Investments, we are encountering a data validation error within the AITPS that requires IT Tower Security & Compliance Spending to match the Investment Funding Total:

For Investments with Standard IT Infrastructure and Management Category as '02' the Total IT Security Spending for CY (0.001000) must be equal to the sum of DME and O&M Agency CY Funding (50.843018). 

Based on past COP and Guidance training's, it was our understanding that Agencies would be allow to submit IT Management and other IT Tower expenses within their Security investments. Is this no longer OMB's intention?

**Comment by rydougherty** [comment]
Following up- it appears that having the values be equal does not make this error go away- My guess is this is a rounding issue somewhere.

                <response-ITBudget-ext:ResponseInformationLevel>1</response-ITBudget-ext:ResponseInformationLevel>
                <response-ITBudget-ext:ResponseLogDescription>Error: For investments with Standard IT Infrastructure and Management Category as '02' the Total IT Security Spending for CY (50.843018) must be equal to the sum of DME and O&amp;M Agency CY Funding (50.843018).</response-ITBudget-ext:ResponseLogDescription>
            </response-ITBudget-ext:ResponseInformation>
            <response-ITBudget-ext:ResponseInformation>
                <response-ITBudget-ext:ResponseInformationLevel>1</response-ITBudget-ext:ResponseInformationLevel>
                <response-ITBudget-ext:ResponseLogDescription>Error: For investments with Standard IT Infrastructure and Management Category as '02' the Total IT Security Spending for BY (50.84177) must be equal to the sum of DME and O&amp;M Agency BY Funding (50.84177).</response-ITBudget-ext:ResponseLogDescription>

**Comment by bill-gehrke-hhs** [comment]
I can confirm we are seeing this issue and believe the issue is that it is always comparing the IT tower Security and Compliance Costs to the PY funding totals. So, if the funding source amounts for PY, CY, and BY are 1, 2, and 3, respectively, entering 1 for the Security and Compliance tower for PY, CY, and BY clears the error.  Entering 1, 2, and 3, which would be expected, generates errors for CY and BY but not PY.

**Comment by ojedanico** [comment]
Bill, Thanks for the follow up I will pass this info along and see if we can get this resolved.

**Comment by ojedanico** [comment]
This bug was fixed on 8/3 and will be resolved in the 08A release scheduled for Aug 14th.

**Comment by rydougherty** [comment]
What did OMB fix here? Can you now submit less Security and Compliance funding than the investment's total funding?

**Comment by ojedanico** [comment]
Ryan, the fix is that the BY and CY validations that were incorrectly using PY values in their evaluations have been corrected to use BY and CY values.

**Comment by rydougherty** [comment]
Thanks Nico, will the final validation compare the Funding Sources values against the IT Security Towers to ensure they are equal? Or, will the validation simply prevent IT Security tower spending from exceeding the Funding Source totals?

**Comment by rydougherty** [comment]
I wanted to follow up here, and see if you are able to answer the question above? We were under the impression that Security Investments could have funding in other IT Towers, such as IT Management. Therefore the Security Tower spending should be less than or equal to the total Investment spending.

**Comment by ojedanico** [comment]
The validation simply prevent IT Security tower spending from exceeding the Funding Source totals. Therefore the Security Tower spending should be less than or equal to the total Investment spending.

**Comment by rydougherty** [comment]
Excellent news- thanks Nico

**Comment by murrayalex** [comment]
We are still seeing the following error after last nights release: Error: For investments with Standard IT Infrastructure and Management Category as '02' the Total IT Security Spending for PY (0.001000) must be equal to the sum of DME and O&M Agency PY Funding and Contributions (51.792319).

Based on the above response from Nico, we feel this is incorrectly triggering.

**Comment by ojedanico** [comment]
I have our development looking into the issue - will get back to you shortly

**Comment by ojedanico** [comment]
Alex 

Are you getting this error when uploading the IT Budget or a Standard Investment Report?

**Comment by murrayalex** [comment]
IT Budget

**Comment by ojedanico** [comment]
This validation is being to removed. Kelly's message to the CPIC CoP has been that the total cost for SIRs would not be enforce to equal the total tower cost. 

Sorry for the confusion I should have caught this earlier.

**Comment by ojedanico** [comment]
Yes it will be in the hotfix scheduled for Monday night release

Nico

On Aug 22, 2017, at 1:55 PM, murrayalex <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, Nico. We can get around it for now to test, but do you have a targeted fix date?
