### ISSUE TITLE
IT Budget XML Errors Reporting

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#82]
In testing the IT Budget XML, we have encountered some issues related to the the error reporting that makes debugging potentially more difficult.  First, it appears the UII is not being displayed, as:

> •IT Budget submission failed◦IT Portfolio with UII: : No Errors
◦IT Portfolio with UII: : 
◾Error: For investments with Standard IT Infrastructure and Management Category as '02' the Total IT Security Spending for CY (2) must be equal to the sum of DME and O&M Agency CY Funding (2).
◾Error: For investments with Standard IT Infrastructure and Management Category as '02' the Total IT Security Spending for BY (3) must be equal to the sum of DME and O&M Agency BY Funding (3).
◦IT Portfolio with UII: : No Errors

With an expected 600-700 investments in our portfolio, this is problematic for identifying any issues in testing and submission.

Additionally, portfolio-level errors in the IT Portfolio should not be reported for each investment.  For example, if we do not include an investment with Infrastructure & Management Category 3, we recive the following error:

> ◦IT Portfolio with UII: : 
Error: At least one investment in the agency's IT portfolio with Type of Investment '05' and Change in Investment Status Identifier is '1', '2', '3', '4', '5', '10', or '11' must have Standard IT Infrastructure and Management Category as '03'.
◦IT Portfolio with UII: : 
Error: At least one investment in the agency's IT portfolio with Type of Investment '05' and Change in Investment Status Identifier is '1', '2', '3', '4', '5', '10', or '11' must have Standard IT Infrastructure and Management Category as '03'.

This is repeated for every investment (so again, potentially 600-700 times) rather than appearing once at the top of the errors.

This is certainly lower priority than other issues as the main effect so far appears to make testing more time-consuming but does not prevent testing or a valid submission.

**Comment by ojedanico** [comment]
the UII display issue was resolved and should be fixed with the 08A release. You should be able to test now. 

For the portfolio-level errors we are working into the 8B release scheduled Aug 22.
