### ISSUE TITLE
Get File for Investment Reports

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#83]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The Get File for Investment Reports is not included in the current Schema. Is there a projected release date for the Investment Report Get File?

**Comment by GihaVillazon** [comment]
Hi Ryan, 

It is the next priority will be available no later than the 28th of August. 

Thank You.

**Comment by rydougherty** [comment]
Hi Giha- I see there is no Get File for the SIR within the Final XSD released last night. When will the xsd on Github contain the Get File and a sample response? And, will this be included for the release on the 22nd?

**Comment by GihaVillazon** [comment]
Hi Ryan,

Yes the plan is with the next release.

Thank You.

**Comment by rydougherty** [comment]
Thanks Giha, that is good to hear. When can we plan on seeing the Get File and sample response in the xsd on Github?

**Comment by ojedanico** [comment]
This will be available for testing against the UAT Aug 22nd. 

https://github.com/ombegov/ITDB-schema/tree/v1.9.6/src/InvestmentReport

**Comment by ojedanico** [comment]
We currently working on the Get File for the SIR and how the response files will be formatted. We post as soon as possible.

**Comment by ojedanico** [comment]
The Get File has been completed and will go through with the 8B release for Aug 22nd.

**Comment by rydougherty** [comment]
Thanks Nico, I see the Get File examples. Will a Sample Response file also be provided before August 22nd?

**Comment by ojedanico** [comment]
We are working on the sample response files - The tags will also be up today

**Comment by rydougherty** [comment]
Hi Nico- Is there a reason the <item0>, <item1> etc tags are used throughout the response file? It is an odd way to list the information since we do not send it over itemized or really in this format at all. Furthermore, it complicates efforts to parse and compare the files, since there is no consistent handle to latch on to. And all these nodes already have clear parent nodes (investmentCostDetail in the example below). If this was an unintentional implementation please let us know as soon as possible, as this itemization has critical implications for our tool. 

Response:
<investmentCostDetail><item0><PY>0.001</PY><CY>0.002</CY><BY>0.003</BY><category>1</category></item0><item1><PY>0.005</PY><CY>0.006</CY><BY>0.007</BY><category>2</category></item1><item2><PY>0.009</PY><CY>0.01</CY><BY>0.011</BY><category>3</category></item2><item3><PY>0.013</PY><CY>0.014</CY><BY>0.015</BY></investmentCostDetail>

**Comment by rydougherty** [comment]
Our expected implementation is below. Please notice the difference in the investmentCostDetail nodes below. Also note this implementation also matches the structure listed in the xsd:

`<investmentCostDetails><investmentCostDetail><PY>0.001</PY><CY>0.002</CY><BY>0.003</BY><category>1</category></investmentCostDetail><investmentCostDetail><PY>0.005</PY><CY>0.006</CY><BY>0.007</BY><category>2</category></investmentCostDetail><investmentCostDetail><PY>0.009</PY><CY>0.01</CY><BY>0.011</BY><category>3</category></investmentCostDetail><investmentCostDetail><PY>0.013</PY><CY>0.014</CY><BY>0.015</BY></investmentCostDetail></investmentCostDetails>`

**Comment by ojedanico** [comment]
We agree that the structure of the “get” response should mirror the structure of the submission. We did not like the function in our API that outputs XML in the current “itemized” format (e.g elements with names like item0, item1, item2, etc), but we didn’t have time to do anything about it while implementing the “get” feature

we were able to squeeze this work into Monday's release, so this issue will be resolved with the 08B hotfix deployment scheduled the 28th.

**Comment by ojedanico** [comment]
As promised here is the link to the response files

https://github.com/ombegov/ITDB-schema/blob/master/src/InvestmentReport/examples/response.xml

**Comment by ojedanico** [comment]
https://github.com/ombegov/ITDB-schema/blob/v1.9.8/src/InvestmentReport/examples/get.xml
