### ISSUE TITLE
isActive Nodes in Investment Reports

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#84]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: In the current schema, there are no <isActive> nodes for contracts, projects, performance metrics etc within the four investment reports. These <isActive> nodes are critical for deactivating old or inaccurate data and restructuring investments.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

These nodes will be available with the updated schema released on the 28th of August. 

Thank You.

**Comment by GihaVillazon** [comment]
Closing this ticket, should you need further clarification feel free to reopen the ticket. 

Thank You.

**Comment by rydougherty** [comment]
I see these nodes were not included in Monday's schema update. Can you please provide a timeline of the following:

- When we will be able to view these nodes on the Github xsd for the SIR?
- When will these nodes be released to the myuat-2019 Dashboard?

**Comment by courtneycorwin** [comment]
I thought isActive was being replaced with the operations tab.  The operation tag has add, update, and delete options.  Is this correct?

**Comment by rydougherty** [comment]
Traditionally Add/Update is separate from Active/Deactive:

                <businessCase-update:reviseUpdatePerformanceMetricActual>
                  <businessCase-update:performanceMetricActualID>50897</businessCase-update:performanceMetricActualID>
                  <businessCase-update:performanceMetricActualResult>99.66</businessCase-update:performanceMetricActualResult>
                  <businessCase-update:performanceMetricDateofActual>2013-04-01</businessCase-update:performanceMetricDateofActual>
                  <businessCase-update:performanceMetricComment></businessCase-update:performanceMetricComment>
                  <businessCase-update:isActive>active</businessCase-update:isActive>
                </businessCase-update:reviseUpdatePerformanceMetricActual>

**Comment by courtneycorwin** [comment]
But since there aren't going to be rebaselines for SIRs, I think that the add operation replaces addPerformanceMetricActual, addPerformanceMetric, etc; update replaces updatePerformanceMetricActual, updatePerformanceMetric, etc.  Finally, I'm hoping that the delete operation is similar to the existing deactivate process, but I've asked for more clarification on that in a separate post.

I'm not correcting you, Ryan, I've just asked similar questions and I want to make sure my understanding is consistent :)

**Comment by rydougherty** [comment]
Based upon Giha's comments above, and the historical implementation of isActive nodes, we are under the impression that the isActive nodes will be implemented and utilized to deactivate row items within the SIRs. If OMB is planning on dropping these nodes, or not utilizing them in this manner, please let us know.
