### ISSUE TITLE
Question: OMBIds and AgencyIds for Capabilities

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#89]
I believe an issue has been posted a few times about IDs missing in the IT Security & Compliance SIR for the capabilities.  I believe you said that OMB and Agency IDs will be available in the schema when you publish the updated version on the 14th.

Also, I believe we've discussed several times that the capabilities that will be included in this SIR will all be new regardless of whether they were submitted as part of the Major IT Business Case in the past.  We can reuse the IDs or create new ones, but regardless of what we choose, they will all be new capabilities.  No "duplicates" will be created if we opt to use a new agencyId and no errors will be returned if we use an agencyId that was used to submit a capability as part of the Major IT Business Case last year. 

Again, I know we've discussed this several times, but I have several customers that would like to see written confirmation from you all on this.  Thanks!!

**Comment by GihaVillazon** [comment]
Hi Courtney, 

Yes, the updated schema will have the OMG and Agency IDs, however we had to create a separate release for the SIR schema updates. 
To further clarify Agency Ids, The system is set up to create new IDs for investments which are being split. 
Hope it helps. 
Thank You.
