### ISSUE TITLE
Send email to Federal CPIC Community to communicate Submission Windows 

### ISSUE THREAD

**Issue by danielwyork** [ombegov/ITDB-schema#90]
Name: Daniel York
Organization: GSA/eCPIC PMO
Urgency: Medium 
Description of Issue: Please arrainge for an email to be sent from OFCIO to the Federal CPIC Community formally informing them of the Agency IT Portfolio, Major IT Investment Business Case, and Standard IT Investment Reports submissions dates as listed in the [ReadMe](https://github.com/ombegov/ITDB-schema/blob/master/README.md) file.

**Comment by ojedanico** [comment]
Gordon is double checking with Kelly to make sure this information has been shared with the CoP.  He is under the impression it has been shared. I will let you know once I get concurrence from them.

**Comment by ojedanico** [comment]
Times for submission have posted on MAX and Kelly has communicated to CoP.

**Comment by TsitsiL** [comment]
Kelly confirmed that she sent out the email yesterday. Closing this ticket.
