### ISSUE TITLE
Missing New Risk Category

### ISSUE THREAD

**Issue by suchun** [ombegov/ITDB-schema#91]
Name: Sue Hu
Organization: Department of Treasury
Urgency: Medium
Description of Issue: The enum of RiskType in the schema only goes up to “19”.  In FY19 guidance, a new Risk Category “Record management” was added, the number of Risk Categories should be 20, the last enum should be 20, looks like the schema is missing the newly added category?

**Comment by GihaVillazon** [comment]
Hi Sue, 

Please follow the link below, I have also copied and pasted part of the nodes for you. 
Scroll down to line 359 you will see:

      <enumeration value="20">
        <annotation>
          <documentation>records management</documentation>
        </annotation>
      </enumeration> 

In https://github.com/ombegov/ITDB-schema/blob/v1.9.5/src/BusinessCase/Subset/businessCaseFacet.xsd

Thank You.

**Comment by suchun** [comment]
Ok, I looked at a wrong folder "draftBY19".
