### ISSUE TITLE
SIR Errors

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#92]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: We have noticed the way the errors are structured for the SIR's are different than the Business Case. Does the IT Dashboard group have guidance on the difference between Critical Errors, Logical Structure Errors, and the itemized errors?

**Comment by GihaVillazon** [comment]
Hi Ryan, 

Below is a soft breakdown of the errors. 
We will post more thorough document by the end of the week. 

•	**Critical Errors** are any basic violations that break the submission and make it impossible or imprudent to process, things like submitting a UII for another agency
•	**Logical Structure Errors** are issues with the XML that are not catchable via schema validation, like sections that are invalid for the report type (e.g. a Data Center report with a costAndCapabilities section)
•	**All other errors and warnings** are those that apply to the various sections, some of which may be structural in nature, but most of which will be for enforcing business rules
•	**Any lists of errors or warnings that include more than 1 item** will show those items wrapped in tags like <item0>, <item1>, <item2>, etc (personally I would prefer to see them wrapped in repeating tags with contextual names, like <error> and <warning> but this might be more trouble than it’s worth to implement)

Thank You.

**Comment by GihaVillazon** [comment]
Hi Ryan, 

We will post a link to sample response files for better clarity.

Thank You.

**Comment by ojedanico** [comment]
until then hopefully this helps...

1. All errors for a given tower in a submission will prevent that tower from saving. A tower with warnings but no errors will save. A submission that includes multiple towers will not save any towers that have errors, but it will save all towers that have no errors.

2. The structure of a response includes 2 main components: 1) one or more tower elements that echo the towers in the submission, 2) a “response" element that shows the submission status for each tower, along with any errors or warnings. Most errors are currently duplicated in the following way: Any error related to a given section of a tower is shown: 1) within the related section, 2) in a summary at the bottom of the tower, along with all other errors for that tower, 3) in a summary in the “response” element, along with all other errors for all other towers in the submission.

3. All Critical Errors short circuit the entire validation process, so a response for a submission with both Critical Errors and other validation errors will only show the Critical Errors. For non Critical Errors, there might be some errors that cascade based on validation logic (i.e. some logic might short circuit other logic), but for the most part all errors detected in the submission are shown at once.
