### ISSUE TITLE
Cost Pools error

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#93]
Name: Sriram Avasarala
 Organization: Treasury
 Urgency: Medium
 Description of Issue: We are getting the following error when we submit the cost pool without PriorYearAmount . As per our understanding, if we don't have value for PY then we can omit that tag. Please let us know  how do we handle this scenario if there are no values for PY.

Error message: Error 1871: Element '{urn:us:gov:update-ITBudget-ext}CurrentYearAmount': This element is not expected. Expected is ( {urn:us:gov:update-ITBudget-ext}PriorYearAmount ). in input on line 56

Sample XML:
-<CostPools>
-<CostPool>
<CostPoolCategory>Total Internal Labor Cost</CostPoolCategory>
<CurrentYearAmount>0.660870</CurrentYearAmount>
<BudgetYearAmount>0.660870</BudgetYearAmount>
</CostPool>

**Comment by GihaVillazon** [comment]
Hi Sriram,

The only time PY is not required is when the status = New. 
If this is an existing investment it should have PY value. 

Thank You.

**Comment by SriramAvasarala** [comment]
Can you confirm the following?
1. The only time we can omit the PY tag from the ITP XML is when the status is NEW for all investment types. 
2. ITP's require Total Internal Labor Cost pool and PY , CY and BY dollars when Type of Investment is not '04'.
3. If we don't have cost for PY , can we submit the value as 0?

The error message doesn't provide UII information. Are you planning to update error messages in the upcoming release?

**Comment by GihaVillazon** [comment]
Hi Sriram, 

Please review the responses below.

1.	The only time we can omit the PY tag from the ITP XML is when the status is NEW for all investment types. **Yes** 
2.	ITP's require Total Internal Labor Cost pool and PY , CY and BY dollars when Type of Investment is not '04'. **Yes** 
3.	If we don't have cost for PY , can we submit the value as 0? **No, zero dollar is not an accepted value for PY, as we are capturing number for better analysis, except for all optional Standard Investment Reports** 
The error message doesn't provide UII information. Are you planning to update error messages in the upcoming release? **Yes**

Thank You.

**Comment by SriramAvasarala** [comment]
3.If we don't have cost for PY , can we submit the value as 0? No, zero dollar is not an accepted value for PY, as we are capturing number for better analysis, except for all optional Standard Investment Reports.

We have some investments that don't have Total Internal Labor. Can you provide some guidance on how we can handle this scenario if zero dollar is not accepted. Do you expect us to report $1 to pass the validation?

**Comment by GihaVillazon** [comment]
Hi Sriram,

In that case the 0 will be acceptable value for all PY, CY, BY.
I hope this helps.

Thank You.

**Comment by SriramAvasarala** [comment]
Ok, I want to make sure that there are no validations if we submit 0 value for PY. Can you confirm? In your prior statement you said zero is not acceptable. "3.If we don't have cost for PY , can we submit the value as 0? **No, zero dollar is not an accepted value for PY**, as we are capturing number for better analysis, except for all optional Standard Investment Reports."

**Comment by GihaVillazon** [comment]
Hi Sriram,

System will not generate an error **IF PY, BY, and CY = 0.** In your earlier statement " investments that don't have Total Internal Labor" in that case all values will be 0 correct? it should be fine to submit with that scenario.

Thank You,

**Comment by SriramAvasarala** [comment]
Thanks Giha. Yes, The PY, CY and BY values will be 0.

**Comment by SriramAvasarala** [comment]
Giha, I am getting cost pool validation error for Type 04-Funding Transfer Investment even if I omit the cost pool tag (or) submit empty node <costPools/>. Please let us know if we need to submit the costpool data for Type 04 investments with Total Internal Labor node with PY, CY and BY values as 0?

**Comment by GihaVillazon** [comment]
Please post your error. 
Thank You.

**Comment by GihaVillazon** [comment]
Ticket is being worked through helpdesk.

**Comment by SriramAvasarala** [comment]
Giha, here is the error: Alert  Error 1871: Element '{urn:us:gov:update-ITBudget-ext}FunctionalBusinessSponsorInformation': This element is not expected. Expected is ( {urn:us:gov:update-ITBudget-ext}CostPools ).

**Comment by GihaVillazon** [comment]
Hi Sriram,

Please try submitting the data once again, the issue was fixed with Sprint 2017.08A.

Thank You.

**Comment by SriramAvasarala** [comment]
Giha, I am still getting the same error. 
alert Error 1871: Element '{urn:us:gov:update-ITBudget-ext}FunctionalBusinessSponsorInformation': This element is not expected. Expected is ( {urn:us:gov:update-ITBudget-ext}CostPools ).

**Comment by GihaVillazon** [comment]
The team informed that SIR was disabled on UAT last night while we work on it in the current release, which will be deployed on August 28 COB. We advise you retest this again then. 

Whenever you do retest, one suggested way of submitting the tags is to include the Cost Pools and IT Towers nodes with all of the elements, so something like what is shown below:
Example:

      </DME>
      <CostPools>
        <CostPool>
          <CostPoolCategory>Total External Labor Cost</CostPoolCategory>
          <PriorYearAmount>0</PriorYearAmount>
          <CurrentYearAmount>0</CurrentYearAmount>
          <BudgetYearAmount>0</BudgetYearAmount>
        </CostPool>
      </CostPools>
      <ITTowers>
        <ITTower>
          <ITTowerCategory>Total IT Management Cost</ITTowerCategory>
          <PriorYearAmount>0</PriorYearAmount>
          <CurrentYearAmount>0</CurrentYearAmount>
          <BudgetYearAmount>0</BudgetYearAmount>
        </ITTower>
      </ITTowers>
      <FunctionalBusinessSponsorInformation>

**Comment by SriramAvasarala** [comment]
Giha, The error is not related to SIR report I am not sure why your team is referring to SIR was disabled for IT Portfolio Cost Pool validation error. Tsitsi mentioned that we should omit cost pool tag for Type 04 Funding Transfer investment when I send the sample xml file to support email yesterday. So please let us know what you fixed in yesterday's deployment to resolve the issue and which option we should go with to submit the final data for Type 04 Investments.
1. Omit the cost pool tag completely 
2. Submit the data as you mention above with all zeros. 
Thank You.

**Comment by TsitsiL** [comment]
Closing this issue to create a new one #110 fo rthe last reported problem of errors received when submitting with empty tags.
