### ISSUE TITLE
Submission Timeline

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#99]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Low
Description of Issue: Will Agencies be able to validate MITBC submissions prior to the window opening on September 11th? I understand that in order to meaningfully validate they would have to first submit an IT Budget, and they wouldn't be able to actually submit data to the Dashboard until window opens. However, once your IT Budget submission is complete, can you send validateOnlyIndicator="true" files to the businesscase url or will that url be completely shut off?

**Comment by ojedanico** [comment]
yes on the UAT server. The submission server for MITBC will not open until September 11th. There are two separate submission windows one for budget submission and one for MITBC. The UAT will stay open so you can continue to test.

**Comment by TsitsiL** [comment]
Ryan,
You will not be able to validate only MITBC in production prior to September 11. The operation for MITBC will not be available in production before then. You can validate only  in UAT as Nico has stated. As of September 11, at 6:30 pm EST , you will be able to set validateOnlyIndicator to true/false for MITBC in production.
I will go ahead and close this issue and if you have follow up questions, we can reopen it. Thanks!
